$axure.loadCurrentPage({
  "url":"主页_1.html",
  "generationDate":new Date(1499312883145.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ecf4245b15854c3181e186bbcb16e2e3",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b8c4c5654f974ef5bc7555a3046f37ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":1130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2850fb3577304ca68e56896a96f93f40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":1130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_1/u0.png"}},
{
          "id":"d2b3c61458df48c5b4c131279b824ec2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":358,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9927ee8a0f449b8244ad55849989bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":358,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.jpg"}},
{
          "id":"672f55c10b294dcf82b1194b3b723afe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":222},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4eb9e9190ca481383001aa19afe9b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":222},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择配送农场",
                      "target":{
                        "targetType":"page",
                        "url":"选择配送农场_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"0da3543ce74046aab9a2d000b8f23084",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":269},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53da616c6cc44215b9c336194f954009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":269},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0843e66d1bc43c091493b1e04be561a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":222},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eccc8f5fb2f14d9989a612560193adc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":222},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农场列表",
                      "target":{
                        "targetType":"page",
                        "url":"农场列表_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"67dc4ef902fb4724b0e975e1e1febf88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":269},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"975c2a995cb94ee4a917413b40a060bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":269},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f55b5bc27f844c2b9fdcbad3ec36e9ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":222},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047478fabd3749ad91ecd43682b13d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":205,
                  "y":222},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"14632c1c73fa4868b5b0a19e271cc649",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":269},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45d69b331b164235a7ed115beca34bad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":269},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aa58b74467244adbc685d2cd9a9db5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":222},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e93a2d2be29b47fd864c19f7747447f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":222},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"af8edbde69db4991b0237f80c585f0f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":269},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98ab1120a9de47828834156d07f32bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":269},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db9bf675f5bc40a485ba1e5d6f2fd1a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":300},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5b79eff4035440c854456a9f9d8c3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":300},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"c3d0e3f702f54306a514aa74e49d2d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":347},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e99253ba832434a8b87e188e3aabe19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":347},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83e6c357319b4dc5925fb6ee52ed543b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":300},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac889aff8c8f4726b43f32983f54c63d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":300},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"82c11b5d44714faeb2a51aed88d50bfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":347},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"670e839269f04303be670638232c6c25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":347},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"047a6801d8c848ed8753e810c42395ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":300},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e68effb9a31e4054bcaf40139613c61f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":300},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"9d077fc694554932a8f6dfbd4d14d384",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":203,
              "y":347},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba6e17919f3a47699a666a051e561cfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":203,
                  "y":347},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dfccfd165e440508944d63134c59fe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":300},
            "size":{
              "width":45,
              "height":45},
            "cornerRadiusTopLeft":"45"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d07da754bc0499c8f2293e0aec6b796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":300},
                "size":{
                  "width":45,
                  "height":45},
                "cornerRadiusTopLeft":"45"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员充值",
                      "target":{
                        "targetType":"page",
                        "url":"会员充值_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u4.png"}},
{
          "id":"9131d49ebfa043e09d4aa316b9b2fb8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":347},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c189cfcbc0249408f486f3a0da74a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":347},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce385ef6206145269209c88fc644c58a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":5},
            "size":{
              "width":331,
              "height":30},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a1a0a2c1d644c6b8473f7c90d229765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":5},
                "size":{
                  "width":331,
                  "height":30},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_1/u36.png"}},
{
          "id":"1891c4c2f2994f3987b81eab3f2c71c1",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":8},
            "size":{
              "width":10,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u38_line.png"}},
{
          "id":"e38a9debb8a2401994bc14711fe4d204",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":302,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b7d19ba0bd04480a1e2c335a533c05b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":302,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ed177d1ff6045c0a584c5e4dc9056f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":380},
            "size":{
              "width":358,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946525f0d9964780b93b712a408ce36b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":380},
                "size":{
                  "width":358,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_1/u41.jpg"}},
{
          "id":"a95292abe8984b539739309463bf5061",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":534},
            "size":{
              "width":358,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf43815ddaea4291a418c9c6195a641a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":534},
                "size":{
                  "width":358,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u43.jpg"}},
{
          "id":"b03e1c322d114a41a5f2b00ca044ebd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF169BD5},
            "location":{
              "x":166,
              "y":190},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75772e94bfa04c418232ed15901cfe97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF169BD5},
                "location":{
                  "x":166,
                  "y":190},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u67.png"}},
{
          "id":"fc52e3fba047438a9c38fedff74a920f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":190},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56769b25d8c045c99c8b995a36a26d93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":190},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u69.png"}},
{
          "id":"e9ceb532e1584b67a50fcedf8d0cd138",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":190},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a55f6bd018ce4164b43b9c25b05795ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":199,
                  "y":190},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u69.png"}},
{
          "id":"d9930af1706644749fb0502e3efe4728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":694},
            "size":{
              "width":359,
              "height":396},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd4f70644ebe4c71a6de86df62862c68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":694},
                "size":{
                  "width":359,
                  "height":396},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_1/u51.png"}},
{
          "id":"5cdf3158bec24eaa937a9814895371bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":724},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_1/u53_line.png"}},
{
          "id":"360c5b1ef13544859e8d4719c1894030",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":708},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5f697f178a48e393dec104e2f9a49f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":708},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"611f4bd42b52453d8cc3ff62a5c8c57f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":810},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_1/u53_line.png"}},
{
          "id":"0713ee2a12c2453eb3d056e8b97ce039",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":735},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03d71402ad214325b211f2343eaa8c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":735},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u79.jpg"}},
{
          "id":"dca972403f784963af10d6912d39b4d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":737},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22ae06a404ed4d68863f616c78dc345b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":737},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3828f14f564047c5ba5ea0ab0f01e942",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":93,
              "y":772},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97f5f4f95a1d423f9f1c7d7eef5d7b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":772},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"734225881f1e4f0fae7b35d2c8cb1a99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":93,
              "y":796},
            "size":{
              "width":69,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9708ca65dd5c4572a5eff3fa932cdd5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":796},
                "size":{
                  "width":69,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9668cf361f9a41d1b05206d6c7c2ab91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":183,
              "y":796},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1720a7e6c7e495db8045d7dfd677f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":183,
                  "y":796},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c83fbe3a8d8f4203987011645d68f4ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":896},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_1/u53_line.png"}},
{
          "id":"4da7efdef7dd4240a730f25273c645d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":821},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d08bca4a8ac4df98eb2282129892b61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":821},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u90.jpg"}},
{
          "id":"dad485e70eb5446c859e399c0f0a8a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":95,
              "y":823},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17a2a0a989244bf7801fc32062f933b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":95,
                  "y":823},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ce69e5bcffb48a3ac4df2f986b84c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":95,
              "y":858},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c8a7c1a6a734c6583b494739956377f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":858},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5af40f468d684c74b97a8315870f6db1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":95,
              "y":882},
            "size":{
              "width":69,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cac11f16330342e6a9eb126c8de5cf3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":882},
                "size":{
                  "width":69,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"371433e93f244b90936207cb85942e82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":185,
              "y":882},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b9b7a32c744704a0b379b15ee530a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":185,
                  "y":882},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e1ae3bb6a264cddbd3226cb71212bdf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":981},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_1/u53_line.png"}},
{
          "id":"43473d7ab0894c759ae33aa7b527f496",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":906},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7587c1485364fefa539fdfb063b5b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":906},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u101.jpg"}},
{
          "id":"9e096c6b84e64c0f9fe196e9ff2d8b0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":908},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"586324804c844c69bea9333444008b09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":908},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69d8131ce8b84778a80cff1f8cd3103f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":93,
              "y":943},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68d86c0a10da444f926bbc0b7b645f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":943},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa8fc95d68374adf989c8ab48e8aed29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":93,
              "y":967},
            "size":{
              "width":69,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72995f80d24d4ee48edec291511198e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":967},
                "size":{
                  "width":69,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9e42039be7143aa874df67773d06e69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":183,
              "y":967},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"798fade9a9f449cdbc0316c90e00fec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":183,
                  "y":967},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80f2be73a7dd4dc38d673fe725c6097b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1066},
            "size":{
              "width":358,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_1/u53_line.png"}},
{
          "id":"264a890ff32142e08d49b0afd2edac8c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":991.000061035156},
            "size":{
              "width":75,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5c95c9acbd405085c0227e78b6d790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":991.000061035156},
                "size":{
                  "width":75,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u79.jpg"}},
{
          "id":"b078f910d63a44358f61aec876a60665",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":93,
              "y":993.000061035156},
            "size":{
              "width":81,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f164cff79f704720a8d9a85764c01ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":93,
                  "y":993.000061035156},
                "size":{
                  "width":81,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"570e483b3fe7451a922c3cb8cdee8ee1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":93,
              "y":1028},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1b5c49581454e96b17dee89e9fab3ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":1028},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b891127882ee4f6fb517d778fb11d163",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":93,
              "y":1052},
            "size":{
              "width":69,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3920d132fc1d466eb5a32445a1a30cbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":93,
                  "y":1052},
                "size":{
                  "width":69,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc7c8a8b621046f4939d5ebf5793053c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":183,
              "y":1052},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a40bbb4768a749958b5000418b303104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":183,
                  "y":1052},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37fb7f2cd1d846ddab65d5158e1faabc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":730},
            "size":{
              "width":357,
              "height":85}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农场详情",
                      "target":{
                        "targetType":"page",
                        "url":"农场详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"05d6feb52a7f4ec39076a33c5b2579d1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":816},
            "size":{
              "width":357,
              "height":85}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农场详情",
                      "target":{
                        "targetType":"page",
                        "url":"农场详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b29104a1083c4ac7854edc88e499b496",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1090},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d80478fc95554678b69ac6c99200ca38",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c745f1d03d74457a96bc9f86b3f7ac26",
                  "label":"",
                  "parentDynamicPanel":"b29104a1083c4ac7854edc88e499b496",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "masterId":"9c8d789cd9ea4344a50ed483251cd481"}]}]}]}},
  "masters":{
    "9c8d789cd9ea4344a50ed483251cd481":{
      "packageId":"9c8d789cd9ea4344a50ed483251cd481",
      "type":"Axure:Master",
      "name":"底部菜单_1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"87500d8b8b844c309601540b4619d68c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":360,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08515cc118c040c3999f325ab93566f2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":360,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u47.png"}},
{
            "id":"c969752f566a49a6a203e49df35fab25",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":44,
                "y":3},
              "size":{
                "width":19,
                "height":20},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"325af96594fe47e187b0c48c8466ada8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":44,
                    "y":3},
                  "size":{
                    "width":19,
                    "height":20},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"506791ca29ed45d4a2ce7c6554b086f0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "location":{
                "x":44,
                "y":24},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2095c2f0c9424993952f697a18668ec6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "location":{
                    "x":44,
                    "y":24},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b01f71406add42228a7c6d6eee864c12",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":130,
                "y":3},
              "size":{
                "width":19,
                "height":20},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2a9a97f3cf084f5d8e9c58efa99246e4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":130,
                    "y":3},
                  "size":{
                    "width":19,
                    "height":20},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"3df70097703244faa1527a5a494c8c42",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "location":{
                "x":130,
                "y":24},
              "size":{
                "width":21,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f7f494690f7647dba3345b464317963a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "location":{
                    "x":130,
                    "y":24},
                  "size":{
                    "width":21,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7b6f02963717457387f89b9f67fcafd8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":211,
                "y":3},
              "size":{
                "width":19,
                "height":20},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3b49bb4a854648309a5eacee1c6f6550",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":211,
                    "y":3},
                  "size":{
                    "width":19,
                    "height":20},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"042cb23104d742f2ae2b63e077e1712d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "location":{
                "x":207,
                "y":24},
              "size":{
                "width":31,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a93b06fed9a846fcbebd845a157d74d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "location":{
                    "x":207,
                    "y":24},
                  "size":{
                    "width":31,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0a65b7584c6c43f187543b1bed0f9620",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":291,
                "y":3},
              "size":{
                "width":19,
                "height":20},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a061bd47263944abac34483694e25ef7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":291,
                    "y":3},
                  "size":{
                    "width":19,
                    "height":20},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u49.png"}},
{
            "id":"7059bc5e155a401bac0768cc3d613ce5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "location":{
                "x":281,
                "y":24},
              "size":{
                "width":41,
                "height":13}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c7a87c87752f49fba0d0cb8e99c88f4a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "location":{
                    "x":281,
                    "y":24},
                  "size":{
                    "width":41,
                    "height":13}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"947fc150c84545bc959a65c3c98bf4d6",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":110,
                "y":0},
              "size":{
                "width":70,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 商品列表",
                        "target":{
                          "targetType":"page",
                          "url":"商品列表_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"8ea57a5b3f8e48fb8d26368b9cd9484c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":17,
                "y":0},
              "size":{
                "width":83,
                "height":40}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "b8c4c5654f974ef5bc7555a3046f37ee":{
      "scriptId":"u0"},
    "2850fb3577304ca68e56896a96f93f40":{
      "scriptId":"u1"},
    "d2b3c61458df48c5b4c131279b824ec2":{
      "scriptId":"u2"},
    "5d9927ee8a0f449b8244ad55849989bb":{
      "scriptId":"u3"},
    "672f55c10b294dcf82b1194b3b723afe":{
      "scriptId":"u4"},
    "a4eb9e9190ca481383001aa19afe9b05":{
      "scriptId":"u5"},
    "0da3543ce74046aab9a2d000b8f23084":{
      "scriptId":"u6"},
    "53da616c6cc44215b9c336194f954009":{
      "scriptId":"u7"},
    "e0843e66d1bc43c091493b1e04be561a":{
      "scriptId":"u8"},
    "eccc8f5fb2f14d9989a612560193adc4":{
      "scriptId":"u9"},
    "67dc4ef902fb4724b0e975e1e1febf88":{
      "scriptId":"u10"},
    "975c2a995cb94ee4a917413b40a060bf":{
      "scriptId":"u11"},
    "f55b5bc27f844c2b9fdcbad3ec36e9ec":{
      "scriptId":"u12"},
    "047478fabd3749ad91ecd43682b13d5d":{
      "scriptId":"u13"},
    "14632c1c73fa4868b5b0a19e271cc649":{
      "scriptId":"u14"},
    "45d69b331b164235a7ed115beca34bad":{
      "scriptId":"u15"},
    "0aa58b74467244adbc685d2cd9a9db5e":{
      "scriptId":"u16"},
    "e93a2d2be29b47fd864c19f7747447f0":{
      "scriptId":"u17"},
    "af8edbde69db4991b0237f80c585f0f5":{
      "scriptId":"u18"},
    "98ab1120a9de47828834156d07f32bf9":{
      "scriptId":"u19"},
    "db9bf675f5bc40a485ba1e5d6f2fd1a0":{
      "scriptId":"u20"},
    "a5b79eff4035440c854456a9f9d8c3d3":{
      "scriptId":"u21"},
    "c3d0e3f702f54306a514aa74e49d2d51":{
      "scriptId":"u22"},
    "7e99253ba832434a8b87e188e3aabe19":{
      "scriptId":"u23"},
    "83e6c357319b4dc5925fb6ee52ed543b":{
      "scriptId":"u24"},
    "ac889aff8c8f4726b43f32983f54c63d":{
      "scriptId":"u25"},
    "82c11b5d44714faeb2a51aed88d50bfb":{
      "scriptId":"u26"},
    "670e839269f04303be670638232c6c25":{
      "scriptId":"u27"},
    "047a6801d8c848ed8753e810c42395ea":{
      "scriptId":"u28"},
    "e68effb9a31e4054bcaf40139613c61f":{
      "scriptId":"u29"},
    "9d077fc694554932a8f6dfbd4d14d384":{
      "scriptId":"u30"},
    "ba6e17919f3a47699a666a051e561cfc":{
      "scriptId":"u31"},
    "3dfccfd165e440508944d63134c59fe0":{
      "scriptId":"u32"},
    "6d07da754bc0499c8f2293e0aec6b796":{
      "scriptId":"u33"},
    "9131d49ebfa043e09d4aa316b9b2fb8d":{
      "scriptId":"u34"},
    "4c189cfcbc0249408f486f3a0da74a94":{
      "scriptId":"u35"},
    "ce385ef6206145269209c88fc644c58a":{
      "scriptId":"u36"},
    "2a1a0a2c1d644c6b8473f7c90d229765":{
      "scriptId":"u37"},
    "1891c4c2f2994f3987b81eab3f2c71c1":{
      "scriptId":"u38"},
    "e38a9debb8a2401994bc14711fe4d204":{
      "scriptId":"u39"},
    "0b7d19ba0bd04480a1e2c335a533c05b":{
      "scriptId":"u40"},
    "8ed177d1ff6045c0a584c5e4dc9056f8":{
      "scriptId":"u41"},
    "946525f0d9964780b93b712a408ce36b":{
      "scriptId":"u42"},
    "a95292abe8984b539739309463bf5061":{
      "scriptId":"u43"},
    "cf43815ddaea4291a418c9c6195a641a":{
      "scriptId":"u44"},
    "b03e1c322d114a41a5f2b00ca044ebd2":{
      "scriptId":"u45"},
    "75772e94bfa04c418232ed15901cfe97":{
      "scriptId":"u46"},
    "fc52e3fba047438a9c38fedff74a920f":{
      "scriptId":"u47"},
    "56769b25d8c045c99c8b995a36a26d93":{
      "scriptId":"u48"},
    "e9ceb532e1584b67a50fcedf8d0cd138":{
      "scriptId":"u49"},
    "a55f6bd018ce4164b43b9c25b05795ba":{
      "scriptId":"u50"},
    "d9930af1706644749fb0502e3efe4728":{
      "scriptId":"u51"},
    "bd4f70644ebe4c71a6de86df62862c68":{
      "scriptId":"u52"},
    "5cdf3158bec24eaa937a9814895371bf":{
      "scriptId":"u53"},
    "360c5b1ef13544859e8d4719c1894030":{
      "scriptId":"u54"},
    "0e5f697f178a48e393dec104e2f9a49f":{
      "scriptId":"u55"},
    "611f4bd42b52453d8cc3ff62a5c8c57f":{
      "scriptId":"u56"},
    "0713ee2a12c2453eb3d056e8b97ce039":{
      "scriptId":"u57"},
    "03d71402ad214325b211f2343eaa8c29":{
      "scriptId":"u58"},
    "dca972403f784963af10d6912d39b4d3":{
      "scriptId":"u59"},
    "22ae06a404ed4d68863f616c78dc345b":{
      "scriptId":"u60"},
    "3828f14f564047c5ba5ea0ab0f01e942":{
      "scriptId":"u61"},
    "97f5f4f95a1d423f9f1c7d7eef5d7b0e":{
      "scriptId":"u62"},
    "734225881f1e4f0fae7b35d2c8cb1a99":{
      "scriptId":"u63"},
    "9708ca65dd5c4572a5eff3fa932cdd5d":{
      "scriptId":"u64"},
    "9668cf361f9a41d1b05206d6c7c2ab91":{
      "scriptId":"u65"},
    "c1720a7e6c7e495db8045d7dfd677f62":{
      "scriptId":"u66"},
    "c83fbe3a8d8f4203987011645d68f4ed":{
      "scriptId":"u67"},
    "4da7efdef7dd4240a730f25273c645d8":{
      "scriptId":"u68"},
    "7d08bca4a8ac4df98eb2282129892b61":{
      "scriptId":"u69"},
    "dad485e70eb5446c859e399c0f0a8a08":{
      "scriptId":"u70"},
    "17a2a0a989244bf7801fc32062f933b2":{
      "scriptId":"u71"},
    "0ce69e5bcffb48a3ac4df2f986b84c33":{
      "scriptId":"u72"},
    "5c8a7c1a6a734c6583b494739956377f":{
      "scriptId":"u73"},
    "5af40f468d684c74b97a8315870f6db1":{
      "scriptId":"u74"},
    "cac11f16330342e6a9eb126c8de5cf3a":{
      "scriptId":"u75"},
    "371433e93f244b90936207cb85942e82":{
      "scriptId":"u76"},
    "a3b9b7a32c744704a0b379b15ee530a4":{
      "scriptId":"u77"},
    "7e1ae3bb6a264cddbd3226cb71212bdf":{
      "scriptId":"u78"},
    "43473d7ab0894c759ae33aa7b527f496":{
      "scriptId":"u79"},
    "d7587c1485364fefa539fdfb063b5b07":{
      "scriptId":"u80"},
    "9e096c6b84e64c0f9fe196e9ff2d8b0b":{
      "scriptId":"u81"},
    "586324804c844c69bea9333444008b09":{
      "scriptId":"u82"},
    "69d8131ce8b84778a80cff1f8cd3103f":{
      "scriptId":"u83"},
    "68d86c0a10da444f926bbc0b7b645f8e":{
      "scriptId":"u84"},
    "aa8fc95d68374adf989c8ab48e8aed29":{
      "scriptId":"u85"},
    "72995f80d24d4ee48edec291511198e5":{
      "scriptId":"u86"},
    "a9e42039be7143aa874df67773d06e69":{
      "scriptId":"u87"},
    "798fade9a9f449cdbc0316c90e00fec9":{
      "scriptId":"u88"},
    "80f2be73a7dd4dc38d673fe725c6097b":{
      "scriptId":"u89"},
    "264a890ff32142e08d49b0afd2edac8c":{
      "scriptId":"u90"},
    "bf5c95c9acbd405085c0227e78b6d790":{
      "scriptId":"u91"},
    "b078f910d63a44358f61aec876a60665":{
      "scriptId":"u92"},
    "f164cff79f704720a8d9a85764c01ef6":{
      "scriptId":"u93"},
    "570e483b3fe7451a922c3cb8cdee8ee1":{
      "scriptId":"u94"},
    "d1b5c49581454e96b17dee89e9fab3ca":{
      "scriptId":"u95"},
    "b891127882ee4f6fb517d778fb11d163":{
      "scriptId":"u96"},
    "3920d132fc1d466eb5a32445a1a30cbf":{
      "scriptId":"u97"},
    "bc7c8a8b621046f4939d5ebf5793053c":{
      "scriptId":"u98"},
    "a40bbb4768a749958b5000418b303104":{
      "scriptId":"u99"},
    "37fb7f2cd1d846ddab65d5158e1faabc":{
      "scriptId":"u100"},
    "05d6feb52a7f4ec39076a33c5b2579d1":{
      "scriptId":"u101"},
    "b29104a1083c4ac7854edc88e499b496":{
      "scriptId":"u102"},
    "c745f1d03d74457a96bc9f86b3f7ac26":{
      "scriptId":"u103",
      "87500d8b8b844c309601540b4619d68c":{
        "scriptId":"u104"},
      "08515cc118c040c3999f325ab93566f2":{
        "scriptId":"u105"},
      "c969752f566a49a6a203e49df35fab25":{
        "scriptId":"u106"},
      "325af96594fe47e187b0c48c8466ada8":{
        "scriptId":"u107"},
      "506791ca29ed45d4a2ce7c6554b086f0":{
        "scriptId":"u108"},
      "2095c2f0c9424993952f697a18668ec6":{
        "scriptId":"u109"},
      "b01f71406add42228a7c6d6eee864c12":{
        "scriptId":"u110"},
      "2a9a97f3cf084f5d8e9c58efa99246e4":{
        "scriptId":"u111"},
      "3df70097703244faa1527a5a494c8c42":{
        "scriptId":"u112"},
      "f7f494690f7647dba3345b464317963a":{
        "scriptId":"u113"},
      "7b6f02963717457387f89b9f67fcafd8":{
        "scriptId":"u114"},
      "3b49bb4a854648309a5eacee1c6f6550":{
        "scriptId":"u115"},
      "042cb23104d742f2ae2b63e077e1712d":{
        "scriptId":"u116"},
      "a93b06fed9a846fcbebd845a157d74d3":{
        "scriptId":"u117"},
      "0a65b7584c6c43f187543b1bed0f9620":{
        "scriptId":"u118"},
      "a061bd47263944abac34483694e25ef7":{
        "scriptId":"u119"},
      "7059bc5e155a401bac0768cc3d613ce5":{
        "scriptId":"u120"},
      "c7a87c87752f49fba0d0cb8e99c88f4a":{
        "scriptId":"u121"},
      "947fc150c84545bc959a65c3c98bf4d6":{
        "scriptId":"u122"},
      "8ea57a5b3f8e48fb8d26368b9cd9484c":{
        "scriptId":"u123"}}}});