$axure.loadCurrentPage({
  "url":"供应商系统主页.html",
  "generationDate":new Date(1502696122864.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"542c3e42e9e94fe191eeda19374bb149",
    "type":"Axure:Page",
    "name":"供应商系统主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"93fc559d8180414982faf72d42539023",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c246cf616b4d4e33ac6e673b32258833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u0.png"}},
{
          "id":"46e50f06f5344e7b80093a350119077a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":16},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2527c46fb38542349d5e7877fd495bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":16},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ed45a1656ec4de3a1421b948da964c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFA0D9F6},
            "location":{
              "x":9,
              "y":10},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b621f029b44d35b91eea35ead0731c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA0D9F6},
                "location":{
                  "x":9,
                  "y":10},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u4.png"}},
{
          "id":"7439a65c64f84e888b27b1aa39da533d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":13},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0488bb2863243c2959e16511635b7e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":13},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u60.png"}},
{
          "id":"1af5bd064b0740789ff4a52f4464186c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":79,
              "y":55},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd08fdaa9c645b4bc1409d378d8c804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":79,
                  "y":55},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e9a747d9b34f4d9c6f2e68d63452b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":109,
              "y":54},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347d0c6ec67b428888224c3cb7a263bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":54},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b22303821314436b4e9c31c82442e9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":80},
            "size":{
              "width":340,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"376fcd73b0014fe3a6107404aa3a42b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":80},
                "size":{
                  "width":340,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u12.png"}},
{
          "id":"3572e0908a454a3bad75aebef78d4f01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":80},
            "size":{
              "width":86,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb7555b0fce47fab001a949aad54a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":80},
                "size":{
                  "width":86,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u14.png"}},
{
          "id":"2fc6fe311eae4e0d9b98a4ce66284281",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6600,
              "opacity":1},
            "location":{
              "x":40,
              "y":96},
            "size":{
              "width":23,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb629ec4298b4ffcb2ff3c6c0523d0e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6600,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":96},
                "size":{
                  "width":23,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5df4e6f0960441c94b23b4442131d20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":29,
              "y":125},
            "size":{
              "width":46,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27362579c2e44907b0756e2532be9ed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":29,
                  "y":125},
                "size":{
                  "width":46,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4dd8e32d29c48b1819454f9c9f14ea0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":80},
            "size":{
              "width":86,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10faedf422c14e9d9046c7c652e4dbbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":80},
                "size":{
                  "width":86,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u14.png"}},
{
          "id":"74f61862c724402f8e19b19e47f4c1a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":125,
              "y":96},
            "size":{
              "width":23,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64993b85fd8a418595aa763f949cc339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":125,
                  "y":96},
                "size":{
                  "width":23,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aecd42c666df4a95a35fac2fc9aee783",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":114,
              "y":125},
            "size":{
              "width":46,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f886224a08304a6d8eb37dc2d703d18f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":114,
                  "y":125},
                "size":{
                  "width":46,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0759f0ee09548cb87b9451b1a12b794",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":80},
            "size":{
              "width":86,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb011783e64448f09fa1d06b9b7706c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":80},
                "size":{
                  "width":86,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u14.png"}},
{
          "id":"166983afc8274919ba503e59d3f2f7c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":216,
              "y":96},
            "size":{
              "width":12,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf3139663bf4f3eb548a5a6f5d36422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":216,
                  "y":96},
                "size":{
                  "width":12,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58c2d67f4e42417fa5e9c269f25fb4dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":199,
              "y":125},
            "size":{
              "width":46,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00a85f8417dd4d648bc72818b4dc8ff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":199,
                  "y":125},
                "size":{
                  "width":46,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"045a37b75fd949368550efc52724068e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":80},
            "size":{
              "width":86,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c76d2a40d94d08a8f37044f22b86d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":80},
                "size":{
                  "width":86,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u14.png"}},
{
          "id":"876c1d57bb49469bb4c28fb77657fb32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":283,
              "y":125},
            "size":{
              "width":46,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"755dddde209f4615b9bc334a0ec77037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":125},
                "size":{
                  "width":46,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4eafd633b544b528d7d2773689e04cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295.5,
              "y":97.5},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5bfbd87bbe241248791bc783df020b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295.5,
                  "y":97.5},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u36.png"}},
{
          "id":"c5e50a342ca942d59e552f756950c17f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":9,
              "y":170},
            "size":{
              "width":340,
              "height":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d629b8a129b449149473e9b0dceb03d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":9,
                  "y":170},
                "size":{
                  "width":340,
                  "height":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u38.png"}},
{
          "id":"1926199d9a71469dac42d91bd6a69093",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":220},
            "size":{
              "width":340,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e1331637d314515a46105032cb4091a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":220},
                "size":{
                  "width":340,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u40.png"}},
{
          "id":"025b1b2a344b4b3eba5651511e90c2fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":9,
              "y":170},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77fb227b7aba4b74aeed69faf7b541c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":9,
                  "y":170},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80b7af68ec3442be9d9e7c52a8b9ae70",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":126,
              "y":170},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d3183d51aa4819bc5271ef211e853d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":126,
                  "y":170},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e145f9e3d464aaa8d81775bf202808e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":239,
              "y":170},
            "size":{
              "width":110,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd26968fd0114f279be8d989d63ee8a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":239,
                  "y":170},
                "size":{
                  "width":110,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28c0624224034312bbe8a6e912511dac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":232.5},
            "size":{
              "width":25,
              "height":25},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38e109f8c47046c9aa7ac50acb0acc06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":232.5},
                "size":{
                  "width":25,
                  "height":25},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u48.png"}},
{
          "id":"7809ea9c5e0e402bb97c3b5649fafa22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":232.5},
            "size":{
              "width":25,
              "height":25},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5123f632f05c4036a469c60bdf9fe65f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":232.5},
                "size":{
                  "width":25,
                  "height":25},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u48.png"}},
{
          "id":"f61f0098c33f462f9107e29ad855a16c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":123,
              "y":236},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73380c20f1f945378e385c5e51191fd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":236},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da2eeb74036e46808438b5a37e87f9f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":212},
            "size":{
              "width":15,
              "height":15},
            "rotation":"45",
            "textRotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bffbb3d253ed4961af5034abf5e809a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":57,
                  "y":212},
                "size":{
                  "width":15,
                  "height":15},
                "rotation":"45",
                "textRotation":"45",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u54.png"}},
{
          "id":"ec3faf259d86436a9bf2f8826f3debb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":280},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"249d72ef8e1441d7bbc537e83b8ef47e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":280},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c438aae328ae4489af304b04999e08d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":304},
            "size":{
              "width":171,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d975e5436fda4597ba2604c1e6816b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":304},
                "size":{
                  "width":171,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4126e1cb6b0462097fcc2bc344ba63c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":362},
            "size":{
              "width":89,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9cfc6a828b740d8bb641b8df551b2b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":362},
                "size":{
                  "width":89,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eabced50eab346cfa214e6fb4d51744c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":386},
            "size":{
              "width":131,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc5953425a224d16a6721ef5d3792f7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":386},
                "size":{
                  "width":131,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb24bfb47d0d4c3cb181e00833475604",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":438},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48b6d96bb1e4b1abb16b3bb026bd11e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":438},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fd42be8100b4a81acf87f6e37db2bd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":462},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2def67af964b4db192ae0458594b9f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":462},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3f7d6831e03411a9d5b4b06af50ff79",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20.5,
              "y":346},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商系统主页/u68_line.png"}},
{
          "id":"472d6cc4823547179ab4485b4198423c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":504},
            "size":{
              "width":317,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商系统主页/u68_line.png"}},
{
          "id":"4ac1f20193cb478482b9a60cf9e5b1c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":525},
            "size":{
              "width":89,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c85494051fb14f1a9cc64a0480f624f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":525},
                "size":{
                  "width":89,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f9c61dc9adc48a687f66b4d30f595f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":549},
            "size":{
              "width":171,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9db85610230482abe3f8aa0aeeae666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":549},
                "size":{
                  "width":171,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee425b74ebee47dc96d026e4c90406ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":601},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23ca0896408447bb665ba5985e7d552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":601},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24f93538c0754ed99c08a054bc703c27",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":36,
              "y":625},
            "size":{
              "width":41,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe475ea3a9643e3ad5cba603ba42a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":625},
                "size":{
                  "width":41,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b29073055b334555a73cdeab2b7843ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":9,
              "y":720},
            "size":{
              "width":340,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a983856b52124d81827fe5d752735a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":9,
                  "y":720},
                "size":{
                  "width":340,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心主页",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心主页_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/供应商系统主页/u78.png"}},
{
          "id":"af60d4f55e2a43deb2e7b92c5dd10e48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":312,
              "y":10},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aeb4f5689b9445bba4f0e23fee3269f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":312,
                  "y":10},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商系统主页/u80.png"}},
{
          "id":"dfd382daf88a44d6a124ad51e511062e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":80},
            "size":{
              "width":86,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 待发货",
                      "target":{
                        "targetType":"page",
                        "url":"待发货.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c62ba7cba111435597e42e6b6763ed7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":305,
              "y":280},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbae8e1c3a0d4553ab6e6c1e7bbc867d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":305,
                  "y":280},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1060988b25224d93a04793bae1f4c6a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":305,
              "y":362},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e16d9f52fcf48ed8223bef6c88df41f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":305,
                  "y":362},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f4f7601944e47a5a4f7249ffa112274",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":305,
              "y":525},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"accb8a2c608347b99f48deb095e75cb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":305,
                  "y":525},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "93fc559d8180414982faf72d42539023":{
      "scriptId":"u0"},
    "c246cf616b4d4e33ac6e673b32258833":{
      "scriptId":"u1"},
    "46e50f06f5344e7b80093a350119077a":{
      "scriptId":"u2"},
    "2527c46fb38542349d5e7877fd495bdf":{
      "scriptId":"u3"},
    "0ed45a1656ec4de3a1421b948da964c9":{
      "scriptId":"u4"},
    "f5b621f029b44d35b91eea35ead0731c":{
      "scriptId":"u5"},
    "7439a65c64f84e888b27b1aa39da533d":{
      "scriptId":"u6"},
    "c0488bb2863243c2959e16511635b7e8":{
      "scriptId":"u7"},
    "1af5bd064b0740789ff4a52f4464186c":{
      "scriptId":"u8"},
    "cbd08fdaa9c645b4bc1409d378d8c804":{
      "scriptId":"u9"},
    "06e9a747d9b34f4d9c6f2e68d63452b1":{
      "scriptId":"u10"},
    "347d0c6ec67b428888224c3cb7a263bd":{
      "scriptId":"u11"},
    "0b22303821314436b4e9c31c82442e9c":{
      "scriptId":"u12"},
    "376fcd73b0014fe3a6107404aa3a42b2":{
      "scriptId":"u13"},
    "3572e0908a454a3bad75aebef78d4f01":{
      "scriptId":"u14"},
    "9eb7555b0fce47fab001a949aad54a34":{
      "scriptId":"u15"},
    "2fc6fe311eae4e0d9b98a4ce66284281":{
      "scriptId":"u16"},
    "eb629ec4298b4ffcb2ff3c6c0523d0e0":{
      "scriptId":"u17"},
    "e5df4e6f0960441c94b23b4442131d20":{
      "scriptId":"u18"},
    "27362579c2e44907b0756e2532be9ed7":{
      "scriptId":"u19"},
    "c4dd8e32d29c48b1819454f9c9f14ea0":{
      "scriptId":"u20"},
    "10faedf422c14e9d9046c7c652e4dbbd":{
      "scriptId":"u21"},
    "74f61862c724402f8e19b19e47f4c1a5":{
      "scriptId":"u22"},
    "64993b85fd8a418595aa763f949cc339":{
      "scriptId":"u23"},
    "aecd42c666df4a95a35fac2fc9aee783":{
      "scriptId":"u24"},
    "f886224a08304a6d8eb37dc2d703d18f":{
      "scriptId":"u25"},
    "d0759f0ee09548cb87b9451b1a12b794":{
      "scriptId":"u26"},
    "bb011783e64448f09fa1d06b9b7706c2":{
      "scriptId":"u27"},
    "166983afc8274919ba503e59d3f2f7c6":{
      "scriptId":"u28"},
    "7cf3139663bf4f3eb548a5a6f5d36422":{
      "scriptId":"u29"},
    "58c2d67f4e42417fa5e9c269f25fb4dd":{
      "scriptId":"u30"},
    "00a85f8417dd4d648bc72818b4dc8ff3":{
      "scriptId":"u31"},
    "045a37b75fd949368550efc52724068e":{
      "scriptId":"u32"},
    "04c76d2a40d94d08a8f37044f22b86d6":{
      "scriptId":"u33"},
    "876c1d57bb49469bb4c28fb77657fb32":{
      "scriptId":"u34"},
    "755dddde209f4615b9bc334a0ec77037":{
      "scriptId":"u35"},
    "b4eafd633b544b528d7d2773689e04cb":{
      "scriptId":"u36"},
    "d5bfbd87bbe241248791bc783df020b4":{
      "scriptId":"u37"},
    "c5e50a342ca942d59e552f756950c17f":{
      "scriptId":"u38"},
    "d629b8a129b449149473e9b0dceb03d0":{
      "scriptId":"u39"},
    "1926199d9a71469dac42d91bd6a69093":{
      "scriptId":"u40"},
    "9e1331637d314515a46105032cb4091a":{
      "scriptId":"u41"},
    "025b1b2a344b4b3eba5651511e90c2fe":{
      "scriptId":"u42"},
    "77fb227b7aba4b74aeed69faf7b541c3":{
      "scriptId":"u43"},
    "80b7af68ec3442be9d9e7c52a8b9ae70":{
      "scriptId":"u44"},
    "a4d3183d51aa4819bc5271ef211e853d":{
      "scriptId":"u45"},
    "6e145f9e3d464aaa8d81775bf202808e":{
      "scriptId":"u46"},
    "fd26968fd0114f279be8d989d63ee8a2":{
      "scriptId":"u47"},
    "28c0624224034312bbe8a6e912511dac":{
      "scriptId":"u48"},
    "38e109f8c47046c9aa7ac50acb0acc06":{
      "scriptId":"u49"},
    "7809ea9c5e0e402bb97c3b5649fafa22":{
      "scriptId":"u50"},
    "5123f632f05c4036a469c60bdf9fe65f":{
      "scriptId":"u51"},
    "f61f0098c33f462f9107e29ad855a16c":{
      "scriptId":"u52"},
    "73380c20f1f945378e385c5e51191fd1":{
      "scriptId":"u53"},
    "da2eeb74036e46808438b5a37e87f9f2":{
      "scriptId":"u54"},
    "bffbb3d253ed4961af5034abf5e809a8":{
      "scriptId":"u55"},
    "ec3faf259d86436a9bf2f8826f3debb8":{
      "scriptId":"u56"},
    "249d72ef8e1441d7bbc537e83b8ef47e":{
      "scriptId":"u57"},
    "c438aae328ae4489af304b04999e08d7":{
      "scriptId":"u58"},
    "d975e5436fda4597ba2604c1e6816b22":{
      "scriptId":"u59"},
    "e4126e1cb6b0462097fcc2bc344ba63c":{
      "scriptId":"u60"},
    "e9cfc6a828b740d8bb641b8df551b2b0":{
      "scriptId":"u61"},
    "eabced50eab346cfa214e6fb4d51744c":{
      "scriptId":"u62"},
    "dc5953425a224d16a6721ef5d3792f7e":{
      "scriptId":"u63"},
    "fb24bfb47d0d4c3cb181e00833475604":{
      "scriptId":"u64"},
    "c48b6d96bb1e4b1abb16b3bb026bd11e":{
      "scriptId":"u65"},
    "3fd42be8100b4a81acf87f6e37db2bd8":{
      "scriptId":"u66"},
    "2def67af964b4db192ae0458594b9f94":{
      "scriptId":"u67"},
    "a3f7d6831e03411a9d5b4b06af50ff79":{
      "scriptId":"u68"},
    "472d6cc4823547179ab4485b4198423c":{
      "scriptId":"u69"},
    "4ac1f20193cb478482b9a60cf9e5b1c6":{
      "scriptId":"u70"},
    "c85494051fb14f1a9cc64a0480f624f7":{
      "scriptId":"u71"},
    "3f9c61dc9adc48a687f66b4d30f595f7":{
      "scriptId":"u72"},
    "e9db85610230482abe3f8aa0aeeae666":{
      "scriptId":"u73"},
    "ee425b74ebee47dc96d026e4c90406ca":{
      "scriptId":"u74"},
    "e23ca0896408447bb665ba5985e7d552":{
      "scriptId":"u75"},
    "24f93538c0754ed99c08a054bc703c27":{
      "scriptId":"u76"},
    "afe475ea3a9643e3ad5cba603ba42a30":{
      "scriptId":"u77"},
    "b29073055b334555a73cdeab2b7843ad":{
      "scriptId":"u78"},
    "a983856b52124d81827fe5d752735a5f":{
      "scriptId":"u79"},
    "af60d4f55e2a43deb2e7b92c5dd10e48":{
      "scriptId":"u80"},
    "0aeb4f5689b9445bba4f0e23fee3269f":{
      "scriptId":"u81"},
    "dfd382daf88a44d6a124ad51e511062e":{
      "scriptId":"u82"},
    "c62ba7cba111435597e42e6b6763ed7a":{
      "scriptId":"u83"},
    "fbae8e1c3a0d4553ab6e6c1e7bbc867d":{
      "scriptId":"u84"},
    "1060988b25224d93a04793bae1f4c6a2":{
      "scriptId":"u85"},
    "7e16d9f52fcf48ed8223bef6c88df41f":{
      "scriptId":"u86"},
    "2f4f7601944e47a5a4f7249ffa112274":{
      "scriptId":"u87"},
    "accb8a2c608347b99f48deb095e75cb7":{
      "scriptId":"u88"}}});