$axure.loadCurrentPage({
  "url":"11_1_绑定使用者.html",
  "generationDate":new Date(1520912123366.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"a5d50a1a5bc74d0dad960c5d7901e384",
    "type":"Axure:Page",
    "name":"11.1 绑定使用者",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bccffef991834e93863730f31b3f4942",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0dd9d123a24977bed8e4f66c3c5cc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_2订单支付页/u0.png"}},
{
          "id":"48fe5a42a5064d47953523004a7c1d58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6074ed00685f4927a99c12674b8ed117",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页/u2.png"}},
{
          "id":"41bbfe77a00748f6bcb211fb31152ad4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a89f7cb77f0048fabddcef5e0a609ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"a708b10ba3da473982e085bb329c5557",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":134,
              "y":9},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b44ab0fafd749f9b761122f7078fe64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":134,
                  "y":9},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a10ea48d4c33442c830c926e588e107c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":34,
              "y":402},
            "size":{
              "width":292,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"379c649c6312451794b48513c321db2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":34,
                  "y":402},
                "size":{
                  "width":292,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc5862e2005a45df8d63f668d5abb0de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7628d266a6341d18261d2ca93509a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"8dddf97472d3467a9e453d311c0318e3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":238},
            "size":{
              "width":270,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2b4288619f8943ad8770608665d3f65d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":244},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00bf940e8ae4f4aa2d6a18315762132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":244},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3ece3bd5dba4962b0f4381b2d811882",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":140,
              "y":352},
            "size":{
              "width":200,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4edca3411d743d58b33820cd4c63469",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":140,
                  "y":352},
                "size":{
                  "width":200,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 1.6提交成功（农旅生活卡）",
                      "target":{
                        "targetType":"page",
                        "url":"1_6提交成功（农旅生活卡）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/11_1_绑定使用者/u15.png"}},
{
          "id":"c27130ecd7be4103bc09927259302bd9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "verticalAlignment":"middle",
            "location":{
              "x":56,
              "y":318},
            "size":{
              "width":228,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db51bb4f363543c78a059acc9b9fc32b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "verticalAlignment":"middle",
                "location":{
                  "x":56,
                  "y":318},
                "size":{
                  "width":228,
                  "height":14}},
              "adaptiveStyles":{
}}]},
{
          "id":"5daae2667fb3494f8d7ad010fac811c0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":313},
            "size":{
              "width":129,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 1.8服务条款",
                      "target":{
                        "targetType":"page",
                        "url":"1_8服务条款.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6b493abe3a7b4dd8a788b784e40f5e18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":360,
              "height":190},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0410b6a94c2b42519eb192d30fa1f261",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":360,
                  "height":190},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_1_绑定使用者/u20.png"}},
{
          "id":"50b7ccccca5f407a8a94e79cc8d052fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":122},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bf7b098e8be4937bd249469ddca93d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":122},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48d0c12c93d241e8864580f64a25cdc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":65},
            "size":{
              "width":114,
              "height":130},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40456904419046f78ed3f2c93341800d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":65},
                "size":{
                  "width":114,
                  "height":130},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_1_绑定使用者/u24.png"}},
{
          "id":"c3eccbb3e481433f852fe2cde815a423",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":98},
            "size":{
              "width":64,
              "height":64},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e49a022be45b4e6892bd767f27281aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":98},
                "size":{
                  "width":64,
                  "height":64},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_1_绑定使用者/u26.png"}},
{
          "id":"b9155addd4d8479092d24adcc7b4ff6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab25f74219e64794bf8802e0efa42a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"a963ac5a86a042bda9965492b2a41a17",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":278},
            "size":{
              "width":270,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"95da4b4aa9e54413b0b27c268f4eccb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":284},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"892f8dbcc0af451ca751f2d1ac4c41b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":284},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"952e3d4a3f8e4793824e9eb32480e41a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":88,
              "y":204},
            "size":{
              "width":236,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff1dc4970c424d148d8c8268b4399b25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":204},
                "size":{
                  "width":236,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02e43b2ed7ff40af9ebc78a86e49b5b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":34,
              "y":352},
            "size":{
              "width":96,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6221ab4a5e28407b87de0fff110d9fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":34,
                  "y":352},
                "size":{
                  "width":96,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 1.6提交成功（农旅生活卡）",
                      "target":{
                        "targetType":"page",
                        "url":"1_6提交成功（农旅生活卡）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/11_1_绑定使用者/u35.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bccffef991834e93863730f31b3f4942":{
      "scriptId":"u0"},
    "9c0dd9d123a24977bed8e4f66c3c5cc0":{
      "scriptId":"u1"},
    "48fe5a42a5064d47953523004a7c1d58":{
      "scriptId":"u2"},
    "6074ed00685f4927a99c12674b8ed117":{
      "scriptId":"u3"},
    "41bbfe77a00748f6bcb211fb31152ad4":{
      "scriptId":"u4"},
    "a89f7cb77f0048fabddcef5e0a609ec1":{
      "scriptId":"u5"},
    "a708b10ba3da473982e085bb329c5557":{
      "scriptId":"u6"},
    "0b44ab0fafd749f9b761122f7078fe64":{
      "scriptId":"u7"},
    "a10ea48d4c33442c830c926e588e107c":{
      "scriptId":"u8"},
    "379c649c6312451794b48513c321db2c":{
      "scriptId":"u9"},
    "dc5862e2005a45df8d63f668d5abb0de":{
      "scriptId":"u10"},
    "f7628d266a6341d18261d2ca93509a66":{
      "scriptId":"u11"},
    "8dddf97472d3467a9e453d311c0318e3":{
      "scriptId":"u12"},
    "2b4288619f8943ad8770608665d3f65d":{
      "scriptId":"u13"},
    "a00bf940e8ae4f4aa2d6a18315762132":{
      "scriptId":"u14"},
    "d3ece3bd5dba4962b0f4381b2d811882":{
      "scriptId":"u15"},
    "f4edca3411d743d58b33820cd4c63469":{
      "scriptId":"u16"},
    "c27130ecd7be4103bc09927259302bd9":{
      "scriptId":"u17"},
    "db51bb4f363543c78a059acc9b9fc32b":{
      "scriptId":"u18"},
    "5daae2667fb3494f8d7ad010fac811c0":{
      "scriptId":"u19"},
    "6b493abe3a7b4dd8a788b784e40f5e18":{
      "scriptId":"u20"},
    "0410b6a94c2b42519eb192d30fa1f261":{
      "scriptId":"u21"},
    "50b7ccccca5f407a8a94e79cc8d052fd":{
      "scriptId":"u22"},
    "2bf7b098e8be4937bd249469ddca93d4":{
      "scriptId":"u23"},
    "48d0c12c93d241e8864580f64a25cdc7":{
      "scriptId":"u24"},
    "40456904419046f78ed3f2c93341800d":{
      "scriptId":"u25"},
    "c3eccbb3e481433f852fe2cde815a423":{
      "scriptId":"u26"},
    "e49a022be45b4e6892bd767f27281aa7":{
      "scriptId":"u27"},
    "b9155addd4d8479092d24adcc7b4ff6b":{
      "scriptId":"u28"},
    "ab25f74219e64794bf8802e0efa42a0f":{
      "scriptId":"u29"},
    "a963ac5a86a042bda9965492b2a41a17":{
      "scriptId":"u30"},
    "95da4b4aa9e54413b0b27c268f4eccb4":{
      "scriptId":"u31"},
    "892f8dbcc0af451ca751f2d1ac4c41b4":{
      "scriptId":"u32"},
    "952e3d4a3f8e4793824e9eb32480e41a":{
      "scriptId":"u33"},
    "ff1dc4970c424d148d8c8268b4399b25":{
      "scriptId":"u34"},
    "02e43b2ed7ff40af9ebc78a86e49b5b0":{
      "scriptId":"u35"},
    "6221ab4a5e28407b87de0fff110d9fba":{
      "scriptId":"u36"}}});