$axure.loadCurrentPage({
  "url":"优游农旅卡.html",
  "generationDate":new Date(1509693752080.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc"],
  "page":{
    "packageId":"fcebf8be3960486d818b5e783f1cb07a",
    "type":"Axure:Page",
    "name":"优游农旅卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e3a50ea4e1e4a64b6c677209d3d1410",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1340,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f235956f39a54e42b7bfc5e943577d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1340,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"720cd1ce1e784cd78ed280dec56c761f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":15},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6ac2ff7b69a4684a2689814175fd478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":15},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"c3e2faa4b19d42428ac16d4e44d0c77e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":10},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f367789b2b4ec39a5c161c1ca86709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":10},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"e153b2fe7eb94a9480517081e67291d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1116,
              "y":58},
            "size":{
              "width":89,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c28751ac1a4a7fa90434b7bb5a9d62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1116,
                  "y":58},
                "size":{
                  "width":89,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda78b89013547f9bb20173d0e2fba10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":555,
              "y":37},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"428319c60fd24a90a09c60f9124dc2ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":555,
                  "y":37},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acadeb03849441b58eeaf75bf33a4304",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":650,
              "y":37},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e0a43ddc8f344939e3a9e769f4fc073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":650,
                  "y":37},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优游农旅卡",
                      "target":{
                        "targetType":"page",
                        "url":"优游农旅卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d6364e7a9db45e9ad2773fd4ce295e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":811,
              "y":37},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"291425b86e13456cb67ddb0ee6269e9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":811,
                  "y":37},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农旅结合",
                      "target":{
                        "targetType":"page",
                        "url":"农旅结合.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e99a26ed76b446e8b59dc51268565180",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":950,
              "y":37},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d89dc57e0823468d91975395e39e49d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":950,
                  "y":37},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于我们",
                      "target":{
                        "targetType":"page",
                        "url":"关于我们.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c935895580648ffa11dbbc9bfc5c1d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1340,
              "height":488}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63d50f045ec44e4a903888a107d13852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":1340,
                  "height":488}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u17.jpg"}},
{
          "id":"0fbb24bdcf0c406ba4f56c30952e681d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":568},
            "size":{
              "width":1100,
              "height":529}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41af6af7512a4622b6886b636c67a52c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":568},
                "size":{
                  "width":1100,
                  "height":529}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优游农旅卡/u18.png"}},
{
          "id":"146b7b53925340658153ae3dd17cafd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":1080},
            "size":{
              "width":1100,
              "height":531}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"887afe4e186248cd92ac757a98f64c69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":1080},
                "size":{
                  "width":1100,
                  "height":531}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优游农旅卡/u20.png"}},
{
          "id":"77402448c0a24239ba017cfe954d9a20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":388.5,
              "y":1621},
            "size":{
              "width":563,
              "height":544}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc73550e34ec4038809e6f268235b33a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388.5,
                  "y":1621},
                "size":{
                  "width":563,
                  "height":544}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/优游农旅卡/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1e3a50ea4e1e4a64b6c677209d3d1410":{
      "scriptId":"u0"},
    "f235956f39a54e42b7bfc5e943577d03":{
      "scriptId":"u1"},
    "720cd1ce1e784cd78ed280dec56c761f":{
      "scriptId":"u2"},
    "b6ac2ff7b69a4684a2689814175fd478":{
      "scriptId":"u3"},
    "c3e2faa4b19d42428ac16d4e44d0c77e":{
      "scriptId":"u4"},
    "e4f367789b2b4ec39a5c161c1ca86709":{
      "scriptId":"u5"},
    "e153b2fe7eb94a9480517081e67291d1":{
      "scriptId":"u6"},
    "29c28751ac1a4a7fa90434b7bb5a9d62":{
      "scriptId":"u7"},
    "dda78b89013547f9bb20173d0e2fba10":{
      "scriptId":"u8"},
    "428319c60fd24a90a09c60f9124dc2ec":{
      "scriptId":"u9"},
    "acadeb03849441b58eeaf75bf33a4304":{
      "scriptId":"u10"},
    "7e0a43ddc8f344939e3a9e769f4fc073":{
      "scriptId":"u11"},
    "4d6364e7a9db45e9ad2773fd4ce295e1":{
      "scriptId":"u12"},
    "291425b86e13456cb67ddb0ee6269e9c":{
      "scriptId":"u13"},
    "e99a26ed76b446e8b59dc51268565180":{
      "scriptId":"u14"},
    "d89dc57e0823468d91975395e39e49d6":{
      "scriptId":"u15"},
    "8c935895580648ffa11dbbc9bfc5c1d9":{
      "scriptId":"u16"},
    "63d50f045ec44e4a903888a107d13852":{
      "scriptId":"u17"},
    "0fbb24bdcf0c406ba4f56c30952e681d":{
      "scriptId":"u18"},
    "41af6af7512a4622b6886b636c67a52c":{
      "scriptId":"u19"},
    "146b7b53925340658153ae3dd17cafd4":{
      "scriptId":"u20"},
    "887afe4e186248cd92ac757a98f64c69":{
      "scriptId":"u21"},
    "77402448c0a24239ba017cfe954d9a20":{
      "scriptId":"u22"},
    "bc73550e34ec4038809e6f268235b33a":{
      "scriptId":"u23"}}});