$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1509696517036.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc"],
  "page":{
    "packageId":"1bdf0002fa324a0d9a16bbdc8fc75b7a",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a339ce234a64ccdab0e8a31d89430e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1340,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49ab4ac3238945a4a8366ea5e9f34cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1340,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"99af0e62efd644fba0dbb67dd01d9cb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":15},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040b4406ee404bac86bf9077d6e89a4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":15},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"e3bc1b9280ef4fc88ae76368d28cb386",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1140,
              "y":10},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30280d9c4c6b43fbbd28610fed012acb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1140,
                  "y":10},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"d9be3ced94384fb78f391690d5b0e12d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1116,
              "y":58},
            "size":{
              "width":89,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"980465d04394430aa34a39065afe028d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1116,
                  "y":58},
                "size":{
                  "width":89,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8992099588174d21a22f2eac1f4b10eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":555,
              "y":37},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41de59cf4bee4eae802b737f81939db9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":37},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ae0bf1197fc4587a1e67e0fbda65b6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":650,
              "y":37},
            "size":{
              "width":101,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"682c6c9fea514d86bdd6e058c485501d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":650,
                  "y":37},
                "size":{
                  "width":101,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优游农旅卡",
                      "target":{
                        "targetType":"page",
                        "url":"优游农旅卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1f9f323fd00440498ee4a1b37884611",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":811,
              "y":37},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71eeb6f1e287497dacc0bebedec5e719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":811,
                  "y":37},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农旅结合",
                      "target":{
                        "targetType":"page",
                        "url":"农旅结合.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f5e0ddef2ae480dad09615e79dbddfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":950,
              "y":37},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83856d96d4804d01a6025dfff491280d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":950,
                  "y":37},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于我们",
                      "target":{
                        "targetType":"page",
                        "url":"关于我们.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
          "label":"幻灯片",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":80},
            "size":{
              "width":1340,
              "height":488}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待4000毫秒",
                      "waitTime":4000},
{
                      "action":"setPanelState",
                      "description":"设置 幻灯片 to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["e5d8b458f7ae4d1f84dc2dbe252cf1be"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待4000毫秒",
                      "waitTime":4000},
{
                      "action":"setPanelState",
                      "description":"设置 幻灯片 to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["e5d8b458f7ae4d1f84dc2dbe252cf1be"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"cb820b7e21e3401698f2d234fa00df6e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"52963dd95e9c4533b8035ccca84643d5",
                  "label":"",
                  "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1340,
                      "height":488}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ade7cfac15fb4ec2a73ec78594d0d901",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1340,
                          "height":488}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u17.jpg"}}]},
{
              "id":"cb3cd01aef4b4106b16e44184ff58768",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b69be16d39f247f081775954f8a6d5d6",
                  "label":"",
                  "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1340,
                      "height":488}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a0abdc44fbc49f6958fc2292a36c529",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1340,
                          "height":488}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u17.jpg"}}]},
{
              "id":"1417405a5e6d412192b74bf9d61f2b2d",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"646fcaea737448d4bcaffe78b713eb34",
                  "label":"",
                  "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1340,
                      "height":488}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5f52fbc1d1e48e2ad4f0f30dbf06735",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1340,
                          "height":488}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u17.jpg"}}]},
{
              "id":"743ff0f109844c16b78feb6ae2038753",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7fc224232e8c406caecf5e0b81597b3f",
                  "label":"",
                  "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1340,
                      "height":488}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77af396a981a434d9149d56df93f1d61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5d8b458f7ae4d1f84dc2dbe252cf1be",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1340,
                          "height":488}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u17.jpg"}}]}]},
{
          "id":"06b35c899d7c4723bc1e7ee09db97a38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF33CC66},
            "location":{
              "x":0,
              "y":2890},
            "size":{
              "width":1340,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abe71fa7d9f94a22bb4be4dbaa209362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33CC66},
                "location":{
                  "x":0,
                  "y":2890},
                "size":{
                  "width":1340,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a339ce234a64ccdab0e8a31d89430e6":{
      "scriptId":"u0"},
    "49ab4ac3238945a4a8366ea5e9f34cd9":{
      "scriptId":"u1"},
    "99af0e62efd644fba0dbb67dd01d9cb4":{
      "scriptId":"u2"},
    "040b4406ee404bac86bf9077d6e89a4d":{
      "scriptId":"u3"},
    "e3bc1b9280ef4fc88ae76368d28cb386":{
      "scriptId":"u4"},
    "30280d9c4c6b43fbbd28610fed012acb":{
      "scriptId":"u5"},
    "d9be3ced94384fb78f391690d5b0e12d":{
      "scriptId":"u6"},
    "980465d04394430aa34a39065afe028d":{
      "scriptId":"u7"},
    "8992099588174d21a22f2eac1f4b10eb":{
      "scriptId":"u8"},
    "41de59cf4bee4eae802b737f81939db9":{
      "scriptId":"u9"},
    "7ae0bf1197fc4587a1e67e0fbda65b6b":{
      "scriptId":"u10"},
    "682c6c9fea514d86bdd6e058c485501d":{
      "scriptId":"u11"},
    "f1f9f323fd00440498ee4a1b37884611":{
      "scriptId":"u12"},
    "71eeb6f1e287497dacc0bebedec5e719":{
      "scriptId":"u13"},
    "5f5e0ddef2ae480dad09615e79dbddfb":{
      "scriptId":"u14"},
    "83856d96d4804d01a6025dfff491280d":{
      "scriptId":"u15"},
    "e5d8b458f7ae4d1f84dc2dbe252cf1be":{
      "scriptId":"u16"},
    "52963dd95e9c4533b8035ccca84643d5":{
      "scriptId":"u17"},
    "ade7cfac15fb4ec2a73ec78594d0d901":{
      "scriptId":"u18"},
    "b69be16d39f247f081775954f8a6d5d6":{
      "scriptId":"u19"},
    "2a0abdc44fbc49f6958fc2292a36c529":{
      "scriptId":"u20"},
    "646fcaea737448d4bcaffe78b713eb34":{
      "scriptId":"u21"},
    "f5f52fbc1d1e48e2ad4f0f30dbf06735":{
      "scriptId":"u22"},
    "7fc224232e8c406caecf5e0b81597b3f":{
      "scriptId":"u23"},
    "77af396a981a434d9149d56df93f1d61":{
      "scriptId":"u24"},
    "06b35c899d7c4723bc1e7ee09db97a38":{
      "scriptId":"u25"},
    "abe71fa7d9f94a22bb4be4dbaa209362":{
      "scriptId":"u26"}}});