$axure.loadCurrentPage({
  "url":"组合套餐（初始）.html",
  "generationDate":new Date(1502704913948.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c5a35dd6a77430ba7682984107e0655",
    "type":"Axure:Page",
    "name":"组合套餐（初始）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c75042ad61c946928365380a36a5bee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":700},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"908d378ce87346f8821eb7905aa260fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":700},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组合套餐（初始）/u0.png"}},
{
          "id":"56b62402d67a4b8ca091769a32c03b45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3ebaeecddb74632bef83e093c660714",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/top_u2.png"}},
{
          "id":"b5acee2ecc514d63999a9a220e012bf3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e5b7fbc272431791cb942f65d8bb28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/平台简介/u4.png"}},
{
          "id":"604eb3243d30408ebc184292ad6e485d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":135,
              "y":9.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9336e949272441a885e2a4a7414ae48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":135,
                  "y":9.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d64f004191047f98b41451cd2ab9917",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a89a59568d4b21a5e15910a766da09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":360,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组合套餐（初始）/u8.png"}},
{
          "id":"24054befff904d138d0bdf561b451cff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":20,
              "y":46},
            "size":{
              "width":133,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6658b69c5a9f4eee99635c1cd00ea03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":46},
                "size":{
                  "width":133,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b125dde7300146a0aa81434b24ba8696",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":97},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a456b976a55547b1870a0495ccbc2c61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":97},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择农旅路线产品",
                      "target":{
                        "targetType":"page",
                        "url":"选择农旅路线产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/组合套餐（初始）/u12.png"}},
{
          "id":"a1bb5f2ea8c84fbe980c5cfcd3b9ed59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":79},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51c703d1f2334af8a44ae93b5d0400ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":79},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4dc46e9aa44456d8b84366a80ee0767",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":156},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"939795b2aeff467290c66305ea1e4df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":156},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"2bc6bc24938a4d06b90863b97c1b1b28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":168},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e33df937ea4363867df1fddd3f1b18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":168},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32ad90a8d4464b02a55177b44f8a988d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":161},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20d411901adc4a688909c40b6235ef01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":161},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"fb9f165be27c494787089e2bd6dab152",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":195},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f8e045fc5834f53a29475d8ea79da4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":195},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"d9d7d9c65f53437682392ebb3e8b59f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":207},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1267025b27f04de3a575912067107581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":207},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0c0b5a7e97548d7ab6aaeb78e31caff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":259,
              "y":200},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eeb92d72dd443e38334471a478f54fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":259,
                  "y":200},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认预约时间/u35.png"}},
{
          "id":"18e0d6ecf354460b8fe2c55c2e454c58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":321,
              "y":200},
            "size":{
              "width":29,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"502e9978e23a4e018f8dc653a36924fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":321,
                  "y":200},
                "size":{
                  "width":29,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组合套餐（初始）/u28.png"}},
{
          "id":"4917597415d94ebf9f99abafe4c94612",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":301,
              "y":206},
            "size":{
              "width":10,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a70e4c43c37440f79e3b54cdcf2a5643",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":301,
                  "y":206},
                "size":{
                  "width":10,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96374d42dc644178822eb02141b45b75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":112},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1967f6e9005c4d178d73bfbcf5eae7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":112},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"398b61a0b81e4ad1b9c5c47fd8c06a17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":234},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7b5faebcbb24b92821b96fbe7c89c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":234},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"17b2e20c58b9448aa2a4f7955034b850",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":246},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5624b54e398c439298684f28f016a61c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":246},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"470b881f36e546dea076c4d5527916ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":301,
              "y":244},
            "size":{
              "width":45,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6b2fec071b4478a147b707fdc19e63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":244},
                "size":{
                  "width":45,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dde3325dec94bd6a2ad195e369f1fd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":8,
              "y":289},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3986e7ea7b0a4859bfffde5c6a059a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":8,
                  "y":289},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dd81a2245dd4ada9bece3f18a416007",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":347},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa9f879f750e4541b7483cc2b460df78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":347},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"e849b41e676d4dbdb5e2668c5b52ef99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":359},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a7b9585a8d949318562a68c9af4ab4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":359},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e438a64399644b2089aa1a0d5e3f11c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":352},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a3b4fae4b9a4012a3f7df0d26ce0f97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":352},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"49c76e72a65e4b7287ed6c61534641ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":425},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a54b765ec7794b9899aa12c76831c84c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":425},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"dbb6ddaeebd74faeb3d14d30b3fe1d87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":437},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b2f1e235a34c6eaa801801dae67c1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":437},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d7e514566b8493b81a83e2f3df383c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":301,
              "y":436},
            "size":{
              "width":45,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c7cf624e594281a8a5be4ab71e5beb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":436},
                "size":{
                  "width":45,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fce449a46954e9cb339c03d4f379c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":308},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64452853ad2940d3b08d0311f47b9755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":308},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择配送农场",
                      "target":{
                        "targetType":"page",
                        "url":"选择配送农场_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"d334c17fbf0c4076ab1e601c9bb4655f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":320},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8116a7a98cd47779f754719f3c83c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":320},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19e66e6a39b644a2935ad1dd955f98b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":313},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e07fa0ad974d10be8aae5cbc39c65f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":313},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"0a77d3357d7c4c4a83c26d74a49e7f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":320},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073d0222d6b1458aaa11af5a8707bcf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":320},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68111ddbc64b4607bc8acf5f0e6d82f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":386},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13198f3533649769f4b1450d41b1550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":386},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路详情/u48.png"}},
{
          "id":"abf2d6f7e0a94a6dbe63d01acdb52232",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":398},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f8a6275f957499c8a121b9222b7bb51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":398},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10868edac4984725bd40a9ed0391a4db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":391},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bfa851acb894c89bdbda7a4f0ae67dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":391},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"a1ac44ec15184b74ba0867958ff4b6a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":359},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"599a0eb9446c4a11827ef06d87ec6c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":359},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3be6b85054aa49bea747c7d5eb90d06b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":398},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1a5fcb9fc5452b9832de9aabdb711f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":398},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e0852d89efb4856b4fd27f4fd08eefe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":168},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"761bbdbcc2314e81b8207eb68ab9586f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":168},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48b82480280545479a5c2d1063835184",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":63,
              "y":120},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c55be83247a461cba82191291f8fd15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":63,
                  "y":120},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择农旅路线产品",
                      "target":{
                        "targetType":"page",
                        "url":"选择农旅路线产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1573e98a08bc44fcaa2e939136d24a83",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18.5,
              "y":111},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9744e99757ad477f8e026803cdc917d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18.5,
                  "y":111},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u56.png"}},
{
          "id":"08a6e525708846ab9f72f8c4859d6d95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":475},
            "size":{
              "width":360,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7fc093414cc4217b6166650a431d20f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":475},
                "size":{
                  "width":360,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/组合套餐（初始）/u78.png"}},
{
          "id":"cfe1b47c62c34a51a1458dcd18af763b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":475},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1dc80bd551747629bb50bf29d812bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":475},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新人专享套餐/体验游栏首_u12.png"}},
{
          "id":"35b44210e12d442781214ad08845b950",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":482},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ce51cb02dd44f229cb94229806df531",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":482},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0826220ab40a46fcb665cff8e64d07f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":515},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad888e69843455da5e1def665508aef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":515},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40caff1b61e447f3af926466dc037d8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":510},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d17e6f0299f4b45bcd136c0dcd096f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":510},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14db94b591bd4f49a94f6246c477626c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":535},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fa94b7c04c74fd49ca0cbe985303ddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":535},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0a7ba9aa4c0421d99ab8830b57bfc0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":530},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f6f7b0e73ae47c59508fa8ae55b5836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":530},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2e61415091840229b3e302d6524d08f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":9,
              "y":579},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eaf16486f584c9294e014649574d6e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":579},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73b27e495e9d4b57bd678e417ebd053f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":301,
              "y":579},
            "size":{
              "width":45,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cfd2426290c4ecc8bffe03d4d31f9ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":579},
                "size":{
                  "width":45,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8e0f29964d74b0a8a30fd9e96a644f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":556},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a68d724b49402089032b4203b21b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":556},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50dfbfdfc8f14f169a5ec7a4ade1a662",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":553},
            "size":{
              "width":45,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94da486d20d14cd19573e5a0fcb41381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":301,
                  "y":553},
                "size":{
                  "width":45,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26db90c56f0648fbb24a2ac7419d9fa6",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":630},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1d4522ef8f7c4398a73f829d970384b3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4b66ec07437a476d97a12c8cb8f20b4d",
                  "label":"",
                  "parentDynamicPanel":"26db90c56f0648fbb24a2ac7419d9fa6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12aef95b620c43329c7f757021e10fa5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"26db90c56f0648fbb24a2ac7419d9fa6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/新人专享套餐/u250.png"}},
{
                  "id":"e8f74b4d22714554acfa5c6af7d5ef3d",
                  "label":"",
                  "parentDynamicPanel":"26db90c56f0648fbb24a2ac7419d9fa6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":14},
                    "size":{
                      "width":29,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ac6e61d935f45a4a9b991f5eed00725",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"26db90c56f0648fbb24a2ac7419d9fa6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":14},
                        "size":{
                          "width":29,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2307d9e811e0475fb91c1cce11155cb6",
                  "label":"",
                  "parentDynamicPanel":"26db90c56f0648fbb24a2ac7419d9fa6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":230,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18227853726a459aae6a0f5decc4cd2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"26db90c56f0648fbb24a2ac7419d9fa6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":230,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 会员充值",
                              "target":{
                                "targetType":"page",
                                "url":"会员充值_4.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/新人专享套餐/u254.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "c75042ad61c946928365380a36a5bee5":{
      "scriptId":"u0"},
    "908d378ce87346f8821eb7905aa260fa":{
      "scriptId":"u1"},
    "56b62402d67a4b8ca091769a32c03b45":{
      "scriptId":"u2"},
    "d3ebaeecddb74632bef83e093c660714":{
      "scriptId":"u3"},
    "b5acee2ecc514d63999a9a220e012bf3":{
      "scriptId":"u4"},
    "93e5b7fbc272431791cb942f65d8bb28":{
      "scriptId":"u5"},
    "604eb3243d30408ebc184292ad6e485d":{
      "scriptId":"u6"},
    "f9336e949272441a885e2a4a7414ae48":{
      "scriptId":"u7"},
    "0d64f004191047f98b41451cd2ab9917":{
      "scriptId":"u8"},
    "24a89a59568d4b21a5e15910a766da09":{
      "scriptId":"u9"},
    "24054befff904d138d0bdf561b451cff":{
      "scriptId":"u10"},
    "6658b69c5a9f4eee99635c1cd00ea03e":{
      "scriptId":"u11"},
    "b125dde7300146a0aa81434b24ba8696":{
      "scriptId":"u12"},
    "a456b976a55547b1870a0495ccbc2c61":{
      "scriptId":"u13"},
    "a1bb5f2ea8c84fbe980c5cfcd3b9ed59":{
      "scriptId":"u14"},
    "51c703d1f2334af8a44ae93b5d0400ed":{
      "scriptId":"u15"},
    "d4dc46e9aa44456d8b84366a80ee0767":{
      "scriptId":"u16"},
    "939795b2aeff467290c66305ea1e4df5":{
      "scriptId":"u17"},
    "2bc6bc24938a4d06b90863b97c1b1b28":{
      "scriptId":"u18"},
    "43e33df937ea4363867df1fddd3f1b18":{
      "scriptId":"u19"},
    "32ad90a8d4464b02a55177b44f8a988d":{
      "scriptId":"u20"},
    "20d411901adc4a688909c40b6235ef01":{
      "scriptId":"u21"},
    "fb9f165be27c494787089e2bd6dab152":{
      "scriptId":"u22"},
    "7f8e045fc5834f53a29475d8ea79da4e":{
      "scriptId":"u23"},
    "d9d7d9c65f53437682392ebb3e8b59f5":{
      "scriptId":"u24"},
    "1267025b27f04de3a575912067107581":{
      "scriptId":"u25"},
    "e0c0b5a7e97548d7ab6aaeb78e31caff":{
      "scriptId":"u26"},
    "3eeb92d72dd443e38334471a478f54fc":{
      "scriptId":"u27"},
    "18e0d6ecf354460b8fe2c55c2e454c58":{
      "scriptId":"u28"},
    "502e9978e23a4e018f8dc653a36924fd":{
      "scriptId":"u29"},
    "4917597415d94ebf9f99abafe4c94612":{
      "scriptId":"u30"},
    "a70e4c43c37440f79e3b54cdcf2a5643":{
      "scriptId":"u31"},
    "96374d42dc644178822eb02141b45b75":{
      "scriptId":"u32"},
    "1967f6e9005c4d178d73bfbcf5eae7bd":{
      "scriptId":"u33"},
    "398b61a0b81e4ad1b9c5c47fd8c06a17":{
      "scriptId":"u34"},
    "c7b5faebcbb24b92821b96fbe7c89c2f":{
      "scriptId":"u35"},
    "17b2e20c58b9448aa2a4f7955034b850":{
      "scriptId":"u36"},
    "5624b54e398c439298684f28f016a61c":{
      "scriptId":"u37"},
    "470b881f36e546dea076c4d5527916ca":{
      "scriptId":"u38"},
    "de6b2fec071b4478a147b707fdc19e63":{
      "scriptId":"u39"},
    "9dde3325dec94bd6a2ad195e369f1fd6":{
      "scriptId":"u40"},
    "3986e7ea7b0a4859bfffde5c6a059a23":{
      "scriptId":"u41"},
    "3dd81a2245dd4ada9bece3f18a416007":{
      "scriptId":"u42"},
    "fa9f879f750e4541b7483cc2b460df78":{
      "scriptId":"u43"},
    "e849b41e676d4dbdb5e2668c5b52ef99":{
      "scriptId":"u44"},
    "2a7b9585a8d949318562a68c9af4ab4d":{
      "scriptId":"u45"},
    "e438a64399644b2089aa1a0d5e3f11c7":{
      "scriptId":"u46"},
    "8a3b4fae4b9a4012a3f7df0d26ce0f97":{
      "scriptId":"u47"},
    "49c76e72a65e4b7287ed6c61534641ef":{
      "scriptId":"u48"},
    "a54b765ec7794b9899aa12c76831c84c":{
      "scriptId":"u49"},
    "dbb6ddaeebd74faeb3d14d30b3fe1d87":{
      "scriptId":"u50"},
    "29b2f1e235a34c6eaa801801dae67c1e":{
      "scriptId":"u51"},
    "8d7e514566b8493b81a83e2f3df383c9":{
      "scriptId":"u52"},
    "04c7cf624e594281a8a5be4ab71e5beb":{
      "scriptId":"u53"},
    "1fce449a46954e9cb339c03d4f379c17":{
      "scriptId":"u54"},
    "64452853ad2940d3b08d0311f47b9755":{
      "scriptId":"u55"},
    "d334c17fbf0c4076ab1e601c9bb4655f":{
      "scriptId":"u56"},
    "a8116a7a98cd47779f754719f3c83c11":{
      "scriptId":"u57"},
    "19e66e6a39b644a2935ad1dd955f98b5":{
      "scriptId":"u58"},
    "70e07fa0ad974d10be8aae5cbc39c65f":{
      "scriptId":"u59"},
    "0a77d3357d7c4c4a83c26d74a49e7f9c":{
      "scriptId":"u60"},
    "073d0222d6b1458aaa11af5a8707bcf7":{
      "scriptId":"u61"},
    "68111ddbc64b4607bc8acf5f0e6d82f8":{
      "scriptId":"u62"},
    "f13198f3533649769f4b1450d41b1550":{
      "scriptId":"u63"},
    "abf2d6f7e0a94a6dbe63d01acdb52232":{
      "scriptId":"u64"},
    "8f8a6275f957499c8a121b9222b7bb51":{
      "scriptId":"u65"},
    "10868edac4984725bd40a9ed0391a4db":{
      "scriptId":"u66"},
    "2bfa851acb894c89bdbda7a4f0ae67dc":{
      "scriptId":"u67"},
    "a1ac44ec15184b74ba0867958ff4b6a2":{
      "scriptId":"u68"},
    "599a0eb9446c4a11827ef06d87ec6c0a":{
      "scriptId":"u69"},
    "3be6b85054aa49bea747c7d5eb90d06b":{
      "scriptId":"u70"},
    "7a1a5fcb9fc5452b9832de9aabdb711f":{
      "scriptId":"u71"},
    "9e0852d89efb4856b4fd27f4fd08eefe":{
      "scriptId":"u72"},
    "761bbdbcc2314e81b8207eb68ab9586f":{
      "scriptId":"u73"},
    "48b82480280545479a5c2d1063835184":{
      "scriptId":"u74"},
    "6c55be83247a461cba82191291f8fd15":{
      "scriptId":"u75"},
    "1573e98a08bc44fcaa2e939136d24a83":{
      "scriptId":"u76"},
    "9744e99757ad477f8e026803cdc917d8":{
      "scriptId":"u77"},
    "08a6e525708846ab9f72f8c4859d6d95":{
      "scriptId":"u78"},
    "c7fc093414cc4217b6166650a431d20f":{
      "scriptId":"u79"},
    "cfe1b47c62c34a51a1458dcd18af763b":{
      "scriptId":"u80"},
    "e1dc80bd551747629bb50bf29d812bcd":{
      "scriptId":"u81"},
    "35b44210e12d442781214ad08845b950":{
      "scriptId":"u82"},
    "1ce51cb02dd44f229cb94229806df531":{
      "scriptId":"u83"},
    "0826220ab40a46fcb665cff8e64d07f8":{
      "scriptId":"u84"},
    "9ad888e69843455da5e1def665508aef":{
      "scriptId":"u85"},
    "40caff1b61e447f3af926466dc037d8a":{
      "scriptId":"u86"},
    "1d17e6f0299f4b45bcd136c0dcd096f1":{
      "scriptId":"u87"},
    "14db94b591bd4f49a94f6246c477626c":{
      "scriptId":"u88"},
    "6fa94b7c04c74fd49ca0cbe985303ddb":{
      "scriptId":"u89"},
    "b0a7ba9aa4c0421d99ab8830b57bfc0d":{
      "scriptId":"u90"},
    "6f6f7b0e73ae47c59508fa8ae55b5836":{
      "scriptId":"u91"},
    "f2e61415091840229b3e302d6524d08f":{
      "scriptId":"u92"},
    "1eaf16486f584c9294e014649574d6e2":{
      "scriptId":"u93"},
    "73b27e495e9d4b57bd678e417ebd053f":{
      "scriptId":"u94"},
    "8cfd2426290c4ecc8bffe03d4d31f9ed":{
      "scriptId":"u95"},
    "b8e0f29964d74b0a8a30fd9e96a644f2":{
      "scriptId":"u96"},
    "10a68d724b49402089032b4203b21b36":{
      "scriptId":"u97"},
    "50dfbfdfc8f14f169a5ec7a4ade1a662":{
      "scriptId":"u98"},
    "94da486d20d14cd19573e5a0fcb41381":{
      "scriptId":"u99"},
    "26db90c56f0648fbb24a2ac7419d9fa6":{
      "scriptId":"u100"},
    "4b66ec07437a476d97a12c8cb8f20b4d":{
      "scriptId":"u101"},
    "12aef95b620c43329c7f757021e10fa5":{
      "scriptId":"u102"},
    "e8f74b4d22714554acfa5c6af7d5ef3d":{
      "scriptId":"u103"},
    "0ac6e61d935f45a4a9b991f5eed00725":{
      "scriptId":"u104"},
    "2307d9e811e0475fb91c1cce11155cb6":{
      "scriptId":"u105"},
    "18227853726a459aae6a0f5decc4cd2c":{
      "scriptId":"u106"}}});