$axure.loadCurrentPage({
  "url":"特色活动_1.html",
  "generationDate":new Date(1501052593724.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"75b773b64c86405f94bd2abe742bf5e8",
    "type":"Axure:Page",
    "name":"特色活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c12933d0bc24405a612b2201ed1f9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF1F1F1},
            "size":{
              "width":360,
              "height":690},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF1F1F1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b90dc06fd824d4798dead72e9e72137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1},
                "size":{
                  "width":360,
                  "height":690},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF1F1F1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动_1/u0.png"}},
{
          "id":"b72cafcc65174ee9a4594d9231424cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":132},
            "size":{
              "width":360,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2463cf998795441b9172c4620069501e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":132},
                "size":{
                  "width":360,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u50.png"}},
{
          "id":"0ef91a4cdc224eaba9cfe12217693195",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":93},
            "size":{
              "width":360,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc16575a55da4f6cb7d57da467815499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":93},
                "size":{
                  "width":360,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动_1/u4.png"}},
{
          "id":"ab4286f3f88648fd8767f6a378c00c5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":133},
            "size":{
              "width":360,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd54036212ce4224a8403eb69e0151a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":133},
                "size":{
                  "width":360,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动/u37.png"}},
{
          "id":"f1d1c619564c4f71be8b1bc19328094f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":248},
            "size":{
              "width":360,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_安卓_0725/u54_line.png"}},
{
          "id":"f40f1ae5227042818a11014e6ccf7df1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":263},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcd71c7b5e2e433d8c331189b3602922",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":263},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d176849880547c38ace00a4ddea7b3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":9,
              "y":289},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1113211c664045fb8c1de19e2c52dfea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":289},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48197e73253649dbb25a0f2f6ab9da1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":141,
              "y":289},
            "size":{
              "width":40,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f5feb9b87ca47ab85bc716f8caca3ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":141,
                  "y":289},
                "size":{
                  "width":40,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9271009ccb4e48488f1e1efb031b6ff0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":183,
              "y":284},
            "size":{
              "width":28,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"753692ff612d4685ba790025ce2fbb7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":183,
                  "y":284},
                "size":{
                  "width":28,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b143600d816d454daf7f68335a3d89e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":273},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0975182e5c804bfaade40fe95456ff7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":273},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u63.png"}},
{
          "id":"aec2f1bb644345fc98009f74cd8f4fb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":323},
            "size":{
              "width":360,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"401b959d2f844a82a94ef22c508758e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":323},
                "size":{
                  "width":360,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u50.png"}},
{
          "id":"e5858d6b950f4c9bbe11edcea9a21a07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":324},
            "size":{
              "width":360,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce96722e5854707968accfafb95fa44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":324},
                "size":{
                  "width":360,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动/u52.jpg"}},
{
          "id":"b88453297b794296b70d89525eea880d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":439},
            "size":{
              "width":360,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_安卓_0725/u54_line.png"}},
{
          "id":"42f2bdd9931b4d7a8dfeafc8212ed180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":454},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6738eac450a41f3a037a046e78ca4e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":454},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5beace90364d437f9323c9ca7bb7898c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":9,
              "y":480},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2e15f40c34c4ecb8d906f5e384925ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":480},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09a73167828146b4b22236ac5475e375",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":141,
              "y":480},
            "size":{
              "width":40,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37fa9bcc66574075aa53715aac4db5c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":141,
                  "y":480},
                "size":{
                  "width":40,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5708c492cee542089b9af37eb8ce2292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":183,
              "y":475},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8e082aa93ae4329a50370bd2cfe83ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":183,
                  "y":475},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24dddad65c3c4c7ea9edb4d82e4cbb07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":464},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"796f803be4be4de1a1ff18131e723ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":464},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u63.png"}},
{
          "id":"74f1218be63d46d39770fc898d8a73bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":514},
            "size":{
              "width":360,
              "height":181}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0381390ab7474ecd91ae6d7bd710ffd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":514},
                "size":{
                  "width":360,
                  "height":181}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u50.png"}},
{
          "id":"f12af0bb7e044b83b87cb3bfbd0b3d98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":515},
            "size":{
              "width":360,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"877413b7b9d94d39a6f55461f9e65639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":515},
                "size":{
                  "width":360,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动/u67.jpg"}},
{
          "id":"4a9c08376bd6474380076beff39e2d13",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":630},
            "size":{
              "width":360,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页_安卓_0725/u54_line.png"}},
{
          "id":"f5ed464e0e004d659ee5a7b4a3356245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":645},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3fc7bb66c944df1a4804bb79b6bdbc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":645},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b260fc7c70dc4cf1af79a71b8fd277bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":8,
              "y":671},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ddb07545ad441b90ff30ec292a3647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":671},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b7efcd06a0b48db915974341f213a5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":140,
              "y":671},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e8723eac994dca989600b335c8728b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":671},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34104affef10443d85ffe2f6c26cf893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":182,
              "y":666},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c834a8d61f5f4c25a123b0d345f65e52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":182,
                  "y":666},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e708d33326fb42a8b7c7c798c61a9943",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":655},
            "size":{
              "width":80,
              "height":30},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332c38b4c8d1454ea0512d322d342858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":655},
                "size":{
                  "width":80,
                  "height":30},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u63.png"}},
{
          "id":"d4c2fef46fe142cca34b32ac7e34340c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fca9225e2854f72b7229458ab88bf85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_0725/u217.png"}},
{
          "id":"18d262941ea441c187a137b1a4173ab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":11,
              "y":11},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"533fcb5b0c6d4b8d87a0a818f5edd46b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":11,
                  "y":11},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a5bdc65976f428089c4f0040cd3c6b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":70,
              "y":7},
            "size":{
              "width":282,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0bcc573d4b4423c9022f199e702e87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":70,
                  "y":7},
                "size":{
                  "width":282,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/u14.png"}},
{
          "id":"a0b4a81dfae44df2bb11a6674a7206bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":100,
              "y":13},
            "size":{
              "width":78,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ccadeeaceea486ca1bc1ee9fd4c9fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":13},
                "size":{
                  "width":78,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"878954e00444429baee1fe1b4e94a59a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":14},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d061f32fe09b450aa4ea77bbf2d8ef89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动/u20.png"}},
{
          "id":"297038f79e50452dbb5020876822e5ee",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":45}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b29b2be8f85e4072b5118836ba2e97af",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1202b4fd5602463b9f5feaa3d62f1dc4",
                  "label":"",
                  "parentDynamicPanel":"297038f79e50452dbb5020876822e5ee",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"531c150725674364b4d1209380c90c94",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"a952f40052934b63bbbeded5df6d1026",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":780,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9f7bec6ec9fb43f69e65a5c6acd07b35",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":780,
                                  "height":40}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/主页_安卓_/u22.png"}},
{
                          "id":"2fea510e4d664727add57f41dc993b5a",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":13},
                            "size":{
                              "width":53,
                              "height":13},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF0099FF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8df726c78da443f999069c05aa80fafb",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":13},
                                "size":{
                                  "width":53,
                                  "height":13},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFF0099FF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"5587a93b531b4c53a6205bbc7ee9749b",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":86,
                              "y":35},
                            "size":{
                              "width":70,
                              "height":10},
                            "borderWidth":"2",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF0099FF}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/主页_安卓_/u26_line.png"}},
{
                          "id":"40d04c61ddaa42e5abe5a2fba5963542",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":170,
                              "y":12},
                            "size":{
                              "width":66,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"26e15ba87ac64042b08a3af5f883386f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":170,
                                  "y":12},
                                "size":{
                                  "width":66,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"3517ed5a3da3411eb28d496bcd586e52",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":349,
                              "y":12},
                            "size":{
                              "width":61,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9100ca5c13f148258cf5ce2737b20ab2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":349,
                                  "y":12},
                                "size":{
                                  "width":61,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"bca2fcb567284ac5885e4fc08761b7cf",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":604,
                              "y":12},
                            "size":{
                              "width":66,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"72bc717f7b2640e886e7bdaeaaaea673",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":604,
                                  "y":12},
                                "size":{
                                  "width":66,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"dfc97bf1d2274da881512539351ee079",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":258,
                              "y":12},
                            "size":{
                              "width":66,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"cdfdf4002f6a42c194e60471111f5166",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":258,
                                  "y":12},
                                "size":{
                                  "width":66,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"59591591d0234533bc23db0c9dbe804b",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":430,
                              "y":12},
                            "size":{
                              "width":66,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c04603ce44bf489ba7a5d8f3d6758b42",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":430,
                                  "y":12},
                                "size":{
                                  "width":66,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"c2f60fbf6e0f427183d6511a0e5a54b5",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":520,
                              "y":12},
                            "size":{
                              "width":66,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f72b6421622f4f299a4cea19ed0b1440",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":520,
                                  "y":12},
                                "size":{
                                  "width":66,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"cf15d3534a274d1692cf581bc419d00e",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0099FF,
                              "opacity":1},
                            "location":{
                              "x":94,
                              "y":12},
                            "size":{
                              "width":53,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b083c1ca761941ee8716852a6522f792",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF0099FF,
                                  "opacity":1},
                                "location":{
                                  "x":94,
                                  "y":12},
                                "size":{
                                  "width":53,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"49927180749e4644909b686020181193",
                          "label":"",
                          "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":690,
                              "y":12},
                            "size":{
                              "width":79,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f0d1d8742332418180b655d8f5bc9e58",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1202b4fd5602463b9f5feaa3d62f1dc4",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":690,
                                  "y":12},
                                "size":{
                                  "width":79,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]}]}]}]},
{
          "id":"7e4554fb0db14066a40c869a4eacde6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":10},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b91d41a43b448386b769efcb03cff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":10},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/u44.png"}},
{
          "id":"9c8da3e124274d18a7c2a194acdd649a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":39},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1380a5bf8d48476ead5e1d64a6798953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":39},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/u46.png"}},
{
          "id":"f48fe3a5c3d84fb183aa7571efd8aeef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":47},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a685b4223104bfab3e5cda1f67bbf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":328,
                  "y":47},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特色活动/u20.png"}},
{
          "id":"e08a1735d0ea49cfa98a081d16a1b89c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":39},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"dd55564beecf473b8178d42989910512",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":9,
              "y":101},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7943030f2614cb6b12f6e5f0c39624d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":9,
                  "y":101},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac9ed8e142b84f8e9f3bbc7020576180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":310,
              "y":100},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"655a11ee3c2b4e74a10602d09f2b5ecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":100},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f01ba40b46ea46fdb584abbb838a2a95",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":695},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ca539273b7914e6c8590b8044a330f61",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4725a87366154c239f5e68f657942614",
                  "label":"",
                  "parentDynamicPanel":"f01ba40b46ea46fdb584abbb838a2a95",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "masterId":"864967e889e541e9958747926389b524"}]}]}]}},
  "masters":{
    "864967e889e541e9958747926389b524":{
      "packageId":"864967e889e541e9958747926389b524",
      "type":"Axure:Master",
      "name":"底部菜单0726",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d3980e768e434d6e8006717cfc1027d7",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"33e17ce2012b4cbda3b4e022b57a30db",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"5302c9f29ec84d49b96b0cdde12c2d96",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":360,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5ce46e8bf0f1475fb3b3b7da2d61bfd4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":360,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_/u134.png"}},
{
                    "id":"dbd6a5f83af64ab191b7f078d53db2df",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":39,
                        "y":24},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c081ce32660247bfb9c77e35f3c9f8df",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":39,
                            "y":24},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9456264ba204c659a73730ac5f9be10",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":118,
                        "y":24},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"38b51ec901e940038aa1d61e70cebbae",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":118,
                            "y":24},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cd39e767b2cb408a81a6c3721408db6b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":198,
                        "y":24},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"45450782be8a4066b51da07d94fc70ca",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":198,
                            "y":24},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"0d3829ac6ae645118ae248d779627e03",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":277,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1e699b0485d842fda37a4804fbb1a443",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":277,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"537a1d54bb024094a5238b61a93b1b3b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":39,
                        "y":2},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7e66d880a8948f286fa211dbac91888",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":39,
                            "y":2},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u36.png"}},
{
                    "id":"b7f155757800405f98f3a2e19819a135",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":288,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"de6f0a9691d847e8be63625ea68a2fad",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":288,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u42.png"}},
{
                    "id":"806e77a021e44ddb9e4b2ec499bc008e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":118,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fcb44076144736abafdcb00a145142",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":118,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_/u148.png"}},
{
                    "id":"0855a01c3bf8421f852d6f1786340508",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":199,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9b3f8f00dd784297b8062985a5c291b6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":199,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_/u150.png"}},
{
                    "id":"b01444f95aeb4686a41a1b02e9924322",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主页(安卓)",
                                "target":{
                                  "targetType":"page",
                                  "url":"主页_安卓_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"c571f4e1ff0749f4b80729d3b1cad885",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":267.5,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]},
{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"75de4c9dd38e43f494a2161c0a3c9108",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":179,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 会员充值",
                                "target":{
                                  "targetType":"page",
                                  "url":"会员充值_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]},
{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}]}]}}},
  "objectPaths":{
    "7c12933d0bc24405a612b2201ed1f9d0":{
      "scriptId":"u0"},
    "9b90dc06fd824d4798dead72e9e72137":{
      "scriptId":"u1"},
    "b72cafcc65174ee9a4594d9231424cb2":{
      "scriptId":"u2"},
    "2463cf998795441b9172c4620069501e":{
      "scriptId":"u3"},
    "0ef91a4cdc224eaba9cfe12217693195":{
      "scriptId":"u4"},
    "dc16575a55da4f6cb7d57da467815499":{
      "scriptId":"u5"},
    "ab4286f3f88648fd8767f6a378c00c5f":{
      "scriptId":"u6"},
    "dd54036212ce4224a8403eb69e0151a7":{
      "scriptId":"u7"},
    "f1d1c619564c4f71be8b1bc19328094f":{
      "scriptId":"u8"},
    "f40f1ae5227042818a11014e6ccf7df1":{
      "scriptId":"u9"},
    "dcd71c7b5e2e433d8c331189b3602922":{
      "scriptId":"u10"},
    "9d176849880547c38ace00a4ddea7b3e":{
      "scriptId":"u11"},
    "1113211c664045fb8c1de19e2c52dfea":{
      "scriptId":"u12"},
    "48197e73253649dbb25a0f2f6ab9da1f":{
      "scriptId":"u13"},
    "8f5feb9b87ca47ab85bc716f8caca3ca":{
      "scriptId":"u14"},
    "9271009ccb4e48488f1e1efb031b6ff0":{
      "scriptId":"u15"},
    "753692ff612d4685ba790025ce2fbb7e":{
      "scriptId":"u16"},
    "b143600d816d454daf7f68335a3d89e6":{
      "scriptId":"u17"},
    "0975182e5c804bfaade40fe95456ff7b":{
      "scriptId":"u18"},
    "aec2f1bb644345fc98009f74cd8f4fb6":{
      "scriptId":"u19"},
    "401b959d2f844a82a94ef22c508758e5":{
      "scriptId":"u20"},
    "e5858d6b950f4c9bbe11edcea9a21a07":{
      "scriptId":"u21"},
    "4ce96722e5854707968accfafb95fa44":{
      "scriptId":"u22"},
    "b88453297b794296b70d89525eea880d":{
      "scriptId":"u23"},
    "42f2bdd9931b4d7a8dfeafc8212ed180":{
      "scriptId":"u24"},
    "a6738eac450a41f3a037a046e78ca4e4":{
      "scriptId":"u25"},
    "5beace90364d437f9323c9ca7bb7898c":{
      "scriptId":"u26"},
    "c2e15f40c34c4ecb8d906f5e384925ca":{
      "scriptId":"u27"},
    "09a73167828146b4b22236ac5475e375":{
      "scriptId":"u28"},
    "37fa9bcc66574075aa53715aac4db5c7":{
      "scriptId":"u29"},
    "5708c492cee542089b9af37eb8ce2292":{
      "scriptId":"u30"},
    "b8e082aa93ae4329a50370bd2cfe83ae":{
      "scriptId":"u31"},
    "24dddad65c3c4c7ea9edb4d82e4cbb07":{
      "scriptId":"u32"},
    "796f803be4be4de1a1ff18131e723ef5":{
      "scriptId":"u33"},
    "74f1218be63d46d39770fc898d8a73bf":{
      "scriptId":"u34"},
    "0381390ab7474ecd91ae6d7bd710ffd5":{
      "scriptId":"u35"},
    "f12af0bb7e044b83b87cb3bfbd0b3d98":{
      "scriptId":"u36"},
    "877413b7b9d94d39a6f55461f9e65639":{
      "scriptId":"u37"},
    "4a9c08376bd6474380076beff39e2d13":{
      "scriptId":"u38"},
    "f5ed464e0e004d659ee5a7b4a3356245":{
      "scriptId":"u39"},
    "b3fc7bb66c944df1a4804bb79b6bdbc0":{
      "scriptId":"u40"},
    "b260fc7c70dc4cf1af79a71b8fd277bc":{
      "scriptId":"u41"},
    "e1ddb07545ad441b90ff30ec292a3647":{
      "scriptId":"u42"},
    "7b7efcd06a0b48db915974341f213a5b":{
      "scriptId":"u43"},
    "31e8723eac994dca989600b335c8728b":{
      "scriptId":"u44"},
    "34104affef10443d85ffe2f6c26cf893":{
      "scriptId":"u45"},
    "c834a8d61f5f4c25a123b0d345f65e52":{
      "scriptId":"u46"},
    "e708d33326fb42a8b7c7c798c61a9943":{
      "scriptId":"u47"},
    "332c38b4c8d1454ea0512d322d342858":{
      "scriptId":"u48"},
    "d4c2fef46fe142cca34b32ac7e34340c":{
      "scriptId":"u49"},
    "8fca9225e2854f72b7229458ab88bf85":{
      "scriptId":"u50"},
    "18d262941ea441c187a137b1a4173ab0":{
      "scriptId":"u51"},
    "533fcb5b0c6d4b8d87a0a818f5edd46b":{
      "scriptId":"u52"},
    "7a5bdc65976f428089c4f0040cd3c6b3":{
      "scriptId":"u53"},
    "b0bcc573d4b4423c9022f199e702e87d":{
      "scriptId":"u54"},
    "a0b4a81dfae44df2bb11a6674a7206bf":{
      "scriptId":"u55"},
    "6ccadeeaceea486ca1bc1ee9fd4c9fb2":{
      "scriptId":"u56"},
    "878954e00444429baee1fe1b4e94a59a":{
      "scriptId":"u57"},
    "d061f32fe09b450aa4ea77bbf2d8ef89":{
      "scriptId":"u58"},
    "297038f79e50452dbb5020876822e5ee":{
      "scriptId":"u59"},
    "1202b4fd5602463b9f5feaa3d62f1dc4":{
      "scriptId":"u60"},
    "a952f40052934b63bbbeded5df6d1026":{
      "scriptId":"u61"},
    "9f7bec6ec9fb43f69e65a5c6acd07b35":{
      "scriptId":"u62"},
    "2fea510e4d664727add57f41dc993b5a":{
      "scriptId":"u63"},
    "8df726c78da443f999069c05aa80fafb":{
      "scriptId":"u64"},
    "5587a93b531b4c53a6205bbc7ee9749b":{
      "scriptId":"u65"},
    "40d04c61ddaa42e5abe5a2fba5963542":{
      "scriptId":"u66"},
    "26e15ba87ac64042b08a3af5f883386f":{
      "scriptId":"u67"},
    "3517ed5a3da3411eb28d496bcd586e52":{
      "scriptId":"u68"},
    "9100ca5c13f148258cf5ce2737b20ab2":{
      "scriptId":"u69"},
    "bca2fcb567284ac5885e4fc08761b7cf":{
      "scriptId":"u70"},
    "72bc717f7b2640e886e7bdaeaaaea673":{
      "scriptId":"u71"},
    "dfc97bf1d2274da881512539351ee079":{
      "scriptId":"u72"},
    "cdfdf4002f6a42c194e60471111f5166":{
      "scriptId":"u73"},
    "59591591d0234533bc23db0c9dbe804b":{
      "scriptId":"u74"},
    "c04603ce44bf489ba7a5d8f3d6758b42":{
      "scriptId":"u75"},
    "c2f60fbf6e0f427183d6511a0e5a54b5":{
      "scriptId":"u76"},
    "f72b6421622f4f299a4cea19ed0b1440":{
      "scriptId":"u77"},
    "cf15d3534a274d1692cf581bc419d00e":{
      "scriptId":"u78"},
    "b083c1ca761941ee8716852a6522f792":{
      "scriptId":"u79"},
    "49927180749e4644909b686020181193":{
      "scriptId":"u80"},
    "f0d1d8742332418180b655d8f5bc9e58":{
      "scriptId":"u81"},
    "7e4554fb0db14066a40c869a4eacde6c":{
      "scriptId":"u82"},
    "56b91d41a43b448386b769efcb03cff7":{
      "scriptId":"u83"},
    "9c8da3e124274d18a7c2a194acdd649a":{
      "scriptId":"u84"},
    "1380a5bf8d48476ead5e1d64a6798953":{
      "scriptId":"u85"},
    "f48fe3a5c3d84fb183aa7571efd8aeef":{
      "scriptId":"u86"},
    "3a685b4223104bfab3e5cda1f67bbf99":{
      "scriptId":"u87"},
    "e08a1735d0ea49cfa98a081d16a1b89c":{
      "scriptId":"u88"},
    "dd55564beecf473b8178d42989910512":{
      "scriptId":"u89"},
    "d7943030f2614cb6b12f6e5f0c39624d":{
      "scriptId":"u90"},
    "ac9ed8e142b84f8e9f3bbc7020576180":{
      "scriptId":"u91"},
    "655a11ee3c2b4e74a10602d09f2b5ecd":{
      "scriptId":"u92"},
    "f01ba40b46ea46fdb584abbb838a2a95":{
      "scriptId":"u93"},
    "4725a87366154c239f5e68f657942614":{
      "scriptId":"u94",
      "d3980e768e434d6e8006717cfc1027d7":{
        "scriptId":"u95"},
      "5302c9f29ec84d49b96b0cdde12c2d96":{
        "scriptId":"u96"},
      "5ce46e8bf0f1475fb3b3b7da2d61bfd4":{
        "scriptId":"u97"},
      "dbd6a5f83af64ab191b7f078d53db2df":{
        "scriptId":"u98"},
      "c081ce32660247bfb9c77e35f3c9f8df":{
        "scriptId":"u99"},
      "f9456264ba204c659a73730ac5f9be10":{
        "scriptId":"u100"},
      "38b51ec901e940038aa1d61e70cebbae":{
        "scriptId":"u101"},
      "cd39e767b2cb408a81a6c3721408db6b":{
        "scriptId":"u102"},
      "45450782be8a4066b51da07d94fc70ca":{
        "scriptId":"u103"},
      "0d3829ac6ae645118ae248d779627e03":{
        "scriptId":"u104"},
      "1e699b0485d842fda37a4804fbb1a443":{
        "scriptId":"u105"},
      "537a1d54bb024094a5238b61a93b1b3b":{
        "scriptId":"u106"},
      "e7e66d880a8948f286fa211dbac91888":{
        "scriptId":"u107"},
      "b7f155757800405f98f3a2e19819a135":{
        "scriptId":"u108"},
      "de6f0a9691d847e8be63625ea68a2fad":{
        "scriptId":"u109"},
      "806e77a021e44ddb9e4b2ec499bc008e":{
        "scriptId":"u110"},
      "d7fcb44076144736abafdcb00a145142":{
        "scriptId":"u111"},
      "0855a01c3bf8421f852d6f1786340508":{
        "scriptId":"u112"},
      "9b3f8f00dd784297b8062985a5c291b6":{
        "scriptId":"u113"},
      "b01444f95aeb4686a41a1b02e9924322":{
        "scriptId":"u114"},
      "c571f4e1ff0749f4b80729d3b1cad885":{
        "scriptId":"u115"},
      "75de4c9dd38e43f494a2161c0a3c9108":{
        "scriptId":"u116"}}}});