$axure.loadCurrentPage({
  "url":"确认订单_1.html",
  "generationDate":new Date(1503365075609.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"feafe59053784b5c83482a9b505ccb30",
    "type":"Axure:Page",
    "name":"确认订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"设置 值于 package = &quot;fasle&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetGlobalVariableValue",
                      "arguments":[{
                          "exprType":"globalVariableLiteral",
                          "variableName":"package"},
{
                          "exprType":"stringLiteral",
                          "value":"fasle",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"69522d4f37c545baa5ab1d367f651974",
          "label":"配送设置面板",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":1000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa2b227c6784b85a4b21c7f7f231842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":1000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单_1/配送设置面板_u0.png"}},
{
          "id":"2391244f1f394a6ca32cb5309caf33dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3862ea5fc97341b8ab1d542cc0a13748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/top_u2.png"}},
{
          "id":"40dc83185821431c9a3b37807c09caa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":143.5,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7a1e45e22d4f9d929ae3d192ce8e23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":143.5,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38473f7c025c42958424c2a2223adb2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83d77037c9df419fbf900ef0904ce927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/平台简介/u4.png"}},
{
          "id":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":910},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"467296247e744101ad9a98fb842daaa1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d601fd5d81ca41ad9fa5455186dab207",
                  "label":"",
                  "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea4dcbf1602d4dd1b8986d94393f86ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蜜桃/u40.png"}},
{
                  "id":"f10cb96905384beaad5d8e4ac33a8edd",
                  "label":"",
                  "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":15},
                    "size":{
                      "width":90,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce15c513ba4c4610a867a172aedd03e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":15},
                        "size":{
                          "width":90,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5f30bc240d943f9bd6a25d2454d31fd",
                  "label":"",
                  "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b82629eff3bf464dacf20e564452544d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a3cc1b1f0e346c5a0f2769a58cf56d0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 订单支付页",
                              "target":{
                                "targetType":"page",
                                "url":"订单支付页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/确认订单/u13.png"}}]}]},
{
          "id":"dd9c603606e94b53bd090964bfc44be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":149},
            "size":{
              "width":360,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9794369f1bf64cea9a21bc11498aec0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":149},
                "size":{
                  "width":360,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u15.png"}},
{
          "id":"23c600fd61914e8ca927d84c01ef9e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":45},
            "size":{
              "width":360,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"665b391e3fff4a9db2c71beeca7397b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":45},
                "size":{
                  "width":360,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单_1/u17.png"}},
{
          "id":"022fb6533114438bb7dff1ebbf250b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":8,
              "y":76},
            "size":{
              "width":330,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a656fc9f9114057adfd774637532dcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":8,
                  "y":76},
                "size":{
                  "width":330,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f67b2180767549ca8e15a55b008325e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":310},
            "size":{
              "width":360,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ceb8e587a4a4063a06d8f336e0b90e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":310},
                "size":{
                  "width":360,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u21.png"}},
{
          "id":"a821a7b663d944c2bc081200e47effd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":342},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11cff4deba5c45868213a010a426154c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":342},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u23.png"}},
{
          "id":"57583bbab3a448d79a942237793806a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":353},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a068c509ff54683a8900e5207315be0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":353},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4d9bdc0689e4a0d83760ffeb686fd19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":353},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea8b6348db84f7b90eebf7858f75c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":353},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d86a0dde82b45e681c3c1b459cc34e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":379},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aae63639dc64247b44c7dec1c137d60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":379},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1888cc569d924faf9f754e7ae0627a0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":295,
              "y":355},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6cd319030074e2c8642cd18210707b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":295,
                  "y":355},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8de2f8ea59c74d3b86f1cbbdf4adb45b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":328,
              "y":379},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eaafaa5c1d5458b90b9f480e92bf430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":379},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e432dbb24c014b58bc2844a063ef2708",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":401},
            "size":{
              "width":360,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be1e283594974e619957f684a460e61f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":401},
                "size":{
                  "width":360,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u23.png"}},
{
          "id":"afe9c45cd6fa436c8e7411c4fd4413f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":412},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace98a162ad44f9da0dc0aaf912a19aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":412},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13195ec46a454612a2bba5b2d6ca40dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":412},
            "size":{
              "width":115,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d64761b0824db98f43cadcee3bcc4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":412},
                "size":{
                  "width":115,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c23e91c2e7e947b2abfb9ef9f5b0e554",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":438},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f8c5b4a1c0c4ba3b43b1ac455448d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":438},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63b4c79e434d45bda90499e961afcb6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":328,
              "y":438},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36f6860fd7c942e4bd9a8b61ec207a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":438},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9b21636a1aa44c393b96c040076fd1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":460},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82975f07cdcf4bb58a341dbc57d81344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":460},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/top_u2.png"}},
{
          "id":"41ffa23a13bc4811bab6feab38b58af5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":463},
            "size":{
              "width":34,
              "height":34},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f542aed04294d3d8595ddef1176fda6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":463},
                "size":{
                  "width":34,
                  "height":34},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u47.png"}},
{
          "id":"40e7bb45006845fab8631020b4a4bebd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":472},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa7cd5a1afc4307a7f3bc73dd2ecf5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":472},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e705c3cdacc240d69f19c47c24fc6308",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":319},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ea4f384a884e4d8d1353e2934d98fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":319},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c808e2e3dc34d96be365b06f29828a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":120},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3cc23ec3d4f4832afb41504c13cd132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":120},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9069125e3544d3da5e80935ebe0f011",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":120},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"883482b4cf1c41318ccc4400be93d0ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dae3c14d0d14579b3e60efd1619fea7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":15,
              "y":53},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b6fa6f71ad48e1abe183f68c68b761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":15,
                  "y":53},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cea30c028fa540208b42111b1dee20ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":15,
              "y":160},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a75c3ed7a38440a936fceb144890be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":15,
                  "y":160},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b47d4a9fa8254037b4f899093d251be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":269},
            "size":{
              "width":360,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38afba8640c1473ba7e19c0637cb8b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":269},
                "size":{
                  "width":360,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新人专享套餐/体验游栏首_u12.png"}},
{
          "id":"1720820f00e74a5b8456237a0665ac4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":186},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"877f328e64b84fd5b5b18055fc2d6159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":186},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5a9f74fa2034678886d6eafbeeccdce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":212},
            "size":{
              "width":209,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb9173f305c431bac853b3f3d7e91ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":212},
                "size":{
                  "width":209,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e9854e13f0f41129392573edc40af9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":238},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d662659bb7fb454fbd58f1d210462aa8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":238},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"536b7c9ec9d548f3aab0c65e93206b31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":510},
            "size":{
              "width":360,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3d9a1300d064e24a4c88490ed822351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":510},
                "size":{
                  "width":360,
                  "height":93}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u63.png"}},
{
          "id":"0f526b86ebd84ffc81576980db6fb413",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":519},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18b543c776b4845a30f72745bd40949",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":519},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a800c46a20564ac2b7a3721e1d75b21e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":540},
            "size":{
              "width":360,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51767f7c10d74d91928d373cc82e1213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":540},
                "size":{
                  "width":360,
                  "height":63}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u67.png"}},
{
          "id":"dd3cbb51d1f944f68d5f4d6617c57f78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":582},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a9302ee371473a811d75a1a5cc557f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":582},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bc7f73fdb874bb7ab49996bdbac38a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":547},
            "size":{
              "width":341,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52ae05abf4ad4e03be418a8cb1490a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":547},
                "size":{
                  "width":341,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d6367d71c1f40b0b59cc57b79151ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":328,
              "y":583},
            "size":{
              "width":23,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b377c1572db446dcb734c36e0263bb05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":328,
                  "y":583},
                "size":{
                  "width":23,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89489d14e934437b8b828914c54f8ead",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":613},
            "size":{
              "width":358,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8cccd92efe543709fe7369c50b67d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":613},
                "size":{
                  "width":358,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u75.png"}},
{
          "id":"72fc30c1b7b346f1804978df78cb31e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":625},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93d173cc7dc54aca81bd9651dc5c53a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":625},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bb64c98b5f240ca9962ddecded26c94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":290,
              "y":625},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a93d8dd3a8064a9fb3895f5121e4fecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":625},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47a888a17b384d478265248b7b25239e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":652},
            "size":{
              "width":358,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3c4e20f5a394527b662960b0c40037b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":652},
                "size":{
                  "width":358,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u75.png"}},
{
          "id":"9f88094edc234a9888dab33d49388350",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":665},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a0184dfbed04fca894ef659a9035569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":665},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"149d246469b645d9960b879905ee0653",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":311,
              "y":665},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9839e3a710a8431ba890209ebaaa0059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":311,
                  "y":665},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f9a452b65ff48a19294588161687f5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":691},
            "size":{
              "width":358,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adbaf93940604ccbb73a81beb4f5bf0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":691},
                "size":{
                  "width":358,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u75.png"}},
{
          "id":"d8a96bab62914802a9502a26dbe4c55b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":703},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3cee38f90d402893c4a82e2b9b3b16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":703},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fef38b88c8044d819f2a4fdc190e9827",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":298,
              "y":703},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd56f77d206849359c416614453fdf86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":298,
                  "y":703},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a04d675e256d4d2883ed734fa09d07d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":79,
              "y":704},
            "size":{
              "width":62,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1757529520204b70937730a614761e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":704},
                "size":{
                  "width":62,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a1adda2c676407bbe35f4eda4ac699a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":779},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1197a4dc2f6a4e498cfae36be4039c0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":779},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u95.png"}},
{
          "id":"499c4cf46c6b4cd3bb65cf905082a1e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":791},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d367b75db7b7439cb54bc2d7002313f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":791},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59a638cd496f4caabf18659211125eea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":783},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1c2bf4e200143f092dbc165d946f0f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":783},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"fa9ac6a8b44d4024b8c52c4e9cd4833a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":791},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fee7455a385c418f8d41d4b95554db71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":791},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c355e48719494ddb82c1fe91f6494671",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":818},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a5639ac2234afeb26856cc00272ad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":818},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u95.png"}},
{
          "id":"6d6a96f45e7f418d9d7f307d78675ea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":830},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21fd7802dca64450a879caf1a5f3ad05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":830},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eaa5d2b8afcd477a89832029bf93a1e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":822},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61851d69bc542b3be5111b334e63a12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":822},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"cc7ab4d2252a4300a583945fa78daf66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":830},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcbdd49fef15491095642dde397b25b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":830},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78ceaafc3f90477b87acf52a1d8dde27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":741},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3674b2f8de2f42a39643553516161c99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":741},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认订单/u95.png"}},
{
          "id":"865529dddaf2476b88ec4c405d727140",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":753},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff8f016b6aaa4fdabc14f04335acd393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":753},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa409bf382314eac8ec43627c11f68a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":753},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2afba409878f4ee59ab3c891f7b783d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":753},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3991876cc584e6b9d5b2815b19d2568",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":221,
              "y":276},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b7fce11cf8b4802afc5dfc8ee9cb488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":221,
                  "y":276},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "69522d4f37c545baa5ab1d367f651974":{
      "scriptId":"u0"},
    "4fa2b227c6784b85a4b21c7f7f231842":{
      "scriptId":"u1"},
    "2391244f1f394a6ca32cb5309caf33dc":{
      "scriptId":"u2"},
    "3862ea5fc97341b8ab1d542cc0a13748":{
      "scriptId":"u3"},
    "40dc83185821431c9a3b37807c09caa5":{
      "scriptId":"u4"},
    "0d7a1e45e22d4f9d929ae3d192ce8e23":{
      "scriptId":"u5"},
    "38473f7c025c42958424c2a2223adb2a":{
      "scriptId":"u6"},
    "83d77037c9df419fbf900ef0904ce927":{
      "scriptId":"u7"},
    "0a3cc1b1f0e346c5a0f2769a58cf56d0":{
      "scriptId":"u8"},
    "d601fd5d81ca41ad9fa5455186dab207":{
      "scriptId":"u9"},
    "ea4dcbf1602d4dd1b8986d94393f86ed":{
      "scriptId":"u10"},
    "f10cb96905384beaad5d8e4ac33a8edd":{
      "scriptId":"u11"},
    "ce15c513ba4c4610a867a172aedd03e0":{
      "scriptId":"u12"},
    "f5f30bc240d943f9bd6a25d2454d31fd":{
      "scriptId":"u13"},
    "b82629eff3bf464dacf20e564452544d":{
      "scriptId":"u14"},
    "dd9c603606e94b53bd090964bfc44be8":{
      "scriptId":"u15"},
    "9794369f1bf64cea9a21bc11498aec0f":{
      "scriptId":"u16"},
    "23c600fd61914e8ca927d84c01ef9e37":{
      "scriptId":"u17"},
    "665b391e3fff4a9db2c71beeca7397b3":{
      "scriptId":"u18"},
    "022fb6533114438bb7dff1ebbf250b7e":{
      "scriptId":"u19"},
    "9a656fc9f9114057adfd774637532dcf":{
      "scriptId":"u20"},
    "f67b2180767549ca8e15a55b008325e8":{
      "scriptId":"u21"},
    "6ceb8e587a4a4063a06d8f336e0b90e1":{
      "scriptId":"u22"},
    "a821a7b663d944c2bc081200e47effd1":{
      "scriptId":"u23"},
    "11cff4deba5c45868213a010a426154c":{
      "scriptId":"u24"},
    "57583bbab3a448d79a942237793806a5":{
      "scriptId":"u25"},
    "0a068c509ff54683a8900e5207315be0":{
      "scriptId":"u26"},
    "c4d9bdc0689e4a0d83760ffeb686fd19":{
      "scriptId":"u27"},
    "fea8b6348db84f7b90eebf7858f75c3a":{
      "scriptId":"u28"},
    "3d86a0dde82b45e681c3c1b459cc34e2":{
      "scriptId":"u29"},
    "8aae63639dc64247b44c7dec1c137d60":{
      "scriptId":"u30"},
    "1888cc569d924faf9f754e7ae0627a0c":{
      "scriptId":"u31"},
    "c6cd319030074e2c8642cd18210707b3":{
      "scriptId":"u32"},
    "8de2f8ea59c74d3b86f1cbbdf4adb45b":{
      "scriptId":"u33"},
    "5eaafaa5c1d5458b90b9f480e92bf430":{
      "scriptId":"u34"},
    "e432dbb24c014b58bc2844a063ef2708":{
      "scriptId":"u35"},
    "be1e283594974e619957f684a460e61f":{
      "scriptId":"u36"},
    "afe9c45cd6fa436c8e7411c4fd4413f3":{
      "scriptId":"u37"},
    "ace98a162ad44f9da0dc0aaf912a19aa":{
      "scriptId":"u38"},
    "13195ec46a454612a2bba5b2d6ca40dc":{
      "scriptId":"u39"},
    "e7d64761b0824db98f43cadcee3bcc4f":{
      "scriptId":"u40"},
    "c23e91c2e7e947b2abfb9ef9f5b0e554":{
      "scriptId":"u41"},
    "4f8c5b4a1c0c4ba3b43b1ac455448d1d":{
      "scriptId":"u42"},
    "63b4c79e434d45bda90499e961afcb6b":{
      "scriptId":"u43"},
    "36f6860fd7c942e4bd9a8b61ec207a15":{
      "scriptId":"u44"},
    "a9b21636a1aa44c393b96c040076fd1f":{
      "scriptId":"u45"},
    "82975f07cdcf4bb58a341dbc57d81344":{
      "scriptId":"u46"},
    "41ffa23a13bc4811bab6feab38b58af5":{
      "scriptId":"u47"},
    "8f542aed04294d3d8595ddef1176fda6":{
      "scriptId":"u48"},
    "40e7bb45006845fab8631020b4a4bebd":{
      "scriptId":"u49"},
    "baa7cd5a1afc4307a7f3bc73dd2ecf5d":{
      "scriptId":"u50"},
    "e705c3cdacc240d69f19c47c24fc6308":{
      "scriptId":"u51"},
    "c6ea4f384a884e4d8d1353e2934d98fe":{
      "scriptId":"u52"},
    "5c808e2e3dc34d96be365b06f29828a7":{
      "scriptId":"u53"},
    "c3cc23ec3d4f4832afb41504c13cd132":{
      "scriptId":"u54"},
    "b9069125e3544d3da5e80935ebe0f011":{
      "scriptId":"u55"},
    "883482b4cf1c41318ccc4400be93d0ab":{
      "scriptId":"u56"},
    "0dae3c14d0d14579b3e60efd1619fea7":{
      "scriptId":"u57"},
    "b6b6fa6f71ad48e1abe183f68c68b761":{
      "scriptId":"u58"},
    "cea30c028fa540208b42111b1dee20ea":{
      "scriptId":"u59"},
    "4a75c3ed7a38440a936fceb144890be4":{
      "scriptId":"u60"},
    "b47d4a9fa8254037b4f899093d251be3":{
      "scriptId":"u61"},
    "38afba8640c1473ba7e19c0637cb8b51":{
      "scriptId":"u62"},
    "1720820f00e74a5b8456237a0665ac4d":{
      "scriptId":"u63"},
    "877f328e64b84fd5b5b18055fc2d6159":{
      "scriptId":"u64"},
    "e5a9f74fa2034678886d6eafbeeccdce":{
      "scriptId":"u65"},
    "4fb9173f305c431bac853b3f3d7e91ed":{
      "scriptId":"u66"},
    "4e9854e13f0f41129392573edc40af9a":{
      "scriptId":"u67"},
    "d662659bb7fb454fbd58f1d210462aa8":{
      "scriptId":"u68"},
    "536b7c9ec9d548f3aab0c65e93206b31":{
      "scriptId":"u69"},
    "d3d9a1300d064e24a4c88490ed822351":{
      "scriptId":"u70"},
    "0f526b86ebd84ffc81576980db6fb413":{
      "scriptId":"u71"},
    "f18b543c776b4845a30f72745bd40949":{
      "scriptId":"u72"},
    "a800c46a20564ac2b7a3721e1d75b21e":{
      "scriptId":"u73"},
    "51767f7c10d74d91928d373cc82e1213":{
      "scriptId":"u74"},
    "dd3cbb51d1f944f68d5f4d6617c57f78":{
      "scriptId":"u75"},
    "c6a9302ee371473a811d75a1a5cc557f":{
      "scriptId":"u76"},
    "7bc7f73fdb874bb7ab49996bdbac38a2":{
      "scriptId":"u77"},
    "52ae05abf4ad4e03be418a8cb1490a0f":{
      "scriptId":"u78"},
    "4d6367d71c1f40b0b59cc57b79151ff7":{
      "scriptId":"u79"},
    "b377c1572db446dcb734c36e0263bb05":{
      "scriptId":"u80"},
    "89489d14e934437b8b828914c54f8ead":{
      "scriptId":"u81"},
    "a8cccd92efe543709fe7369c50b67d3b":{
      "scriptId":"u82"},
    "72fc30c1b7b346f1804978df78cb31e5":{
      "scriptId":"u83"},
    "93d173cc7dc54aca81bd9651dc5c53a4":{
      "scriptId":"u84"},
    "4bb64c98b5f240ca9962ddecded26c94":{
      "scriptId":"u85"},
    "a93d8dd3a8064a9fb3895f5121e4fecb":{
      "scriptId":"u86"},
    "47a888a17b384d478265248b7b25239e":{
      "scriptId":"u87"},
    "e3c4e20f5a394527b662960b0c40037b":{
      "scriptId":"u88"},
    "9f88094edc234a9888dab33d49388350":{
      "scriptId":"u89"},
    "0a0184dfbed04fca894ef659a9035569":{
      "scriptId":"u90"},
    "149d246469b645d9960b879905ee0653":{
      "scriptId":"u91"},
    "9839e3a710a8431ba890209ebaaa0059":{
      "scriptId":"u92"},
    "1f9a452b65ff48a19294588161687f5e":{
      "scriptId":"u93"},
    "adbaf93940604ccbb73a81beb4f5bf0b":{
      "scriptId":"u94"},
    "d8a96bab62914802a9502a26dbe4c55b":{
      "scriptId":"u95"},
    "bd3cee38f90d402893c4a82e2b9b3b16":{
      "scriptId":"u96"},
    "fef38b88c8044d819f2a4fdc190e9827":{
      "scriptId":"u97"},
    "fd56f77d206849359c416614453fdf86":{
      "scriptId":"u98"},
    "a04d675e256d4d2883ed734fa09d07d2":{
      "scriptId":"u99"},
    "1757529520204b70937730a614761e02":{
      "scriptId":"u100"},
    "1a1adda2c676407bbe35f4eda4ac699a":{
      "scriptId":"u101"},
    "1197a4dc2f6a4e498cfae36be4039c0f":{
      "scriptId":"u102"},
    "499c4cf46c6b4cd3bb65cf905082a1e0":{
      "scriptId":"u103"},
    "d367b75db7b7439cb54bc2d7002313f2":{
      "scriptId":"u104"},
    "59a638cd496f4caabf18659211125eea":{
      "scriptId":"u105"},
    "e1c2bf4e200143f092dbc165d946f0f1":{
      "scriptId":"u106"},
    "fa9ac6a8b44d4024b8c52c4e9cd4833a":{
      "scriptId":"u107"},
    "fee7455a385c418f8d41d4b95554db71":{
      "scriptId":"u108"},
    "c355e48719494ddb82c1fe91f6494671":{
      "scriptId":"u109"},
    "86a5639ac2234afeb26856cc00272ad9":{
      "scriptId":"u110"},
    "6d6a96f45e7f418d9d7f307d78675ea2":{
      "scriptId":"u111"},
    "21fd7802dca64450a879caf1a5f3ad05":{
      "scriptId":"u112"},
    "eaa5d2b8afcd477a89832029bf93a1e5":{
      "scriptId":"u113"},
    "b61851d69bc542b3be5111b334e63a12":{
      "scriptId":"u114"},
    "cc7ab4d2252a4300a583945fa78daf66":{
      "scriptId":"u115"},
    "bcbdd49fef15491095642dde397b25b5":{
      "scriptId":"u116"},
    "78ceaafc3f90477b87acf52a1d8dde27":{
      "scriptId":"u117"},
    "3674b2f8de2f42a39643553516161c99":{
      "scriptId":"u118"},
    "865529dddaf2476b88ec4c405d727140":{
      "scriptId":"u119"},
    "ff8f016b6aaa4fdabc14f04335acd393":{
      "scriptId":"u120"},
    "aa409bf382314eac8ec43627c11f68a4":{
      "scriptId":"u121"},
    "2afba409878f4ee59ab3c891f7b783d2":{
      "scriptId":"u122"},
    "e3991876cc584e6b9d5b2815b19d2568":{
      "scriptId":"u123"},
    "6b7fce11cf8b4802afc5dfc8ee9cb488":{
      "scriptId":"u124"}}});