$axure.loadCurrentPage({
  "url":"农旅产品详情.html",
  "generationDate":new Date(1501233922566.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba25d7ab4f7e4224869c487741d00b61",
    "type":"Axure:Page",
    "name":"农旅产品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b22112a07c9431e853d410e476e6a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4f12348a5a4755ad2d3ab165236d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u13.png"}},
{
          "id":"c9352d30998f480399d9a1df1af63aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e16382e59d4ec2af48f96a78601490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"872640187cde461995c12c3310c50370",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f264fdd782a640e8a051e29c9e1b4538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/平台简介/u4.png"}},
{
          "id":"5d461c2f6d804383a230526066d1af49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":133,
              "y":9},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f07622d5d71432b9a6ed0a168a2cbaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":133,
                  "y":9},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7b118934fe14d9ab5239efbce7d0154",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":354,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fe1291e9a1400b8c33ba0fe50605e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":354,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"1095b6aaa09a4e79b08c8cb1c8292c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":354,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc96eba7b7e6441bae995261472d00ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":354,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"c46432eebce64b69a48af648b4a0350e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":354,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba490fe420e48898793bda2c8daa956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":354,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"ac8d0a9515fd49b29df22399721702c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":373,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc31e2ba88e2436481da83af76cc2d9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":373,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情/u14.jpg"}},
{
          "id":"508646b57bdc4d0f870a0cbda8a2f019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":280},
            "size":{
              "width":373,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd5e34b904c49f586ec2ea21c9e5239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":280},
                "size":{
                  "width":373,
                  "height":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情/u16.png"}},
{
          "id":"3bdadf7945b64ea39e03c5d7fa355704",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":303},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u56_line.png"}},
{
          "id":"16882a03adbc42498bbe79586f3d05b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":291},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fab233f02d3f447c9fac4275528b3760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":291},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0d73aa0c2334190ba9e16dd229ec632",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":430},
            "size":{
              "width":373,
              "height":181},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601e37cdb5344c94b60fc5ba21b0fcf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":430},
                "size":{
                  "width":373,
                  "height":181},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情/u21.png"}},
{
          "id":"415e049068cb4ef5be1e5772a44c7f68",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":460},
            "size":{
              "width":375,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/主页/u56_line.png"}},
{
          "id":"d99648621d8c4b8e91eb346c6aec293b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":444},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ea1648a33e410b97622f34fc4067fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":444},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ed561fc341d47c29c239ba1bad6fe9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":170},
            "size":{
              "width":373,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21b03ecce4d44b678d0bb8a6fcf4266b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":170},
                "size":{
                  "width":373,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情/u26.png"}},
{
          "id":"79147a52bf2443b5b6ccf4eb9c19ac83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":19,
              "y":177},
            "size":{
              "width":349,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ce76bd9738a4126bfeeeaa4048aa3e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":19,
                  "y":177},
                "size":{
                  "width":349,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e109bed43df4768bc96acdb6dfa60ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":19,
              "y":200},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d36561b584a4c00857333e7125f9d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":200},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fa10afc44454a79a2d2b7471b3d9355",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":302,
              "y":200},
            "size":{
              "width":52,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bbccc085b7947528443dfc146dfddc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":200},
                "size":{
                  "width":52,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cda810639d7248e084fee9910f2e5ef8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":373,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff4bc17ca8ef4bfeb45311843bafeccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":373,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品列表",
                      "target":{
                        "targetType":"page",
                        "url":"商品列表_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/农场详情/u62.png"}},
{
          "id":"2f23350efc13467ba42420e836c5b762",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":242},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"789e4fd1a11c43cdab168c5dd8943099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":242},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9beaeb8c7844402586cbc68bc6a8cbdf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":234},
            "size":{
              "width":30,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0176f9495cc453583e35a22213306c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":234},
                "size":{
                  "width":30,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"247fa7a3812b4f7b86d6a7c75f1de835",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":236},
            "size":{
              "width":29,
              "height":29},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dd4f77a65e48fcb1a1637e349eb321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":236},
                "size":{
                  "width":29,
                  "height":29},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情/u40.png"}},
{
          "id":"6e50dd6e5e824e73a721e57defb0ad91",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":375,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农场详情",
                      "target":{
                        "targetType":"page",
                        "url":"农场详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d3db32bacbb14e2f8ce129a09a276a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":473},
            "size":{
              "width":360,
              "height":397}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aabc5390b8a648dc9b84438a8156209e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":473},
                "size":{
                  "width":360,
                  "height":397}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c28592b88954782aff9c300abb8e44e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":327},
            "size":{
              "width":338,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9d4cd38cad46ed9cb79ba429548f2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":327},
                "size":{
                  "width":338,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be536668f8214536bc45b42c3e0450a6",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a4f7aa4e19f641e8b4993cfeb29fc1d6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fd3d1d584f89425a875fe53a6e5ccf98",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":375,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c77c0443d9e3434e8e1dfa687e81d699",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":375,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品列表/u107.png"}},
{
                  "id":"2c7f38d48cd04868a034ad8d4dd5377b",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":15},
                    "size":{
                      "width":79,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23d1294ea53b4a949181e0be3250f22e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":15},
                        "size":{
                          "width":79,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"87f67b9f575c49c1b2b77cbcd47d666a",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":0},
                    "size":{
                      "width":105,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b7470335b3349268edd928af8583437",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":0},
                        "size":{
                          "width":105,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 确认预约时间",
                              "target":{
                                "targetType":"page",
                                "url":"确认预约时间.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品列表/u119.png"}},
{
                  "id":"e2bf6cb02f154ab4b766d4be385d22c7",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"10px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":23},
                    "size":{
                      "width":43,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7863a2233bc6461691a1ee8f36a5d27f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"10px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":23},
                        "size":{
                          "width":43,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b3514b79a9cc4714a92821f258c2aad9",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":24},
                    "size":{
                      "width":49,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/农旅产品详情/u56_line.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "5b22112a07c9431e853d410e476e6a60":{
      "scriptId":"u0"},
    "6c4f12348a5a4755ad2d3ab165236d46":{
      "scriptId":"u1"},
    "c9352d30998f480399d9a1df1af63aa1":{
      "scriptId":"u2"},
    "43e16382e59d4ec2af48f96a78601490":{
      "scriptId":"u3"},
    "872640187cde461995c12c3310c50370":{
      "scriptId":"u4"},
    "f264fdd782a640e8a051e29c9e1b4538":{
      "scriptId":"u5"},
    "5d461c2f6d804383a230526066d1af49":{
      "scriptId":"u6"},
    "7f07622d5d71432b9a6ed0a168a2cbaa":{
      "scriptId":"u7"},
    "b7b118934fe14d9ab5239efbce7d0154":{
      "scriptId":"u8"},
    "e9fe1291e9a1400b8c33ba0fe50605e6":{
      "scriptId":"u9"},
    "1095b6aaa09a4e79b08c8cb1c8292c95":{
      "scriptId":"u10"},
    "bc96eba7b7e6441bae995261472d00ce":{
      "scriptId":"u11"},
    "c46432eebce64b69a48af648b4a0350e":{
      "scriptId":"u12"},
    "3ba490fe420e48898793bda2c8daa956":{
      "scriptId":"u13"},
    "ac8d0a9515fd49b29df22399721702c1":{
      "scriptId":"u14"},
    "dc31e2ba88e2436481da83af76cc2d9a":{
      "scriptId":"u15"},
    "508646b57bdc4d0f870a0cbda8a2f019":{
      "scriptId":"u16"},
    "6bd5e34b904c49f586ec2ea21c9e5239":{
      "scriptId":"u17"},
    "3bdadf7945b64ea39e03c5d7fa355704":{
      "scriptId":"u18"},
    "16882a03adbc42498bbe79586f3d05b9":{
      "scriptId":"u19"},
    "fab233f02d3f447c9fac4275528b3760":{
      "scriptId":"u20"},
    "a0d73aa0c2334190ba9e16dd229ec632":{
      "scriptId":"u21"},
    "601e37cdb5344c94b60fc5ba21b0fcf8":{
      "scriptId":"u22"},
    "415e049068cb4ef5be1e5772a44c7f68":{
      "scriptId":"u23"},
    "d99648621d8c4b8e91eb346c6aec293b":{
      "scriptId":"u24"},
    "20ea1648a33e410b97622f34fc4067fe":{
      "scriptId":"u25"},
    "0ed561fc341d47c29c239ba1bad6fe9f":{
      "scriptId":"u26"},
    "21b03ecce4d44b678d0bb8a6fcf4266b":{
      "scriptId":"u27"},
    "79147a52bf2443b5b6ccf4eb9c19ac83":{
      "scriptId":"u28"},
    "9ce76bd9738a4126bfeeeaa4048aa3e5":{
      "scriptId":"u29"},
    "8e109bed43df4768bc96acdb6dfa60ff":{
      "scriptId":"u30"},
    "7d36561b584a4c00857333e7125f9d8d":{
      "scriptId":"u31"},
    "1fa10afc44454a79a2d2b7471b3d9355":{
      "scriptId":"u32"},
    "4bbccc085b7947528443dfc146dfddc0":{
      "scriptId":"u33"},
    "cda810639d7248e084fee9910f2e5ef8":{
      "scriptId":"u34"},
    "ff4bc17ca8ef4bfeb45311843bafeccf":{
      "scriptId":"u35"},
    "2f23350efc13467ba42420e836c5b762":{
      "scriptId":"u36"},
    "789e4fd1a11c43cdab168c5dd8943099":{
      "scriptId":"u37"},
    "9beaeb8c7844402586cbc68bc6a8cbdf":{
      "scriptId":"u38"},
    "d0176f9495cc453583e35a22213306c9":{
      "scriptId":"u39"},
    "247fa7a3812b4f7b86d6a7c75f1de835":{
      "scriptId":"u40"},
    "03dd4f77a65e48fcb1a1637e349eb321":{
      "scriptId":"u41"},
    "6e50dd6e5e824e73a721e57defb0ad91":{
      "scriptId":"u42"},
    "d3db32bacbb14e2f8ce129a09a276a2e":{
      "scriptId":"u43"},
    "aabc5390b8a648dc9b84438a8156209e":{
      "scriptId":"u44"},
    "2c28592b88954782aff9c300abb8e44e":{
      "scriptId":"u45"},
    "4f9d4cd38cad46ed9cb79ba429548f2e":{
      "scriptId":"u46"},
    "be536668f8214536bc45b42c3e0450a6":{
      "scriptId":"u47"},
    "fd3d1d584f89425a875fe53a6e5ccf98":{
      "scriptId":"u48"},
    "c77c0443d9e3434e8e1dfa687e81d699":{
      "scriptId":"u49"},
    "2c7f38d48cd04868a034ad8d4dd5377b":{
      "scriptId":"u50"},
    "23d1294ea53b4a949181e0be3250f22e":{
      "scriptId":"u51"},
    "87f67b9f575c49c1b2b77cbcd47d666a":{
      "scriptId":"u52"},
    "7b7470335b3349268edd928af8583437":{
      "scriptId":"u53"},
    "e2bf6cb02f154ab4b766d4be385d22c7":{
      "scriptId":"u54"},
    "7863a2233bc6461691a1ee8f36a5d27f":{
      "scriptId":"u55"},
    "b3514b79a9cc4714a92821f258c2aad9":{
      "scriptId":"u56"}}});