$axure.loadCurrentPage({
  "url":"3_3充值优惠.html",
  "generationDate":new Date(1515057182282.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"5c86ecc3bf604b8cbddac604a843dedc",
    "type":"Axure:Page",
    "name":"3.3充值优惠",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8eadf3b433f6426abea08c0fc93dd7b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":810}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fa1613d4c0a4d85840d44e7a0d9490d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":810}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_3充值优惠/u0.png"}},
{
          "id":"aefffd9ef0cd43a8a49c6dbfe2200ea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1f6b81d4e534d598cb0abb760e2d717",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"7fe12ba0412e4dd9bae1916344bbeb8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c454b4abc07043c68b5e58a42a594ee3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"3f5837fea36e45ef9d40c60c34bbf7e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f494623bc144ff6a888b33230879af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cd69a22d3ec414fa766a8baecf6a560",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":163},
            "size":{
              "width":360,
              "height":255}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5567df3b934f31a7677d8951c0a89f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":163},
                "size":{
                  "width":360,
                  "height":255}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_3充值优惠/u8.png"}},
{
          "id":"a1352b3f6a124a4e833d97f7c091c98d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":12,
              "y":190},
            "size":{
              "width":336,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d761f336a614d7abeaf7746acee10a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":190},
                "size":{
                  "width":336,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8272722634a84d748e96291c13e5bfe7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":750},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ba3a11e8b8794b4390274790e5309683",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ee19f4d30403470b9a3b7eb1880a30d4",
                  "label":"",
                  "parentDynamicPanel":"8272722634a84d748e96291c13e5bfe7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6eec4b32bcdd454f8781fe4b965ef4e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8272722634a84d748e96291c13e5bfe7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":360,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/0_0主页/top_u44.png"}}]}]},
{
          "id":"022da9039c714e5ca67db95b46b0c267",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":360,
              "height":123}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb160800988484495be8dd518c493fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":360,
                  "height":123}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_8我的账户/u60.png"}},
{
          "id":"8838c9c98926495fa4a5ea9314b4be67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":12,
              "y":240},
            "size":{
              "width":336,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c0df2f70d354de492e3845bce2dd322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":240},
                "size":{
                  "width":336,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ec45f09273c4560a81dc0a1fccccb22",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":12,
              "y":310},
            "size":{
              "width":336,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4397531b1e9453797f6049624b2624d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":310},
                "size":{
                  "width":336,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15f7bcb5431e457ca2970e0a73c738b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":12,
              "y":364},
            "size":{
              "width":336,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b071c579f68d4ed0b76b5a8fc9928e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":364},
                "size":{
                  "width":336,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dbbf6ee7cdd4128b4079cb8ad1c26f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":298,
              "y":280},
            "size":{
              "width":50,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4363d59ddf9c4df0994c2edb445ea948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":298,
                  "y":280},
                "size":{
                  "width":50,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_3充值优惠/u23.png"}},
{
          "id":"d1a0db6ede734b89ba6b3fa46ecfc487",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":440},
            "size":{
              "width":360,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ca792aee874176afe65c0ca6459ef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":440},
                "size":{
                  "width":360,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_3充值优惠/u25.png"}},
{
          "id":"25fb1d486b40410fbd8772b94732bf13",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":119.5,
              "y":456},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b10201a64d4b4097c32eb3440e8caa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":119.5,
                  "y":456},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8eadf3b433f6426abea08c0fc93dd7b4":{
      "scriptId":"u0"},
    "5fa1613d4c0a4d85840d44e7a0d9490d":{
      "scriptId":"u1"},
    "aefffd9ef0cd43a8a49c6dbfe2200ea2":{
      "scriptId":"u2"},
    "b1f6b81d4e534d598cb0abb760e2d717":{
      "scriptId":"u3"},
    "7fe12ba0412e4dd9bae1916344bbeb8b":{
      "scriptId":"u4"},
    "c454b4abc07043c68b5e58a42a594ee3":{
      "scriptId":"u5"},
    "3f5837fea36e45ef9d40c60c34bbf7e4":{
      "scriptId":"u6"},
    "8f494623bc144ff6a888b33230879af0":{
      "scriptId":"u7"},
    "4cd69a22d3ec414fa766a8baecf6a560":{
      "scriptId":"u8"},
    "bf5567df3b934f31a7677d8951c0a89f":{
      "scriptId":"u9"},
    "a1352b3f6a124a4e833d97f7c091c98d":{
      "scriptId":"u10"},
    "0d761f336a614d7abeaf7746acee10a3":{
      "scriptId":"u11"},
    "8272722634a84d748e96291c13e5bfe7":{
      "scriptId":"u12"},
    "ee19f4d30403470b9a3b7eb1880a30d4":{
      "scriptId":"u13"},
    "6eec4b32bcdd454f8781fe4b965ef4e1":{
      "scriptId":"u14"},
    "022da9039c714e5ca67db95b46b0c267":{
      "scriptId":"u15"},
    "ccb160800988484495be8dd518c493fe":{
      "scriptId":"u16"},
    "8838c9c98926495fa4a5ea9314b4be67":{
      "scriptId":"u17"},
    "9c0df2f70d354de492e3845bce2dd322":{
      "scriptId":"u18"},
    "7ec45f09273c4560a81dc0a1fccccb22":{
      "scriptId":"u19"},
    "f4397531b1e9453797f6049624b2624d":{
      "scriptId":"u20"},
    "15f7bcb5431e457ca2970e0a73c738b1":{
      "scriptId":"u21"},
    "b071c579f68d4ed0b76b5a8fc9928e47":{
      "scriptId":"u22"},
    "8dbbf6ee7cdd4128b4079cb8ad1c26f6":{
      "scriptId":"u23"},
    "4363d59ddf9c4df0994c2edb445ea948":{
      "scriptId":"u24"},
    "d1a0db6ede734b89ba6b3fa46ecfc487":{
      "scriptId":"u25"},
    "92ca792aee874176afe65c0ca6459ef2":{
      "scriptId":"u26"},
    "25fb1d486b40410fbd8772b94732bf13":{
      "scriptId":"u27"},
    "88b10201a64d4b4097c32eb3440e8caa":{
      "scriptId":"u28"}}});