$axure.loadCurrentPage({
  "url":"个人中心主页_1.html",
  "generationDate":new Date(1501752148306.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7da0bb4ffbfd4610a7b4cb9982e7a9a6",
    "type":"Axure:Page",
    "name":"个人中心主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2b74988362eb421a983141ab15d9ab99",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"466e11e1751e47a9ae9e21ab4a93bbcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表_1/配送设置面板_u132.png"}},
{
          "id":"52ded57945ac4f3ab04a24b9465140a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b786f45eb9d4d44b73f56b0be9dd8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u2.png"}},
{
          "id":"7368f1f132004b61b448f08aa63ad3e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":8},
            "size":{
              "width":23,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd4e1c08e470404599fa5b6d1c39ea6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":8},
                "size":{
                  "width":23,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u4.png"}},
{
          "id":"442d78d8806145e2bdc8dd78f05ef587",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":8},
            "size":{
              "width":22,
              "height":22},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3b4cb4edca045129e984a90f5c3c84c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":8},
                "size":{
                  "width":22,
                  "height":22},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u6.png"}},
{
          "id":"1fba798fdb3f461da1dad7ad1033bf3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":130,
              "y":54},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4a79f6633d34ff4bfe3351804090769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":130,
                  "y":54},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93e6b694da3243f4bb686725840df812",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":130,
              "y":88},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fb9b3b9cb5c4a538c0f803fa7d59ebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":88},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10c5fdea972c45678fd0ad3fe9d466de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":130,
              "y":106},
            "size":{
              "width":86,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca3212a08af64d86bc0b333420c40fe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":106},
                "size":{
                  "width":86,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af06dd1c3b134fbc9a47b6aa0161b276",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":79},
            "size":{
              "width":23,
              "height":23},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"823c5f1272584397be69088381197a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":79},
                "size":{
                  "width":23,
                  "height":23},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"178572379c4f4713a9dbcceeb83806e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":160},
            "size":{
              "width":92,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0ccbca0e3242059ce25c0afb458cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":160},
                "size":{
                  "width":92,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u16.png"}},
{
          "id":"42939e0d934a4cdeb70f4d41ced31c71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":22,
              "y":200},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7747a6250f5843d38ed496c7804cba19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":22,
                  "y":200},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3b7a51b378a4a86a3da877db9debc42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":160},
            "size":{
              "width":92,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab5087611984486bae33464369aa0cbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":160},
                "size":{
                  "width":92,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u16.png"}},
{
          "id":"08a0e63c1de54247aa79bf62b6c42c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":116,
              "y":200},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1386a721d3410cbae36cb1f37d6614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":116,
                  "y":200},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"422dbfec849e4e399ee8b51735f52a53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":160},
            "size":{
              "width":92,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d5eea4ffb7f428981a63ae39bfce4fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":177,
                  "y":160},
                "size":{
                  "width":92,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u16.png"}},
{
          "id":"f96516a4cd7447239e82c419ea742bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":199,
              "y":200},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5fbe71341847c98a7f5259b9e73eee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":199,
                  "y":200},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd7153e67857428dbc23d719704defdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":160},
            "size":{
              "width":92,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3ae33d77a3e4329b57cf098ca494ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":160},
                "size":{
                  "width":92,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u16.png"}},
{
          "id":"4aef533a185743709002c94994a512f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":291,
              "y":200},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b676b7861df4b259dedb56e0e500242",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":291,
                  "y":200},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc99173e89624deea2b498be12669879",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":121,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"959c57ee0bbb44a4a788faa89208c231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":121,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u32.png"}},
{
          "id":"5eb0d3f58f684101be88591f484f4668",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":304},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9c5fa3485cd4450a5be1a4493552fab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":304},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d6d72c64f294b4fbdd70cf8b5870203",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":230},
            "size":{
              "width":121,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ea48ace39c4c7ba5bc04a457b1653f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":230},
                "size":{
                  "width":121,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u32.png"}},
{
          "id":"59c320822d6e49f98e68e1d8a67f8c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":304},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f21413116045a5b87a49002905e23b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":304},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eba434340cea48ae9eac724bb2027473",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":230},
            "size":{
              "width":122,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a29e2870e0d94fc6833a3f61e944a630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":230},
                "size":{
                  "width":122,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u40.png"}},
{
          "id":"2057c2b6f16e4f29b17986a5a70cbb9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":304},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"551e56325a5a4f6888c02f00993aad55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":304},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25753fdb19bd44d497542873af3927ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":329},
            "size":{
              "width":121,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8046faebbdb1468b9b1313a3818a6394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":329},
                "size":{
                  "width":121,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u32.png"}},
{
          "id":"6659f9eab2c142a3bfef4ae5c98381da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":403},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b88e086864e4fa699551b4e1bc307e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":403},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"283d7e77844f4352acef43d49b36a4d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":329},
            "size":{
              "width":121,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f883c07b4c141ddb9d19b853082fe1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":329},
                "size":{
                  "width":121,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u32.png"}},
{
          "id":"ae1999ad87614e3da14202a4317b28d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":403},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6dd1fd45a0b401bbe5f549356aa4bf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":403},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b5eabe7f3b04cc784afaa426440c258",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":329},
            "size":{
              "width":122,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27258067053942b182a6e49d72fbcd97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":329},
                "size":{
                  "width":122,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u40.png"}},
{
          "id":"9e33a2cc167b4a92ab3b4dd0a1ad1f12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":403},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5eab95bbe794edfb913169337ff7b3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":403},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa51975d28de4bebb0af4a7125d8d509",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":220,
              "y":52},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b66408cccdbe4d839bfdabb1281f6133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":220,
                  "y":52},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u56.png"}},
{
          "id":"e09be58156844e7e9454e9e047e405f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":50},
            "size":{
              "width":80,
              "height":80},
            "cornerRadiusTopLeft":"80"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d95239d5a24e9d8ed119992487c1eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":50},
                "size":{
                  "width":80,
                  "height":80},
                "cornerRadiusTopLeft":"80"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页_1/u58.png"}},
{
          "id":"358b67b5d57d4647a65fb1128c42df2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":50},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"265bf74c771145de9e8bba3801e4dad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":50},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u60.png"}},
{
          "id":"74ade40850594b51b94fc0a9f7cd8977",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":166},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"178c276cc3034f22a86b40e5019129fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":166},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u62.png"}},
{
          "id":"068ca2da4b90451ab45d4fc5cc523c18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":166},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b99ad3f4c7c468f9bbaaac379a8386c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":166},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u64.png"}},
{
          "id":"a903998863634e42a32356cddaae98eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":302,
              "y":169},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e924a09d0e4669ace1132e1b7de28e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":302,
                  "y":169},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u66.png"}},
{
          "id":"ac174a772887445fa307f986d5cc8da4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":166},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"194e885c0fb64ee2889cc3d35506ab48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":166},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u68.png"}},
{
          "id":"44dc06c0e9e244dd8f5b8a4f386b4cb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":343},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf60782f2ddf47c5af48ab5a978664bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":343},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u70.png"}},
{
          "id":"40118e06113a4b2ea0c4af816a6cf518",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":155.5,
              "y":244},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76fd90c029142b0ab145736ffb1b83e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155.5,
                  "y":244},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u72.png"}},
{
          "id":"70750f0c27854443a3b142b5c7b0ba31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":273.5,
              "y":244},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6637449a66404a3f8851630f83019114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":273.5,
                  "y":244},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u74.png"}},
{
          "id":"6dd2c9e92e0e46ab9bfe5393cb93761a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40.5,
              "y":249},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38fb4ddee0f6415a95b6952048e387d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40.5,
                  "y":249},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u76.png"}},
{
          "id":"0b946b4fbe314c0bae50e0b9af11842d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":343},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d15dafa8ed84e238cbdac6718b4f8c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":343},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u78.png"}},
{
          "id":"4cc18f15bf374ad5be1f37331b2d6611",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160.5,
              "y":348},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e180247010e4a9d8104a1f86ea33198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160.5,
                  "y":348},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心主页/u80.png"}},
{
          "id":"20a5fe669cce426c872a3b3466ecf0fc",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":627},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e81ef5b5647c4ea8a1d1066bed2a217b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2f066d3300bb4edf9aa58fb76a894984",
                  "label":"",
                  "parentDynamicPanel":"20a5fe669cce426c872a3b3466ecf0fc",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "masterId":"864967e889e541e9958747926389b524"}]}]}]}},
  "masters":{
    "864967e889e541e9958747926389b524":{
      "packageId":"864967e889e541e9958747926389b524",
      "type":"Axure:Master",
      "name":"底部菜单0726",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d3980e768e434d6e8006717cfc1027d7",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"33e17ce2012b4cbda3b4e022b57a30db",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"5302c9f29ec84d49b96b0cdde12c2d96",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":360,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5ce46e8bf0f1475fb3b3b7da2d61bfd4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":360,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_0727/u134.png"}},
{
                    "id":"dbd6a5f83af64ab191b7f078d53db2df",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":39,
                        "y":24},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c081ce32660247bfb9c77e35f3c9f8df",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":39,
                            "y":24},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"f9456264ba204c659a73730ac5f9be10",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":110,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"38b51ec901e940038aa1d61e70cebbae",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":110,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"cd39e767b2cb408a81a6c3721408db6b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":191,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"45450782be8a4066b51da07d94fc70ca",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":191,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"0d3829ac6ae645118ae248d779627e03",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":277,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1e699b0485d842fda37a4804fbb1a443",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":277,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"537a1d54bb024094a5238b61a93b1b3b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":39,
                        "y":2},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e7e66d880a8948f286fa211dbac91888",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":39,
                            "y":2},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u36.png"}},
{
                    "id":"b7f155757800405f98f3a2e19819a135",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":288,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"de6f0a9691d847e8be63625ea68a2fad",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":288,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u42.png"}},
{
                    "id":"806e77a021e44ddb9e4b2ec499bc008e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":118,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d7fcb44076144736abafdcb00a145142",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":118,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_0727/u148.png"}},
{
                    "id":"0855a01c3bf8421f852d6f1786340508",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":199,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9b3f8f00dd784297b8062985a5c291b6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":199,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_0727/u150.png"}},
{
                    "id":"b01444f95aeb4686a41a1b02e9924322",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主页(安卓)",
                                "target":{
                                  "targetType":"page",
                                  "url":"主页_安卓_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"c571f4e1ff0749f4b80729d3b1cad885",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":267.5,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"5546bbd9a15544b0adcca0215bcedee1",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":98,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主题农旅",
                                "target":{
                                  "targetType":"page",
                                  "url":"主题农旅.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"690a1cd387b244b5b2acab4956a49b1e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":179,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 会员特权",
                                "target":{
                                  "targetType":"page",
                                  "url":"会员特权.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}]}]}}},
  "objectPaths":{
    "2b74988362eb421a983141ab15d9ab99":{
      "scriptId":"u0"},
    "466e11e1751e47a9ae9e21ab4a93bbcf":{
      "scriptId":"u1"},
    "52ded57945ac4f3ab04a24b9465140a7":{
      "scriptId":"u2"},
    "5b786f45eb9d4d44b73f56b0be9dd8b2":{
      "scriptId":"u3"},
    "7368f1f132004b61b448f08aa63ad3e5":{
      "scriptId":"u4"},
    "dd4e1c08e470404599fa5b6d1c39ea6d":{
      "scriptId":"u5"},
    "442d78d8806145e2bdc8dd78f05ef587":{
      "scriptId":"u6"},
    "f3b4cb4edca045129e984a90f5c3c84c":{
      "scriptId":"u7"},
    "1fba798fdb3f461da1dad7ad1033bf3e":{
      "scriptId":"u8"},
    "c4a79f6633d34ff4bfe3351804090769":{
      "scriptId":"u9"},
    "93e6b694da3243f4bb686725840df812":{
      "scriptId":"u10"},
    "3fb9b3b9cb5c4a538c0f803fa7d59ebb":{
      "scriptId":"u11"},
    "10c5fdea972c45678fd0ad3fe9d466de":{
      "scriptId":"u12"},
    "ca3212a08af64d86bc0b333420c40fe7":{
      "scriptId":"u13"},
    "af06dd1c3b134fbc9a47b6aa0161b276":{
      "scriptId":"u14"},
    "823c5f1272584397be69088381197a2f":{
      "scriptId":"u15"},
    "178572379c4f4713a9dbcceeb83806e0":{
      "scriptId":"u16"},
    "4f0ccbca0e3242059ce25c0afb458cf2":{
      "scriptId":"u17"},
    "42939e0d934a4cdeb70f4d41ced31c71":{
      "scriptId":"u18"},
    "7747a6250f5843d38ed496c7804cba19":{
      "scriptId":"u19"},
    "b3b7a51b378a4a86a3da877db9debc42":{
      "scriptId":"u20"},
    "ab5087611984486bae33464369aa0cbd":{
      "scriptId":"u21"},
    "08a0e63c1de54247aa79bf62b6c42c4d":{
      "scriptId":"u22"},
    "2f1386a721d3410cbae36cb1f37d6614":{
      "scriptId":"u23"},
    "422dbfec849e4e399ee8b51735f52a53":{
      "scriptId":"u24"},
    "7d5eea4ffb7f428981a63ae39bfce4fc":{
      "scriptId":"u25"},
    "f96516a4cd7447239e82c419ea742bc8":{
      "scriptId":"u26"},
    "bf5fbe71341847c98a7f5259b9e73eee":{
      "scriptId":"u27"},
    "dd7153e67857428dbc23d719704defdf":{
      "scriptId":"u28"},
    "a3ae33d77a3e4329b57cf098ca494ec0":{
      "scriptId":"u29"},
    "4aef533a185743709002c94994a512f6":{
      "scriptId":"u30"},
    "1b676b7861df4b259dedb56e0e500242":{
      "scriptId":"u31"},
    "cc99173e89624deea2b498be12669879":{
      "scriptId":"u32"},
    "959c57ee0bbb44a4a788faa89208c231":{
      "scriptId":"u33"},
    "5eb0d3f58f684101be88591f484f4668":{
      "scriptId":"u34"},
    "a9c5fa3485cd4450a5be1a4493552fab":{
      "scriptId":"u35"},
    "1d6d72c64f294b4fbdd70cf8b5870203":{
      "scriptId":"u36"},
    "f6ea48ace39c4c7ba5bc04a457b1653f":{
      "scriptId":"u37"},
    "59c320822d6e49f98e68e1d8a67f8c0b":{
      "scriptId":"u38"},
    "54f21413116045a5b87a49002905e23b":{
      "scriptId":"u39"},
    "eba434340cea48ae9eac724bb2027473":{
      "scriptId":"u40"},
    "a29e2870e0d94fc6833a3f61e944a630":{
      "scriptId":"u41"},
    "2057c2b6f16e4f29b17986a5a70cbb9a":{
      "scriptId":"u42"},
    "551e56325a5a4f6888c02f00993aad55":{
      "scriptId":"u43"},
    "25753fdb19bd44d497542873af3927ac":{
      "scriptId":"u44"},
    "8046faebbdb1468b9b1313a3818a6394":{
      "scriptId":"u45"},
    "6659f9eab2c142a3bfef4ae5c98381da":{
      "scriptId":"u46"},
    "4b88e086864e4fa699551b4e1bc307e5":{
      "scriptId":"u47"},
    "283d7e77844f4352acef43d49b36a4d9":{
      "scriptId":"u48"},
    "1f883c07b4c141ddb9d19b853082fe1c":{
      "scriptId":"u49"},
    "ae1999ad87614e3da14202a4317b28d6":{
      "scriptId":"u50"},
    "b6dd1fd45a0b401bbe5f549356aa4bf1":{
      "scriptId":"u51"},
    "2b5eabe7f3b04cc784afaa426440c258":{
      "scriptId":"u52"},
    "27258067053942b182a6e49d72fbcd97":{
      "scriptId":"u53"},
    "9e33a2cc167b4a92ab3b4dd0a1ad1f12":{
      "scriptId":"u54"},
    "c5eab95bbe794edfb913169337ff7b3c":{
      "scriptId":"u55"},
    "aa51975d28de4bebb0af4a7125d8d509":{
      "scriptId":"u56"},
    "b66408cccdbe4d839bfdabb1281f6133":{
      "scriptId":"u57"},
    "e09be58156844e7e9454e9e047e405f7":{
      "scriptId":"u58"},
    "e4d95239d5a24e9d8ed119992487c1eb":{
      "scriptId":"u59"},
    "358b67b5d57d4647a65fb1128c42df2a":{
      "scriptId":"u60"},
    "265bf74c771145de9e8bba3801e4dad1":{
      "scriptId":"u61"},
    "74ade40850594b51b94fc0a9f7cd8977":{
      "scriptId":"u62"},
    "178c276cc3034f22a86b40e5019129fc":{
      "scriptId":"u63"},
    "068ca2da4b90451ab45d4fc5cc523c18":{
      "scriptId":"u64"},
    "7b99ad3f4c7c468f9bbaaac379a8386c":{
      "scriptId":"u65"},
    "a903998863634e42a32356cddaae98eb":{
      "scriptId":"u66"},
    "31e924a09d0e4669ace1132e1b7de28e":{
      "scriptId":"u67"},
    "ac174a772887445fa307f986d5cc8da4":{
      "scriptId":"u68"},
    "194e885c0fb64ee2889cc3d35506ab48":{
      "scriptId":"u69"},
    "44dc06c0e9e244dd8f5b8a4f386b4cb6":{
      "scriptId":"u70"},
    "cf60782f2ddf47c5af48ab5a978664bc":{
      "scriptId":"u71"},
    "40118e06113a4b2ea0c4af816a6cf518":{
      "scriptId":"u72"},
    "c76fd90c029142b0ab145736ffb1b83e":{
      "scriptId":"u73"},
    "70750f0c27854443a3b142b5c7b0ba31":{
      "scriptId":"u74"},
    "6637449a66404a3f8851630f83019114":{
      "scriptId":"u75"},
    "6dd2c9e92e0e46ab9bfe5393cb93761a":{
      "scriptId":"u76"},
    "38fb4ddee0f6415a95b6952048e387d2":{
      "scriptId":"u77"},
    "0b946b4fbe314c0bae50e0b9af11842d":{
      "scriptId":"u78"},
    "0d15dafa8ed84e238cbdac6718b4f8c5":{
      "scriptId":"u79"},
    "4cc18f15bf374ad5be1f37331b2d6611":{
      "scriptId":"u80"},
    "2e180247010e4a9d8104a1f86ea33198":{
      "scriptId":"u81"},
    "20a5fe669cce426c872a3b3466ecf0fc":{
      "scriptId":"u82"},
    "2f066d3300bb4edf9aa58fb76a894984":{
      "scriptId":"u83",
      "d3980e768e434d6e8006717cfc1027d7":{
        "scriptId":"u84"},
      "5302c9f29ec84d49b96b0cdde12c2d96":{
        "scriptId":"u85"},
      "5ce46e8bf0f1475fb3b3b7da2d61bfd4":{
        "scriptId":"u86"},
      "dbd6a5f83af64ab191b7f078d53db2df":{
        "scriptId":"u87"},
      "c081ce32660247bfb9c77e35f3c9f8df":{
        "scriptId":"u88"},
      "f9456264ba204c659a73730ac5f9be10":{
        "scriptId":"u89"},
      "38b51ec901e940038aa1d61e70cebbae":{
        "scriptId":"u90"},
      "cd39e767b2cb408a81a6c3721408db6b":{
        "scriptId":"u91"},
      "45450782be8a4066b51da07d94fc70ca":{
        "scriptId":"u92"},
      "0d3829ac6ae645118ae248d779627e03":{
        "scriptId":"u93"},
      "1e699b0485d842fda37a4804fbb1a443":{
        "scriptId":"u94"},
      "537a1d54bb024094a5238b61a93b1b3b":{
        "scriptId":"u95"},
      "e7e66d880a8948f286fa211dbac91888":{
        "scriptId":"u96"},
      "b7f155757800405f98f3a2e19819a135":{
        "scriptId":"u97"},
      "de6f0a9691d847e8be63625ea68a2fad":{
        "scriptId":"u98"},
      "806e77a021e44ddb9e4b2ec499bc008e":{
        "scriptId":"u99"},
      "d7fcb44076144736abafdcb00a145142":{
        "scriptId":"u100"},
      "0855a01c3bf8421f852d6f1786340508":{
        "scriptId":"u101"},
      "9b3f8f00dd784297b8062985a5c291b6":{
        "scriptId":"u102"},
      "b01444f95aeb4686a41a1b02e9924322":{
        "scriptId":"u103"},
      "c571f4e1ff0749f4b80729d3b1cad885":{
        "scriptId":"u104"},
      "5546bbd9a15544b0adcca0215bcedee1":{
        "scriptId":"u105"},
      "690a1cd387b244b5b2acab4956a49b1e":{
        "scriptId":"u106"}}}});