$axure.loadCurrentPage({
  "url":"11_3_已过期的卡.html",
  "generationDate":new Date(1519785540617.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"a3e88c4f0ba54ef2b829a6eb64dbc010",
    "type":"Axure:Page",
    "name":"11.3 已过期的卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb6536d72c5048d898326bc928b1b74f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6df10b3e3d784b628124edd4180f2776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_2订单支付页/u0.png"}},
{
          "id":"9604e39166ff4aedadcdbfdaf8b56483",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a1c47fe19944d7a2869b40353211bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页/u2.png"}},
{
          "id":"6e6271735ddc4de49bec216fa2755dab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"182f71fabe6b4d8da9b10cd2b41958a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"318980ec8c384b33917179fa18a39821",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":10},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a96cac1e82734e6eb7c384f34b073d54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":10},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb2537c25f3c4eaeb175326740a798bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":50},
            "size":{
              "width":323,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c746fc7a5ee4bfab434dbc5e50f6825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":50},
                "size":{
                  "width":323,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_2_我的卡包/u8.png"}},
{
          "id":"8f4a2ff90bd94a37b6e7aaf942b1b0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"40"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cec4086be9c4cdb88c17b10746deed0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":70},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"40"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_4搜索结果页/u110.png"}},
{
          "id":"d692792d10204d55805190e133939ae6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"13px",
            "location":{
              "x":80,
              "y":63},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2d1c05ff6aa45e6ad5353966df514c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"13px",
                "location":{
                  "x":80,
                  "y":63},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b22bf63dc54b468db3ed7c6ef2f4768d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":80,
              "y":106},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9e55e92b5414868a6bd06edaee5fbd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":80,
                  "y":106},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4918e4c20eec4037825e89698192bed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":235,
              "y":106},
            "size":{
              "width":95,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b08cf9ebd184353b5923e562a356130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":235,
                  "y":106},
                "size":{
                  "width":95,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d568e2bfc8f442098f7e296bd04e32ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":270,
              "y":59},
            "size":{
              "width":60,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e05ad8d77c4bb7b4ec7961398f3c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":270,
                  "y":59},
                "size":{
                  "width":60,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_3_已过期的卡/u18.png"}},
{
          "id":"da24271dc86b4b96a22bf52f5b66ba47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":83},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"197f983e7c504b1799236a9a32eaf9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":83},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43006ce36784496aa90ee13360bf4097",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":287,
              "y":12},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8601d367f714f15a9a55628fb47da68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":287,
                  "y":12},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 11.2 我的卡包",
                      "target":{
                        "targetType":"page",
                        "url":"11_2_我的卡包.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fb6536d72c5048d898326bc928b1b74f":{
      "scriptId":"u0"},
    "6df10b3e3d784b628124edd4180f2776":{
      "scriptId":"u1"},
    "9604e39166ff4aedadcdbfdaf8b56483":{
      "scriptId":"u2"},
    "21a1c47fe19944d7a2869b40353211bd":{
      "scriptId":"u3"},
    "6e6271735ddc4de49bec216fa2755dab":{
      "scriptId":"u4"},
    "182f71fabe6b4d8da9b10cd2b41958a0":{
      "scriptId":"u5"},
    "318980ec8c384b33917179fa18a39821":{
      "scriptId":"u6"},
    "a96cac1e82734e6eb7c384f34b073d54":{
      "scriptId":"u7"},
    "fb2537c25f3c4eaeb175326740a798bc":{
      "scriptId":"u8"},
    "4c746fc7a5ee4bfab434dbc5e50f6825":{
      "scriptId":"u9"},
    "8f4a2ff90bd94a37b6e7aaf942b1b0e3":{
      "scriptId":"u10"},
    "7cec4086be9c4cdb88c17b10746deed0":{
      "scriptId":"u11"},
    "d692792d10204d55805190e133939ae6":{
      "scriptId":"u12"},
    "b2d1c05ff6aa45e6ad5353966df514c7":{
      "scriptId":"u13"},
    "b22bf63dc54b468db3ed7c6ef2f4768d":{
      "scriptId":"u14"},
    "c9e55e92b5414868a6bd06edaee5fbd6":{
      "scriptId":"u15"},
    "4918e4c20eec4037825e89698192bed1":{
      "scriptId":"u16"},
    "1b08cf9ebd184353b5923e562a356130":{
      "scriptId":"u17"},
    "d568e2bfc8f442098f7e296bd04e32ca":{
      "scriptId":"u18"},
    "54e05ad8d77c4bb7b4ec7961398f3c06":{
      "scriptId":"u19"},
    "da24271dc86b4b96a22bf52f5b66ba47":{
      "scriptId":"u20"},
    "197f983e7c504b1799236a9a32eaf9da":{
      "scriptId":"u21"},
    "43006ce36784496aa90ee13360bf4097":{
      "scriptId":"u22"},
    "e8601d367f714f15a9a55628fb47da68":{
      "scriptId":"u23"}}});