$axure.loadCurrentPage({
  "url":"9_0_确认订单模板.html",
  "generationDate":new Date(1515981014889.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"93e745c1c96742969b450986ec177d5e",
    "type":"Axure:Page",
    "name":"9.0 确认订单模板",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a1cdaeb54ccb4a38bbef773ff95b985f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":325,
              "height":1260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4386c09bfe4b4459852115722c7593af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":325,
                  "height":1260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/9_0_确认订单模板/u0.jpg"}},
{
          "id":"93c49c8c0cf349aebcc53f5f2d990487",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":239},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd27fad176141b8928ae617630be650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":239},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/9_0_确认订单模板/u2.png"}},
{
          "id":"5bd4c5cae1044847b7c2a6261d2a8e0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":251},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7a4fd3a97449f2bd92540ff3ebe4c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":251},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"996b2ebb5d5c4be9875c3356e0830245",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":251},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5403ad724b4b4718ae86be838443a33a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":252,
                  "y":251},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfffc4d9494a45c18731aabc341c1aba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":247},
            "size":{
              "width":24,
              "height":24},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e2a9bc19d14f9aadd683499d965f50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":247},
                "size":{
                  "width":24,
                  "height":24},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_2农场体验游详情/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a1cdaeb54ccb4a38bbef773ff95b985f":{
      "scriptId":"u0"},
    "4386c09bfe4b4459852115722c7593af":{
      "scriptId":"u1"},
    "93c49c8c0cf349aebcc53f5f2d990487":{
      "scriptId":"u2"},
    "3cd27fad176141b8928ae617630be650":{
      "scriptId":"u3"},
    "5bd4c5cae1044847b7c2a6261d2a8e0d":{
      "scriptId":"u4"},
    "ec7a4fd3a97449f2bd92540ff3ebe4c8":{
      "scriptId":"u5"},
    "996b2ebb5d5c4be9875c3356e0830245":{
      "scriptId":"u6"},
    "5403ad724b4b4718ae86be838443a33a":{
      "scriptId":"u7"},
    "cfffc4d9494a45c18731aabc341c1aba":{
      "scriptId":"u8"},
    "c1e2a9bc19d14f9aadd683499d965f50":{
      "scriptId":"u9"}}});