$axure.loadCurrentPage({
  "url":"3_0会员充值.html",
  "generationDate":new Date(1521082407026.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"c7b10b805f2149c88618a71ed5d76fea",
    "type":"Axure:Page",
    "name":"3.0会员充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e791f3d433884f50b7849ed18f46c708",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":1350}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f9e67bd640a4a558b3045d59626581c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":1350}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u0.png"}},
{
          "id":"f42628a40acb4ca2804b9ea99a3aee25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8885f2826a9a4548b50845b069e91d14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"898b8dc43747405ead4300c3a3c9bcac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3318a130838a468797f8392963325810",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"0e77fca28e9d4fc78488a5a2ee541eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f43b7f8ac14d119f40dc25d2e58df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7342c14165974911a605d3dce6978b86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0628bcaa9f48b587f003278293bbbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":290},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页/u2.png"}},
{
          "id":"122a11397b0f4daab3c10ed9c11d9410",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":302},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b831e911adb4efc9946154aefbafff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":302},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a32be29b1ead4e6184b118c623b41885",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":302},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36f61d3c977d43ef8ea5f95730bfcd0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":302},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef0e2a42adbd49289380352a1c0c3254",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":298},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b720f9d2ab324cd3b7cc4a8104c8b9a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":298},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_2订单支付页/u34.png"}},
{
          "id":"eb02ee59dcef4381b1915a2dd4d44675",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":340},
            "size":{
              "width":360,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba9d252aab64700861fed92ea0312f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":340},
                "size":{
                  "width":360,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u16.png"}},
{
          "id":"255bfdb314eb4ae1b742cfc88aa9ed76",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "verticalAlignment":"middle",
            "location":{
              "x":21,
              "y":350},
            "size":{
              "width":318,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab9ed8523734aefa2f6a3a5d92e2f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "verticalAlignment":"middle",
                "location":{
                  "x":21,
                  "y":350},
                "size":{
                  "width":318,
                  "height":14}},
              "adaptiveStyles":{
}}]},
{
          "id":"e387dab1524045348da2de4b07a5f701",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0033},
            "location":{
              "x":60,
              "y":374},
            "size":{
              "width":230,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ec6d7832c245e6b30f8e5bbe08e8c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0033},
                "location":{
                  "x":60,
                  "y":374},
                "size":{
                  "width":230,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 3.1充值成功",
                      "target":{
                        "targetType":"page",
                        "url":"3_1充值成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/3_0会员充值/u20.png"}},
{
          "id":"32a7404af0d5441289497b5267223212",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":60,
              "y":429},
            "size":{
              "width":137,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c006fb365b24e93a1cae8d500792b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":429},
                "size":{
                  "width":137,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11a10b5459394b6089663b8912722993",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":374},
            "size":{
              "width":360,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c6305c6b7bc46e1a17d3836bdc17d23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":374},
                "size":{
                  "width":360,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u24.png"}},
{
          "id":"304f96ed8ed447f9a6a305e03d885ab9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":50},
            "size":{
              "width":333,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5d64c2d7e9045afa4d8ee9ac48dd7ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":50},
                "size":{
                  "width":333,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u26.png"}},
{
          "id":"e6b7207778ea40e5936bf4a8468ad79e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":210},
            "size":{
              "width":331,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7196effc61446df906962bdc314c97a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":210},
                "size":{
                  "width":331,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u28.png"}},
{
          "id":"78aa2172c5ad41dab18fe8c54a68d2b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":135,
              "y":70},
            "size":{
              "width":78,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d519e79a1b740f6a12dd43c7ad8a3b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":135,
                  "y":70},
                "size":{
                  "width":78,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeefce8ed0d84ef0ad1b92614b38751e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":126,
              "y":230},
            "size":{
              "width":96,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e48229910fe47ab817af758698154b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":126,
                  "y":230},
                "size":{
                  "width":96,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0bfe2b187204aa1827a9718d991fa8f",
          "label":"500",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":13,
              "y":50},
            "size":{
              "width":333,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"21bb99b04e1f47a7a4a6499f6004eaa4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9b675035b90f4611893f05203c54344f",
                  "label":"",
                  "parentDynamicPanel":"f0bfe2b187204aa1827a9718d991fa8f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":330,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efa4cd28913a41b99d6dc466d724184b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f0bfe2b187204aa1827a9718d991fa8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":330,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/3_0会员充值/u35.png"}},
{
                  "id":"7b0b27de8e424ff7bf0e5200e667614c",
                  "label":"",
                  "parentDynamicPanel":"f0bfe2b187204aa1827a9718d991fa8f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":135,
                      "y":10},
                    "size":{
                      "width":60,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d32b0d068023460caedce9ca440a3080",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f0bfe2b187204aa1827a9718d991fa8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":135,
                          "y":10},
                        "size":{
                          "width":60,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c31cc2f4338a44fdb9af78c6bea9f7c9",
          "label":"3000",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":14,
              "y":210},
            "size":{
              "width":332,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4c801d7ab65a41319c6e9fee311282e5",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"70106052ac9b4a02b4e66ed29049936b",
                  "label":"",
                  "parentDynamicPanel":"c31cc2f4338a44fdb9af78c6bea9f7c9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":330,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e058a2a330243ee97f2e9d3c66d99af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31cc2f4338a44fdb9af78c6bea9f7c9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":330,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/3_0会员充值/u35.png"}},
{
                  "id":"d778f702f28b47ca9a13de796ddbed3e",
                  "label":"",
                  "parentDynamicPanel":"c31cc2f4338a44fdb9af78c6bea9f7c9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":130,
                      "y":20},
                    "size":{
                      "width":69,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66c506d614414639986f8e73e87384ff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31cc2f4338a44fdb9af78c6bea9f7c9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":130,
                          "y":20},
                        "size":{
                          "width":69,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"997255d3775547c5aa44a1be73a47f20",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":50},
            "size":{
              "width":333,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 500",
                      "objectsToFades":[{
                          "objectPath":["f0bfe2b187204aa1827a9718d991fa8f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3000,<br>1000",
                      "objectsToFades":[{
                          "objectPath":["c31cc2f4338a44fdb9af78c6bea9f7c9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fc5ec58beadc4045b99068428e6431c3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"3704b914297f4dd1b2ebe62719e76961",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":210},
            "size":{
              "width":331,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 3000",
                      "objectsToFades":[{
                          "objectPath":["c31cc2f4338a44fdb9af78c6bea9f7c9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 500,<br>1000",
                      "objectsToFades":[{
                          "objectPath":["f0bfe2b187204aa1827a9718d991fa8f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["fc5ec58beadc4045b99068428e6431c3"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"4ee636d475204611adee1af5721c3831",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":130},
            "size":{
              "width":332,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fc20d6f389a4792bb618c63d88feec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":130},
                "size":{
                  "width":332,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u46.png"}},
{
          "id":"e7d9f19b662c4ad5b91743e7a09c2d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":132,
              "y":150},
            "size":{
              "width":96,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"debc8f662f924852a725a4830c461cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":132,
                  "y":150},
                "size":{
                  "width":96,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc5ec58beadc4045b99068428e6431c3",
          "label":"1000",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":14,
              "y":130},
            "size":{
              "width":332,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9fdb7d05f3aa407bb7e4726f6bffd35f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4f2fc9428d304786a2ba695f752ede01",
                  "label":"",
                  "parentDynamicPanel":"fc5ec58beadc4045b99068428e6431c3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":330,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"520e0a615aec457fa91221f200cb0aea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc5ec58beadc4045b99068428e6431c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":330,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/3_0会员充值/u35.png"}},
{
                  "id":"bec120840d10432dac453d847ec1c16c",
                  "label":"",
                  "parentDynamicPanel":"fc5ec58beadc4045b99068428e6431c3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":130,
                      "y":20},
                    "size":{
                      "width":69,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0692aed9f1df4ee6aed7585a74dc2643",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fc5ec58beadc4045b99068428e6431c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0099FF,
                          "opacity":1},
                        "location":{
                          "x":130,
                          "y":20},
                        "size":{
                          "width":69,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"ddbeb9ca349a46eebfc9e0f323f009eb",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":130},
            "size":{
              "width":332,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1000",
                      "objectsToFades":[{
                          "objectPath":["fc5ec58beadc4045b99068428e6431c3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 3000,<br>500",
                      "objectsToFades":[{
                          "objectPath":["c31cc2f4338a44fdb9af78c6bea9f7c9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["f0bfe2b187204aa1827a9718d991fa8f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"d9fdb8517c9348d08264da32a6df85d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":269,
              "y":220},
            "size":{
              "width":70,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b55bca2668840d9ae348aa83ef9ab9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":269,
                  "y":220},
                "size":{
                  "width":70,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u56.png"}},
{
          "id":"55a58a043e264a99a08073413e62a44f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":470},
            "size":{
              "width":360,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1204d8e9ac54a228189e859e889d7d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":470},
                "size":{
                  "width":360,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u58.png"}},
{
          "id":"9096662cb80344008cc3887448600f62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":486},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d12d62e4ef9f4945a9395ac335498c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":486},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1873f27875f342209db95054e761cee2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":740},
            "size":{
              "width":360,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d3209aa3c94f3cac2434773a008f8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":740},
                "size":{
                  "width":360,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u62.png"}},
{
          "id":"1b5fe00ae7134b88b4bff19d3aeecb07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":102,
              "y":89},
            "size":{
              "width":156,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1337bd1288c4b7a949e75296192a4c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":102,
                  "y":89},
                "size":{
                  "width":156,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebaffe43033647b3a5b796635e2bc611",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":102,
              "y":169},
            "size":{
              "width":162,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4217d61f3b2480782b2fb6d88f4fc25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":102,
                  "y":169},
                "size":{
                  "width":162,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"751423a8d4a84a2bb5bfbb6dad2c6191",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":49,
              "y":249},
            "size":{
              "width":262,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439d967dfd564ee8ad2a5e84e108fd74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":49,
                  "y":249},
                "size":{
                  "width":262,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e791f3d433884f50b7849ed18f46c708":{
      "scriptId":"u0"},
    "8f9e67bd640a4a558b3045d59626581c":{
      "scriptId":"u1"},
    "f42628a40acb4ca2804b9ea99a3aee25":{
      "scriptId":"u2"},
    "8885f2826a9a4548b50845b069e91d14":{
      "scriptId":"u3"},
    "898b8dc43747405ead4300c3a3c9bcac":{
      "scriptId":"u4"},
    "3318a130838a468797f8392963325810":{
      "scriptId":"u5"},
    "0e77fca28e9d4fc78488a5a2ee541eb1":{
      "scriptId":"u6"},
    "71f43b7f8ac14d119f40dc25d2e58df4":{
      "scriptId":"u7"},
    "7342c14165974911a605d3dce6978b86":{
      "scriptId":"u8"},
    "2c0628bcaa9f48b587f003278293bbbe":{
      "scriptId":"u9"},
    "122a11397b0f4daab3c10ed9c11d9410":{
      "scriptId":"u10"},
    "7b831e911adb4efc9946154aefbafff6":{
      "scriptId":"u11"},
    "a32be29b1ead4e6184b118c623b41885":{
      "scriptId":"u12"},
    "36f61d3c977d43ef8ea5f95730bfcd0d":{
      "scriptId":"u13"},
    "ef0e2a42adbd49289380352a1c0c3254":{
      "scriptId":"u14"},
    "b720f9d2ab324cd3b7cc4a8104c8b9a1":{
      "scriptId":"u15"},
    "eb02ee59dcef4381b1915a2dd4d44675":{
      "scriptId":"u16"},
    "5ba9d252aab64700861fed92ea0312f8":{
      "scriptId":"u17"},
    "255bfdb314eb4ae1b742cfc88aa9ed76":{
      "scriptId":"u18"},
    "bab9ed8523734aefa2f6a3a5d92e2f56":{
      "scriptId":"u19"},
    "e387dab1524045348da2de4b07a5f701":{
      "scriptId":"u20"},
    "e7ec6d7832c245e6b30f8e5bbe08e8c5":{
      "scriptId":"u21"},
    "32a7404af0d5441289497b5267223212":{
      "scriptId":"u22"},
    "1c006fb365b24e93a1cae8d500792b90":{
      "scriptId":"u23"},
    "11a10b5459394b6089663b8912722993":{
      "scriptId":"u24"},
    "9c6305c6b7bc46e1a17d3836bdc17d23":{
      "scriptId":"u25"},
    "304f96ed8ed447f9a6a305e03d885ab9":{
      "scriptId":"u26"},
    "c5d64c2d7e9045afa4d8ee9ac48dd7ee":{
      "scriptId":"u27"},
    "e6b7207778ea40e5936bf4a8468ad79e":{
      "scriptId":"u28"},
    "f7196effc61446df906962bdc314c97a":{
      "scriptId":"u29"},
    "78aa2172c5ad41dab18fe8c54a68d2b3":{
      "scriptId":"u30"},
    "8d519e79a1b740f6a12dd43c7ad8a3b9":{
      "scriptId":"u31"},
    "aeefce8ed0d84ef0ad1b92614b38751e":{
      "scriptId":"u32"},
    "5e48229910fe47ab817af758698154b0":{
      "scriptId":"u33"},
    "f0bfe2b187204aa1827a9718d991fa8f":{
      "scriptId":"u34"},
    "9b675035b90f4611893f05203c54344f":{
      "scriptId":"u35"},
    "efa4cd28913a41b99d6dc466d724184b":{
      "scriptId":"u36"},
    "7b0b27de8e424ff7bf0e5200e667614c":{
      "scriptId":"u37"},
    "d32b0d068023460caedce9ca440a3080":{
      "scriptId":"u38"},
    "c31cc2f4338a44fdb9af78c6bea9f7c9":{
      "scriptId":"u39"},
    "70106052ac9b4a02b4e66ed29049936b":{
      "scriptId":"u40"},
    "9e058a2a330243ee97f2e9d3c66d99af":{
      "scriptId":"u41"},
    "d778f702f28b47ca9a13de796ddbed3e":{
      "scriptId":"u42"},
    "66c506d614414639986f8e73e87384ff":{
      "scriptId":"u43"},
    "997255d3775547c5aa44a1be73a47f20":{
      "scriptId":"u44"},
    "3704b914297f4dd1b2ebe62719e76961":{
      "scriptId":"u45"},
    "4ee636d475204611adee1af5721c3831":{
      "scriptId":"u46"},
    "1fc20d6f389a4792bb618c63d88feec0":{
      "scriptId":"u47"},
    "e7d9f19b662c4ad5b91743e7a09c2d65":{
      "scriptId":"u48"},
    "debc8f662f924852a725a4830c461cc6":{
      "scriptId":"u49"},
    "fc5ec58beadc4045b99068428e6431c3":{
      "scriptId":"u50"},
    "4f2fc9428d304786a2ba695f752ede01":{
      "scriptId":"u51"},
    "520e0a615aec457fa91221f200cb0aea":{
      "scriptId":"u52"},
    "bec120840d10432dac453d847ec1c16c":{
      "scriptId":"u53"},
    "0692aed9f1df4ee6aed7585a74dc2643":{
      "scriptId":"u54"},
    "ddbeb9ca349a46eebfc9e0f323f009eb":{
      "scriptId":"u55"},
    "d9fdb8517c9348d08264da32a6df85d5":{
      "scriptId":"u56"},
    "1b55bca2668840d9ae348aa83ef9ab9d":{
      "scriptId":"u57"},
    "55a58a043e264a99a08073413e62a44f":{
      "scriptId":"u58"},
    "b1204d8e9ac54a228189e859e889d7d3":{
      "scriptId":"u59"},
    "9096662cb80344008cc3887448600f62":{
      "scriptId":"u60"},
    "d12d62e4ef9f4945a9395ac335498c19":{
      "scriptId":"u61"},
    "1873f27875f342209db95054e761cee2":{
      "scriptId":"u62"},
    "a6d3209aa3c94f3cac2434773a008f8a":{
      "scriptId":"u63"},
    "1b5fe00ae7134b88b4bff19d3aeecb07":{
      "scriptId":"u64"},
    "b1337bd1288c4b7a949e75296192a4c5":{
      "scriptId":"u65"},
    "ebaffe43033647b3a5b796635e2bc611":{
      "scriptId":"u66"},
    "e4217d61f3b2480782b2fb6d88f4fc25":{
      "scriptId":"u67"},
    "751423a8d4a84a2bb5bfbb6dad2c6191":{
      "scriptId":"u68"},
    "439d967dfd564ee8ad2a5e84e108fd74":{
      "scriptId":"u69"}}});