$axure.loadCurrentPage({
  "url":"0_3_搜索页.html",
  "generationDate":new Date(1520925460846.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"a23ba5d494d84760a773fc6021e002a6",
    "type":"Axure:Page",
    "name":"0.3 搜索页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03190d317439459f9bf66435e8f92936",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":667},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5c06cc6f7b14a138e298fe198402d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":667},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/u176.png"}},
{
          "id":"883679e6bd0e469bafe64bf7c232c24f",
          "label":"top",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3806c2eea3404662a15169160f9025b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"ec3e8276393b412a9a660074314bbe84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1c76ee0aac41419d2cd01291db3d77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"d0ac80168e5d45b3b48040c5bb27fc66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":9,
              "y":51},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c37a2a0597b46dc91bc4d6cf0f73c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":51},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaa060ef951c4408a7da52b121ed74be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":9,
              "y":73},
            "size":{
              "width":51,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"402d2bb329684d2d9433bbd3968d03d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":9,
                  "y":73},
                "size":{
                  "width":51,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u191.png"}},
{
          "id":"fa5c8ef51a0d4eef80aa90734ce64a52",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":70,
              "y":73},
            "size":{
              "width":79,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98c73b9e6bbf41ebadb43a014efaa56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":70,
                  "y":73},
                "size":{
                  "width":79,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u193.png"}},
{
          "id":"99a2c8d9f407434ea17b711e0119f784",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":159,
              "y":73},
            "size":{
              "width":79,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d5a38bd8c4445db667e9f4da92753d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":159,
                  "y":73},
                "size":{
                  "width":79,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u193.png"}},
{
          "id":"1a69125da5c84eb290a2c07d90e3405b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":248,
              "y":73},
            "size":{
              "width":92,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81f91a53e9ac4dcf966d994061dfccb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":248,
                  "y":73},
                "size":{
                  "width":92,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u197.png"}},
{
          "id":"66f7b1bc78544bffa16e95447306f985",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":9,
              "y":108},
            "size":{
              "width":79,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04fb7acb0b6a4dcdaea6d3a61927c252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":9,
                  "y":108},
                "size":{
                  "width":79,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u193.png"}},
{
          "id":"2d4457c643ca4a2d80903dab9d258879",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":98,
              "y":108},
            "size":{
              "width":79,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36644a55e2c74837b40cebda58c1cfc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":98,
                  "y":108},
                "size":{
                  "width":79,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u193.png"}},
{
          "id":"93db4cceed3d471d9a2601025856ea30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":9,
              "y":143},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380e5cd5a7a141aab57667bdfad576fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":143},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd78ab2758554553989eabeeda4849fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":166},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"402114a5df5f431496223247ad00e294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":166},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"fa3d081c5a1e420b846fe9c3c1158495",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":178},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ef6328096a4db99c1cf2837ece8a30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":178},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfad18d2bc944e7eb315720b3aa9be00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":205},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"190a8647eef74d1f98234165421763a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":205},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"a8f343fea56b472e99564b61a2ba8c4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":217},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a1c2734a66b41f9822ff7fbde1c3667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":217},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c74716bbf8044a6183e5bba7d6a040a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":244},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf24e6acfd62491bbeeaa4d1700e4afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":244},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"36248200517a41a59d20bb2cb74ce907",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":256},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9593001bc7d04e578d3d32161dd79f90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":256},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a7413ad4dc44ec8b2d64b51fe270d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":283},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"734d050e4a4e482bb744810ae33e54f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":283},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"a240ad2619894585a31ced333f37727e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":295},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9fee8beafbb4d208818ffd7c11abcd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":295},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f76d609d44b648959586ec89478b87df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":315,
              "y":142},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d2bbca7672499d83762c9f4eb3c5c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":315,
                  "y":142},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b13798413b96498995b76d07be4764b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":60,
              "y":7},
            "size":{
              "width":280,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65fab426a3b432da430c7c64859d04c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":60,
                  "y":7},
                "size":{
                  "width":280,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_1选择城市/u78.png"}},
{
          "id":"771c651ddf0e418c8d031b81d7042053",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":70,
              "y":12},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd80bfe368c84e45988e9e9af6a8412b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":12},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0230dfb9ed644608f73be7bb9cc719d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":10},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8694fec7950b4945ab29c279179b18f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":10},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/u54.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03190d317439459f9bf66435e8f92936":{
      "scriptId":"u0"},
    "d5c06cc6f7b14a138e298fe198402d08":{
      "scriptId":"u1"},
    "883679e6bd0e469bafe64bf7c232c24f":{
      "scriptId":"u2"},
    "3806c2eea3404662a15169160f9025b3":{
      "scriptId":"u3"},
    "ec3e8276393b412a9a660074314bbe84":{
      "scriptId":"u4"},
    "4f1c76ee0aac41419d2cd01291db3d77":{
      "scriptId":"u5"},
    "d0ac80168e5d45b3b48040c5bb27fc66":{
      "scriptId":"u6"},
    "7c37a2a0597b46dc91bc4d6cf0f73c0a":{
      "scriptId":"u7"},
    "aaa060ef951c4408a7da52b121ed74be":{
      "scriptId":"u8"},
    "402d2bb329684d2d9433bbd3968d03d7":{
      "scriptId":"u9"},
    "fa5c8ef51a0d4eef80aa90734ce64a52":{
      "scriptId":"u10"},
    "98c73b9e6bbf41ebadb43a014efaa56d":{
      "scriptId":"u11"},
    "99a2c8d9f407434ea17b711e0119f784":{
      "scriptId":"u12"},
    "47d5a38bd8c4445db667e9f4da92753d":{
      "scriptId":"u13"},
    "1a69125da5c84eb290a2c07d90e3405b":{
      "scriptId":"u14"},
    "81f91a53e9ac4dcf966d994061dfccb4":{
      "scriptId":"u15"},
    "66f7b1bc78544bffa16e95447306f985":{
      "scriptId":"u16"},
    "04fb7acb0b6a4dcdaea6d3a61927c252":{
      "scriptId":"u17"},
    "2d4457c643ca4a2d80903dab9d258879":{
      "scriptId":"u18"},
    "36644a55e2c74837b40cebda58c1cfc9":{
      "scriptId":"u19"},
    "93db4cceed3d471d9a2601025856ea30":{
      "scriptId":"u20"},
    "380e5cd5a7a141aab57667bdfad576fc":{
      "scriptId":"u21"},
    "fd78ab2758554553989eabeeda4849fb":{
      "scriptId":"u22"},
    "402114a5df5f431496223247ad00e294":{
      "scriptId":"u23"},
    "fa3d081c5a1e420b846fe9c3c1158495":{
      "scriptId":"u24"},
    "73ef6328096a4db99c1cf2837ece8a30":{
      "scriptId":"u25"},
    "cfad18d2bc944e7eb315720b3aa9be00":{
      "scriptId":"u26"},
    "190a8647eef74d1f98234165421763a6":{
      "scriptId":"u27"},
    "a8f343fea56b472e99564b61a2ba8c4f":{
      "scriptId":"u28"},
    "8a1c2734a66b41f9822ff7fbde1c3667":{
      "scriptId":"u29"},
    "c74716bbf8044a6183e5bba7d6a040a4":{
      "scriptId":"u30"},
    "bf24e6acfd62491bbeeaa4d1700e4afd":{
      "scriptId":"u31"},
    "36248200517a41a59d20bb2cb74ce907":{
      "scriptId":"u32"},
    "9593001bc7d04e578d3d32161dd79f90":{
      "scriptId":"u33"},
    "25a7413ad4dc44ec8b2d64b51fe270d2":{
      "scriptId":"u34"},
    "734d050e4a4e482bb744810ae33e54f8":{
      "scriptId":"u35"},
    "a240ad2619894585a31ced333f37727e":{
      "scriptId":"u36"},
    "a9fee8beafbb4d208818ffd7c11abcd9":{
      "scriptId":"u37"},
    "f76d609d44b648959586ec89478b87df":{
      "scriptId":"u38"},
    "f9d2bbca7672499d83762c9f4eb3c5c7":{
      "scriptId":"u39"},
    "b13798413b96498995b76d07be4764b6":{
      "scriptId":"u40"},
    "c65fab426a3b432da430c7c64859d04c":{
      "scriptId":"u41"},
    "771c651ddf0e418c8d031b81d7042053":{
      "scriptId":"u42"},
    "dd80bfe368c84e45988e9e9af6a8412b":{
      "scriptId":"u43"},
    "e0230dfb9ed644608f73be7bb9cc719d":{
      "scriptId":"u44"},
    "8694fec7950b4945ab29c279179b18f6":{
      "scriptId":"u45"}}});