$axure.loadCurrentPage({
  "url":"平台简介.html",
  "generationDate":new Date(1500453290143.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8521f0ab463f48db983b8d17c2065e67",
    "type":"Axure:Page",
    "name":"平台简介",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b22112a07c9431e853d410e476e6a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4f12348a5a4755ad2d3ab165236d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u0.png"}},
{
          "id":"c9352d30998f480399d9a1df1af63aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e16382e59d4ec2af48f96a78601490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u2.png"}},
{
          "id":"872640187cde461995c12c3310c50370",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f264fdd782a640e8a051e29c9e1b4538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商品列表/u17.png"}},
{
          "id":"5d461c2f6d804383a230526066d1af49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":133,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f07622d5d71432b9a6ed0a168a2cbaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":133,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7b118934fe14d9ab5239efbce7d0154",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fe1291e9a1400b8c33ba0fe50605e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u21.png"}},
{
          "id":"1095b6aaa09a4e79b08c8cb1c8292c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc96eba7b7e6441bae995261472d00ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u21.png"}},
{
          "id":"c46432eebce64b69a48af648b4a0350e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba490fe420e48898793bda2c8daa956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u21.png"}},
{
          "id":"23065884de784e58aeb400ee415bf9fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":268},
            "size":{
              "width":340,
              "height":302}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"756c2d9396c14897a277c1eb57019815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":268},
                "size":{
                  "width":340,
                  "height":302}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd6dd4e201e244d08457ec37ae09fdbc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30.5,
              "y":50},
            "size":{
              "width":299,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c53fbcb7804ca6a272a68a1751036a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30.5,
                  "y":50},
                "size":{
                  "width":299,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u16.jpg"}},
{
          "id":"bc20b8a86433469a96be83b35b78cca2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":520},
            "size":{
              "width":340,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92ea9067b71c4defb557080d21c1be55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":520},
                "size":{
                  "width":340,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5b22112a07c9431e853d410e476e6a60":{
      "scriptId":"u0"},
    "6c4f12348a5a4755ad2d3ab165236d46":{
      "scriptId":"u1"},
    "c9352d30998f480399d9a1df1af63aa1":{
      "scriptId":"u2"},
    "43e16382e59d4ec2af48f96a78601490":{
      "scriptId":"u3"},
    "872640187cde461995c12c3310c50370":{
      "scriptId":"u4"},
    "f264fdd782a640e8a051e29c9e1b4538":{
      "scriptId":"u5"},
    "5d461c2f6d804383a230526066d1af49":{
      "scriptId":"u6"},
    "7f07622d5d71432b9a6ed0a168a2cbaa":{
      "scriptId":"u7"},
    "b7b118934fe14d9ab5239efbce7d0154":{
      "scriptId":"u8"},
    "e9fe1291e9a1400b8c33ba0fe50605e6":{
      "scriptId":"u9"},
    "1095b6aaa09a4e79b08c8cb1c8292c95":{
      "scriptId":"u10"},
    "bc96eba7b7e6441bae995261472d00ce":{
      "scriptId":"u11"},
    "c46432eebce64b69a48af648b4a0350e":{
      "scriptId":"u12"},
    "3ba490fe420e48898793bda2c8daa956":{
      "scriptId":"u13"},
    "23065884de784e58aeb400ee415bf9fe":{
      "scriptId":"u14"},
    "756c2d9396c14897a277c1eb57019815":{
      "scriptId":"u15"},
    "dd6dd4e201e244d08457ec37ae09fdbc":{
      "scriptId":"u16"},
    "b2c53fbcb7804ca6a272a68a1751036a":{
      "scriptId":"u17"},
    "bc20b8a86433469a96be83b35b78cca2":{
      "scriptId":"u18"},
    "92ea9067b71c4defb557080d21c1be55":{
      "scriptId":"u19"}}});