$axure.loadCurrentPage({
  "url":"全部订单.html",
  "generationDate":new Date(1503365082464.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"47818939af5e4547be0f1d04880bb9f7",
    "type":"Axure:Page",
    "name":"全部订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5478764aab9f4a20a74fb71300fd8493",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f744e371c2924ceebbbbd9e0c3ba3cd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单支付页/u0.png"}},
{
          "id":"4b4656b338e140c4aa62f7b4a67b0b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49fbdad49e164288b0aabe2619bbde84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页_安卓_/top_u2.png"}},
{
          "id":"4a528dd320764523b31951041a737b03",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27305b67b1a14a0f9013bcf3289f9ca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/平台简介/u4.png"}},
{
          "id":"c1edc8dbfc3b4c0685a75b40198906d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":145,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fdb50b082642c290ccdc3bd44b38f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":145,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb8b21536fe4e16bca31ea0e9d48d9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":340,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e3a90f716f45e7adcbf0a804f8ea5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":340,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"fd52a68d6a274608b097c117535bbead",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":340,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12ff929f9de4617872a8660f2d80f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":340,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"c1510f8dea5740acab80fe6a40f0c8f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":340,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce483e121444d79aa5cb35aa44fde0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":340,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"15bfd199c91542e9a3e3ab16166e20c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":89,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acd1e66d5f534e09ad62deceae74d329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":89,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u14.png"}},
{
          "id":"75b8df78017e4c3abff54d59c5b84318",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":39},
            "size":{
              "width":91,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33bc03700dd64c0da470d71cb8f7a4aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":39},
                "size":{
                  "width":91,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u16.png"}},
{
          "id":"8340ac1988d246f1a31661bed00d4df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":39},
            "size":{
              "width":91,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d88bdce7d142c9b0bd5db4d37f9796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":39},
                "size":{
                  "width":91,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u16.png"}},
{
          "id":"7ebb5d6311f94ca989ab361f37e5fbd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":269,
              "y":39},
            "size":{
              "width":91,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c3ba5fd2de4d729feb94833779f02f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":269,
                  "y":39},
                "size":{
                  "width":91,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u16.png"}},
{
          "id":"120612823ae4469eaf470e178f2879cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":0,
              "y":77},
            "size":{
              "width":89,
              "height":2},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c92187cad42944d9858341baa952a3bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":0,
                  "y":77},
                "size":{
                  "width":89,
                  "height":2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u22.png"}},
{
          "id":"f677d41454944694b778abb771ad10e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":89},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ed2e7e047a4befa79bb5f4e1f51b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":89},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u24.png"}},
{
          "id":"d821fb6a102c4637bd47d1b3be4e00c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":94},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8de96b70ce194762a533cc73c8aeb780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":94},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u26.png"}},
{
          "id":"2de504157cc24dfe88757d002a6f17cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":101},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d40c7b64929548d1b596c9f546eb742d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":101},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e02bfc11605640afb8502cbb01fca5f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":312,
              "y":102},
            "size":{
              "width":34,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac259ffd87549ce974b4dac4db8acbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":312,
                  "y":102},
                "size":{
                  "width":34,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c942178ec894f36a41bf5cf1bd0ca5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":129},
            "size":{
              "width":360,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6190a837cab6402fa8c6f16b35980394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":129},
                "size":{
                  "width":360,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬果订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"蔬果订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全部订单/u32.png"}},
{
          "id":"0c3517255fdc43ab8524bf2d4f7bf96f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":139},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae4a18842c345e4847d9043b5117c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":139},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed683eedd1ad4d1ca4cb1b700646ce3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":178},
            "size":{
              "width":130,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7932b5d80cb045c4accb5963bd99cdf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":178},
                "size":{
                  "width":130,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96d7dc3eccab437dbc6d9c07ab0675d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":195},
            "size":{
              "width":186,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35200b477d9c4934a467a632bb35ed18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":195},
                "size":{
                  "width":186,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab24ccf687a44bb1a9ae33cf442e8874",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":296,
              "y":139},
            "size":{
              "width":50,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46d615919f445e5bdd397177821cfa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":296,
                  "y":139},
                "size":{
                  "width":50,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7918d099f3e94a41b242aeb02a58b017",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":225},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48bd5d86d4584c5d970e126557503f49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":225},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u24.png"}},
{
          "id":"18a0b642fba64490bb4e27ba48230b70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5490599660434252957fd1c26061d91d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":230},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u44.png"}},
{
          "id":"fd0ab676231f4078914b3e9d482ff4d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":237},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b931e17d5414fb38f73e1d59df1cf70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":237},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d479fe3704104ca4829259400e09a123",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":301,
              "y":239},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"743e77225be649ed91486fd2a4e0183b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":239},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52276a0671634da5b9dfaa726c408e2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":360,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eaaf7d565024bcf806bf2d2a8d6c61f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":265},
                "size":{
                  "width":360,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u32.png"}},
{
          "id":"8be2eeeb84af4fd7b52cf9ab757368e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":10,
              "y":275},
            "size":{
              "width":285,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e557c4b2c30143288ac5169266f1d53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":10,
                  "y":275},
                "size":{
                  "width":285,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e58b6e5371e415bbfef431edc77201b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":314},
            "size":{
              "width":130,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3a4997da2c54ce598b1f3d09717c1cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":314},
                "size":{
                  "width":130,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58bab33546e54a219e3963e459056bce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":331},
            "size":{
              "width":40,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b17c0a208c4b66a5eae181f5e8a7fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":331},
                "size":{
                  "width":40,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"916979d2932f4dcd9dd88ebf924fb43f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":305,
              "y":275},
            "size":{
              "width":41,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0de15571d58475190dc9b92a88f6783",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":305,
                  "y":275},
                "size":{
                  "width":41,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"598088a7a96c4382832c8d3c4f787ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":350},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9e458c01674c9bb87d6e55abf56a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":350},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u24.png"}},
{
          "id":"f5d8af2db58e4b9e9d285becfd96f6bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":279,
              "y":358},
            "size":{
              "width":67,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c92f9bd0a354f648df535823828606d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":279,
                  "y":358},
                "size":{
                  "width":67,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u62.png"}},
{
          "id":"19c8a2b3698f4d2e9063894de19fa006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":400},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"946c4a17c93b4cfca0d65eb6a96ca6e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":400},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u24.png"}},
{
          "id":"8fa6bed469ba4a6298ca0855ce39928e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":405},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4503260a070d453286c1a186a223bccd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":405},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部订单/u26.png"}},
{
          "id":"9f6fff5f0445435bacc4b4eeed25cacb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":412},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f357912a34e4521844cbfa57d6c6451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":412},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7aa6b362e0c74f779343a54510d35de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":242,
              "y":412},
            "size":{
              "width":104,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c087d2457bfc4331a03fa4b2339ac193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":242,
                  "y":412},
                "size":{
                  "width":104,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70457d6ce0a540e78e9c0b3a14a0cb74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":440},
            "size":{
              "width":360,
              "height":86},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dfde74c8ad74bdf8afc2e2098c0d129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":440},
                "size":{
                  "width":360,
                  "height":86},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蔬果订单详情2",
                      "target":{
                        "targetType":"page",
                        "url":"蔬果订单详情2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/全部订单/u32.png"}},
{
          "id":"63bfb81d41b14fffb3ea50e3388d92c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef61061b0d55420a85e2fb1b7c01e829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08eca332e01e4867b271883117465239",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":489},
            "size":{
              "width":130,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"232474167bf645c593494c18f80a8806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":489},
                "size":{
                  "width":130,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a415e4fd486b451eb8ba0ee82d31b947",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":10,
              "y":506},
            "size":{
              "width":187,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfae2855629444f4a92e18293f03a228",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":506},
                "size":{
                  "width":187,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"093ce441d2254f6396f57bbf6c9dfddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":296,
              "y":450},
            "size":{
              "width":50,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc2c9fd1c1e4a358e23b5e9d015f808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":296,
                  "y":450},
                "size":{
                  "width":50,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"299de240754542e0a7d6ad37c7908fcc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":263},
            "size":{
              "width":360,
              "height":87}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农旅订单详情",
                      "target":{
                        "targetType":"page",
                        "url":"农旅订单详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"78a04ae762694974aec4a1ebfb49a96b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":627},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0649cb58ca004a9fa8f148086f3f4aaa",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f201ee68b66d40f2ba70ceb0fde829c7",
                  "label":"",
                  "parentDynamicPanel":"78a04ae762694974aec4a1ebfb49a96b",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":360,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "masterId":"8387a0f784dc4517ba344c8c934a23b2"}]}]}]}},
  "masters":{
    "8387a0f784dc4517ba344c8c934a23b2":{
      "packageId":"8387a0f784dc4517ba344c8c934a23b2",
      "type":"Axure:Master",
      "name":"底部菜单0803",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d3980e768e434d6e8006717cfc1027d7",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"33e17ce2012b4cbda3b4e022b57a30db",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"23869cb13512415b8b7971a663608747",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":360,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3217ebd80ccd40c586ae39ff3ebb1543",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":360,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_/u241.png"}},
{
                    "id":"d004dced895a4eacb5efe917cca36edf",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":29,
                        "y":24},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c8814745f745428db1ec799978487b14",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":29,
                            "y":24},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"410ed3b8921c4b049c59109bbeab49e3",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":92,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a651b47d1e6e452cad7dfe30c2a0ae7c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":92,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"4e103bbf5272432fbfcaef86e4b44e2a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":162,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"12db86e5ca4c477e9addd5bac0cc3d6d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":162,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"910efa73a76d4b0d9db84006f75ec976",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":299,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a42ded06f7a7420f807e1369cb460d27",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":299,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"6d5a344f556a43e6a407001e342fbfea",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":29,
                        "y":2},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0b939d02785c48368653a620956655b4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":29,
                            "y":2},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u36.png"}},
{
                    "id":"fcf6bc000ad54b73a898b7612b0fd1be",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":310,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e8182f657e0a44b2a22072f4fe191a65",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":310,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u42.png"}},
{
                    "id":"999196b197e840f79974725b89c13987",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":100,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e40a4d1685f84b2eb78df8b3d82849aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":100,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_/u255.png"}},
{
                    "id":"e0c8b35ab6c640e4bfa3685c98588a2d",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":170,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"645a1aecdf08437f99fc444dc99f3e10",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":170,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/会员主页_安卓_/u303.png"}},
{
                    "id":"eec58566454a4f2e98c657fc63602e14",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":10,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 会员主页(安卓)",
                                "target":{
                                  "targetType":"page",
                                  "url":"会员主页_安卓_.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"1f411e1738bb4e92b2246476820aabcf",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":290,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"feaa4ec5828a484d9f8f1adbc8376f70",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":80,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主题农旅",
                                "target":{
                                  "targetType":"page",
                                  "url":"主题农旅.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"28fa6cc4561a4a51b20ceee7f7d61b68",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 会员专区",
                                "target":{
                                  "targetType":"page",
                                  "url":"会员专区.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"469056e6db7b48ea8beb0cde764fda32",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":229,
                        "y":24},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cd991483bf843d1ae7045e6e98ebf9b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":229,
                            "y":24},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"78876019e8d742938da830e4d8d4574a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":240,
                        "y":4},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"29d462b7bb7a493b87ec072faf2f5d57",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":240,
                            "y":4},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页_安卓_/u265.png"}},
{
                    "id":"d871e8d8e00b43e38ddfde26b9da7948",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":220,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 农旅百科",
                                "target":{
                                  "targetType":"page",
                                  "url":"农旅百科.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}]}]}}},
  "objectPaths":{
    "5478764aab9f4a20a74fb71300fd8493":{
      "scriptId":"u0"},
    "f744e371c2924ceebbbbd9e0c3ba3cd0":{
      "scriptId":"u1"},
    "4b4656b338e140c4aa62f7b4a67b0b20":{
      "scriptId":"u2"},
    "49fbdad49e164288b0aabe2619bbde84":{
      "scriptId":"u3"},
    "4a528dd320764523b31951041a737b03":{
      "scriptId":"u4"},
    "27305b67b1a14a0f9013bcf3289f9ca1":{
      "scriptId":"u5"},
    "c1edc8dbfc3b4c0685a75b40198906d1":{
      "scriptId":"u6"},
    "26fdb50b082642c290ccdc3bd44b38f5":{
      "scriptId":"u7"},
    "5eb8b21536fe4e16bca31ea0e9d48d9f":{
      "scriptId":"u8"},
    "59e3a90f716f45e7adcbf0a804f8ea5a":{
      "scriptId":"u9"},
    "fd52a68d6a274608b097c117535bbead":{
      "scriptId":"u10"},
    "e12ff929f9de4617872a8660f2d80f74":{
      "scriptId":"u11"},
    "c1510f8dea5740acab80fe6a40f0c8f0":{
      "scriptId":"u12"},
    "0ce483e121444d79aa5cb35aa44fde0b":{
      "scriptId":"u13"},
    "15bfd199c91542e9a3e3ab16166e20c2":{
      "scriptId":"u14"},
    "acd1e66d5f534e09ad62deceae74d329":{
      "scriptId":"u15"},
    "75b8df78017e4c3abff54d59c5b84318":{
      "scriptId":"u16"},
    "33bc03700dd64c0da470d71cb8f7a4aa":{
      "scriptId":"u17"},
    "8340ac1988d246f1a31661bed00d4df3":{
      "scriptId":"u18"},
    "a6d88bdce7d142c9b0bd5db4d37f9796":{
      "scriptId":"u19"},
    "7ebb5d6311f94ca989ab361f37e5fbd3":{
      "scriptId":"u20"},
    "09c3ba5fd2de4d729feb94833779f02f":{
      "scriptId":"u21"},
    "120612823ae4469eaf470e178f2879cd":{
      "scriptId":"u22"},
    "c92187cad42944d9858341baa952a3bb":{
      "scriptId":"u23"},
    "f677d41454944694b778abb771ad10e4":{
      "scriptId":"u24"},
    "07ed2e7e047a4befa79bb5f4e1f51b71":{
      "scriptId":"u25"},
    "d821fb6a102c4637bd47d1b3be4e00c4":{
      "scriptId":"u26"},
    "8de96b70ce194762a533cc73c8aeb780":{
      "scriptId":"u27"},
    "2de504157cc24dfe88757d002a6f17cc":{
      "scriptId":"u28"},
    "d40c7b64929548d1b596c9f546eb742d":{
      "scriptId":"u29"},
    "e02bfc11605640afb8502cbb01fca5f0":{
      "scriptId":"u30"},
    "dac259ffd87549ce974b4dac4db8acbb":{
      "scriptId":"u31"},
    "6c942178ec894f36a41bf5cf1bd0ca5b":{
      "scriptId":"u32"},
    "6190a837cab6402fa8c6f16b35980394":{
      "scriptId":"u33"},
    "0c3517255fdc43ab8524bf2d4f7bf96f":{
      "scriptId":"u34"},
    "1ae4a18842c345e4847d9043b5117c60":{
      "scriptId":"u35"},
    "ed683eedd1ad4d1ca4cb1b700646ce3e":{
      "scriptId":"u36"},
    "7932b5d80cb045c4accb5963bd99cdf9":{
      "scriptId":"u37"},
    "96d7dc3eccab437dbc6d9c07ab0675d1":{
      "scriptId":"u38"},
    "35200b477d9c4934a467a632bb35ed18":{
      "scriptId":"u39"},
    "ab24ccf687a44bb1a9ae33cf442e8874":{
      "scriptId":"u40"},
    "c46d615919f445e5bdd397177821cfa0":{
      "scriptId":"u41"},
    "7918d099f3e94a41b242aeb02a58b017":{
      "scriptId":"u42"},
    "48bd5d86d4584c5d970e126557503f49":{
      "scriptId":"u43"},
    "18a0b642fba64490bb4e27ba48230b70":{
      "scriptId":"u44"},
    "5490599660434252957fd1c26061d91d":{
      "scriptId":"u45"},
    "fd0ab676231f4078914b3e9d482ff4d9":{
      "scriptId":"u46"},
    "2b931e17d5414fb38f73e1d59df1cf70":{
      "scriptId":"u47"},
    "d479fe3704104ca4829259400e09a123":{
      "scriptId":"u48"},
    "743e77225be649ed91486fd2a4e0183b":{
      "scriptId":"u49"},
    "52276a0671634da5b9dfaa726c408e2b":{
      "scriptId":"u50"},
    "6eaaf7d565024bcf806bf2d2a8d6c61f":{
      "scriptId":"u51"},
    "8be2eeeb84af4fd7b52cf9ab757368e9":{
      "scriptId":"u52"},
    "e557c4b2c30143288ac5169266f1d53b":{
      "scriptId":"u53"},
    "4e58b6e5371e415bbfef431edc77201b":{
      "scriptId":"u54"},
    "d3a4997da2c54ce598b1f3d09717c1cd":{
      "scriptId":"u55"},
    "58bab33546e54a219e3963e459056bce":{
      "scriptId":"u56"},
    "56b17c0a208c4b66a5eae181f5e8a7fa":{
      "scriptId":"u57"},
    "916979d2932f4dcd9dd88ebf924fb43f":{
      "scriptId":"u58"},
    "f0de15571d58475190dc9b92a88f6783":{
      "scriptId":"u59"},
    "598088a7a96c4382832c8d3c4f787ac2":{
      "scriptId":"u60"},
    "ca9e458c01674c9bb87d6e55abf56a5f":{
      "scriptId":"u61"},
    "f5d8af2db58e4b9e9d285becfd96f6bf":{
      "scriptId":"u62"},
    "4c92f9bd0a354f648df535823828606d":{
      "scriptId":"u63"},
    "19c8a2b3698f4d2e9063894de19fa006":{
      "scriptId":"u64"},
    "946c4a17c93b4cfca0d65eb6a96ca6e6":{
      "scriptId":"u65"},
    "8fa6bed469ba4a6298ca0855ce39928e":{
      "scriptId":"u66"},
    "4503260a070d453286c1a186a223bccd":{
      "scriptId":"u67"},
    "9f6fff5f0445435bacc4b4eeed25cacb":{
      "scriptId":"u68"},
    "0f357912a34e4521844cbfa57d6c6451":{
      "scriptId":"u69"},
    "7aa6b362e0c74f779343a54510d35de5":{
      "scriptId":"u70"},
    "c087d2457bfc4331a03fa4b2339ac193":{
      "scriptId":"u71"},
    "70457d6ce0a540e78e9c0b3a14a0cb74":{
      "scriptId":"u72"},
    "9dfde74c8ad74bdf8afc2e2098c0d129":{
      "scriptId":"u73"},
    "63bfb81d41b14fffb3ea50e3388d92c7":{
      "scriptId":"u74"},
    "ef61061b0d55420a85e2fb1b7c01e829":{
      "scriptId":"u75"},
    "08eca332e01e4867b271883117465239":{
      "scriptId":"u76"},
    "232474167bf645c593494c18f80a8806":{
      "scriptId":"u77"},
    "a415e4fd486b451eb8ba0ee82d31b947":{
      "scriptId":"u78"},
    "bfae2855629444f4a92e18293f03a228":{
      "scriptId":"u79"},
    "093ce441d2254f6396f57bbf6c9dfddf":{
      "scriptId":"u80"},
    "8dc2c9fd1c1e4a358e23b5e9d015f808":{
      "scriptId":"u81"},
    "299de240754542e0a7d6ad37c7908fcc":{
      "scriptId":"u82"},
    "78a04ae762694974aec4a1ebfb49a96b":{
      "scriptId":"u83"},
    "f201ee68b66d40f2ba70ceb0fde829c7":{
      "scriptId":"u84",
      "d3980e768e434d6e8006717cfc1027d7":{
        "scriptId":"u85"},
      "23869cb13512415b8b7971a663608747":{
        "scriptId":"u86"},
      "3217ebd80ccd40c586ae39ff3ebb1543":{
        "scriptId":"u87"},
      "d004dced895a4eacb5efe917cca36edf":{
        "scriptId":"u88"},
      "c8814745f745428db1ec799978487b14":{
        "scriptId":"u89"},
      "410ed3b8921c4b049c59109bbeab49e3":{
        "scriptId":"u90"},
      "a651b47d1e6e452cad7dfe30c2a0ae7c":{
        "scriptId":"u91"},
      "4e103bbf5272432fbfcaef86e4b44e2a":{
        "scriptId":"u92"},
      "12db86e5ca4c477e9addd5bac0cc3d6d":{
        "scriptId":"u93"},
      "910efa73a76d4b0d9db84006f75ec976":{
        "scriptId":"u94"},
      "a42ded06f7a7420f807e1369cb460d27":{
        "scriptId":"u95"},
      "6d5a344f556a43e6a407001e342fbfea":{
        "scriptId":"u96"},
      "0b939d02785c48368653a620956655b4":{
        "scriptId":"u97"},
      "fcf6bc000ad54b73a898b7612b0fd1be":{
        "scriptId":"u98"},
      "e8182f657e0a44b2a22072f4fe191a65":{
        "scriptId":"u99"},
      "999196b197e840f79974725b89c13987":{
        "scriptId":"u100"},
      "e40a4d1685f84b2eb78df8b3d82849aa":{
        "scriptId":"u101"},
      "e0c8b35ab6c640e4bfa3685c98588a2d":{
        "scriptId":"u102"},
      "645a1aecdf08437f99fc444dc99f3e10":{
        "scriptId":"u103"},
      "eec58566454a4f2e98c657fc63602e14":{
        "scriptId":"u104"},
      "1f411e1738bb4e92b2246476820aabcf":{
        "scriptId":"u105"},
      "feaa4ec5828a484d9f8f1adbc8376f70":{
        "scriptId":"u106"},
      "28fa6cc4561a4a51b20ceee7f7d61b68":{
        "scriptId":"u107"},
      "469056e6db7b48ea8beb0cde764fda32":{
        "scriptId":"u108"},
      "5cd991483bf843d1ae7045e6e98ebf9b":{
        "scriptId":"u109"},
      "78876019e8d742938da830e4d8d4574a":{
        "scriptId":"u110"},
      "29d462b7bb7a493b87ec072faf2f5d57":{
        "scriptId":"u111"},
      "d871e8d8e00b43e38ddfde26b9da7948":{
        "scriptId":"u112"}}}});