$axure.loadCurrentPage({
  "url":"蔬菜箱.html",
  "generationDate":new Date(1504691809894.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"9f527a182f21478fbc13e4e5c8cf4595",
    "type":"Axure:Page",
    "name":"蔬菜箱",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51c8fa84a4664c7dab516ee1a5ba4ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f78ca961e44c21a74bb491998af120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/蔬菜箱/u0.png"}},
{
          "id":"7cd79df75a1a40d0be2f5e9fd844911f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e9cc9557a0418d8bfdd6edff9777a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部分类/u2.png"}},
{
          "id":"c66da8410f0b40a1a25da9e299c2adb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a6503992e17402c9cd7575aa2dc1bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择城市/u4.png"}},
{
          "id":"85ffd25ae39541e4bf3f1dcd44a6454f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":152.5,
              "y":9},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0033f8d31bd458ab113e6ac9d9bf168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":152.5,
                  "y":9},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab5e2bd1ec514d13aa547ad6050ae965",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":697}},
          "adaptiveStyles":{
},
          "masterId":"a652b6c4ffdd4c70aeca0ab75b8386af"},
{
          "id":"39b7e9ca631f41ecaddbfe28e169dc48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":94},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8573a3987ac45339760fc7f05838123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":94},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81efd492c2ef4b6c94fab6e50fbdf07b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":120,
              "y":140},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e55a1eeba5949ada439358c06898548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":120,
                  "y":140},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购买配送次数",
                      "target":{
                        "targetType":"page",
                        "url":"购买配送次数.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/蔬菜箱/u41.png"}}]}},
  "masters":{
    "a652b6c4ffdd4c70aeca0ab75b8386af":{
      "packageId":"a652b6c4ffdd4c70aeca0ab75b8386af",
      "type":"Axure:Master",
      "name":"底部菜单0831",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d3980e768e434d6e8006717cfc1027d7",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":360,
                "height":63}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":0,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"33e17ce2012b4cbda3b4e022b57a30db",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"23869cb13512415b8b7971a663608747",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":23},
                      "size":{
                        "width":360,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3217ebd80ccd40c586ae39ff3ebb1543",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":23},
                          "size":{
                            "width":360,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u370.png"}},
{
                    "id":"d004dced895a4eacb5efe917cca36edf",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":29,
                        "y":47},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c8814745f745428db1ec799978487b14",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":29,
                            "y":47},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"410ed3b8921c4b049c59109bbeab49e3",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":92,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a651b47d1e6e452cad7dfe30c2a0ae7c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":92,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"910efa73a76d4b0d9db84006f75ec976",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":299,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a42ded06f7a7420f807e1369cb460d27",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":299,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"6d5a344f556a43e6a407001e342fbfea",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":29,
                        "y":25},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0b939d02785c48368653a620956655b4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":29,
                            "y":25},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u378.png"}},
{
                    "id":"fcf6bc000ad54b73a898b7612b0fd1be",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":310,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e8182f657e0a44b2a22072f4fe191a65",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":310,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u380.png"}},
{
                    "id":"999196b197e840f79974725b89c13987",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":100,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e40a4d1685f84b2eb78df8b3d82849aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":100,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u382.png"}},
{
                    "id":"469056e6db7b48ea8beb0cde764fda32",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":229,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cd991483bf843d1ae7045e6e98ebf9b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":229,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"78876019e8d742938da830e4d8d4574a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":240,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"29d462b7bb7a493b87ec072faf2f5d57",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":240,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u386.png"}},
{
                    "id":"e54b788ac95740f0a17b53707d224d1e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":60},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"60"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0322dabe132f4082bf7d358e28e63678",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":150,
                            "y":0},
                          "size":{
                            "width":60,
                            "height":60},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"60"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u388.png"}},
{
                    "id":"4e103bbf5272432fbfcaef86e4b44e2a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":165,
                        "y":39},
                      "size":{
                        "width":31,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"12db86e5ca4c477e9addd5bac0cc3d6d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":165,
                            "y":39},
                          "size":{
                            "width":31,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e0c8b35ab6c640e4bfa3685c98588a2d",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":171,
                        "y":15},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"645a1aecdf08437f99fc444dc99f3e10",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":171,
                            "y":15},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u392.png"}},
{
                    "id":"c6e97157c788455f9783097231226f7e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":290,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"696eadac344b40088748cf59bc9aaa9b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":10,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8de9a287ce1540abbcb6ec1b3c3a6254",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":63}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 蔬菜箱",
                                "target":{
                                  "targetType":"page",
                                  "url":"蔬菜箱_1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"480968bad064489eb276b95791c47f09",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":221,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 农旅百科",
                                "target":{
                                  "targetType":"page",
                                  "url":"农旅百科.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"523c14d7ed4e4203a06eb6512ffe4fee",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":79,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 全部分类",
                                "target":{
                                  "targetType":"page",
                                  "url":"全部分类.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}]}]}}},
  "objectPaths":{
    "51c8fa84a4664c7dab516ee1a5ba4ce6":{
      "scriptId":"u0"},
    "02f78ca961e44c21a74bb491998af120":{
      "scriptId":"u1"},
    "7cd79df75a1a40d0be2f5e9fd844911f":{
      "scriptId":"u2"},
    "22e9cc9557a0418d8bfdd6edff9777a6":{
      "scriptId":"u3"},
    "c66da8410f0b40a1a25da9e299c2adb7":{
      "scriptId":"u4"},
    "0a6503992e17402c9cd7575aa2dc1bdf":{
      "scriptId":"u5"},
    "85ffd25ae39541e4bf3f1dcd44a6454f":{
      "scriptId":"u6"},
    "f0033f8d31bd458ab113e6ac9d9bf168":{
      "scriptId":"u7"},
    "ab5e2bd1ec514d13aa547ad6050ae965":{
      "scriptId":"u8",
      "d3980e768e434d6e8006717cfc1027d7":{
        "scriptId":"u9"},
      "23869cb13512415b8b7971a663608747":{
        "scriptId":"u10"},
      "3217ebd80ccd40c586ae39ff3ebb1543":{
        "scriptId":"u11"},
      "d004dced895a4eacb5efe917cca36edf":{
        "scriptId":"u12"},
      "c8814745f745428db1ec799978487b14":{
        "scriptId":"u13"},
      "410ed3b8921c4b049c59109bbeab49e3":{
        "scriptId":"u14"},
      "a651b47d1e6e452cad7dfe30c2a0ae7c":{
        "scriptId":"u15"},
      "910efa73a76d4b0d9db84006f75ec976":{
        "scriptId":"u16"},
      "a42ded06f7a7420f807e1369cb460d27":{
        "scriptId":"u17"},
      "6d5a344f556a43e6a407001e342fbfea":{
        "scriptId":"u18"},
      "0b939d02785c48368653a620956655b4":{
        "scriptId":"u19"},
      "fcf6bc000ad54b73a898b7612b0fd1be":{
        "scriptId":"u20"},
      "e8182f657e0a44b2a22072f4fe191a65":{
        "scriptId":"u21"},
      "999196b197e840f79974725b89c13987":{
        "scriptId":"u22"},
      "e40a4d1685f84b2eb78df8b3d82849aa":{
        "scriptId":"u23"},
      "469056e6db7b48ea8beb0cde764fda32":{
        "scriptId":"u24"},
      "5cd991483bf843d1ae7045e6e98ebf9b":{
        "scriptId":"u25"},
      "78876019e8d742938da830e4d8d4574a":{
        "scriptId":"u26"},
      "29d462b7bb7a493b87ec072faf2f5d57":{
        "scriptId":"u27"},
      "e54b788ac95740f0a17b53707d224d1e":{
        "scriptId":"u28"},
      "0322dabe132f4082bf7d358e28e63678":{
        "scriptId":"u29"},
      "4e103bbf5272432fbfcaef86e4b44e2a":{
        "scriptId":"u30"},
      "12db86e5ca4c477e9addd5bac0cc3d6d":{
        "scriptId":"u31"},
      "e0c8b35ab6c640e4bfa3685c98588a2d":{
        "scriptId":"u32"},
      "645a1aecdf08437f99fc444dc99f3e10":{
        "scriptId":"u33"},
      "c6e97157c788455f9783097231226f7e":{
        "scriptId":"u34"},
      "696eadac344b40088748cf59bc9aaa9b":{
        "scriptId":"u35"},
      "8de9a287ce1540abbcb6ec1b3c3a6254":{
        "scriptId":"u36"},
      "480968bad064489eb276b95791c47f09":{
        "scriptId":"u37"},
      "523c14d7ed4e4203a06eb6512ffe4fee":{
        "scriptId":"u38"}},
    "39b7e9ca631f41ecaddbfe28e169dc48":{
      "scriptId":"u39"},
    "f8573a3987ac45339760fc7f05838123":{
      "scriptId":"u40"},
    "81efd492c2ef4b6c94fab6e50fbdf07b":{
      "scriptId":"u41"},
    "1e55a1eeba5949ada439358c06898548":{
      "scriptId":"u42"}}});