$axure.loadCurrentPage({
  "url":"6_3_2_现场买单订单详情.html",
  "generationDate":new Date(1514253436439.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"e6d26a4567eb466d93a0149e0b14bb0c",
    "type":"Axure:Page",
    "name":"6.3.2 现场买单订单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cb3e1a22dac8444cb3dc3e09a4ff50db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":693}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d8ef099f9ef440b95ff62922bd072c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":693}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3_0会员充值/u0.png"}},
{
          "id":"3c6d3eb4cb6040e180fa4f94f9d288df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d6410bb96a41c08f18e30d4b31b962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/u167.png"}},
{
          "id":"704bf8c26d774fe0ae4143254a372a9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e7af9ae70e8410a86edf344d52c6cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u226.png"}},
{
          "id":"2aeff1089a414c4ca2494087e1336054",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":112.5,
              "y":9.5},
            "size":{
              "width":145,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79c31514c06041c29b27838cd0b008ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":112.5,
                  "y":9.5},
                "size":{
                  "width":145,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69853b033e92495bbb13c7f804acb541",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":360,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc671242522445fc85a8d342b06b3a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":360,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_3_2_现场买单订单详情/u8.png"}},
{
          "id":"0fe64356341b4628aa28b41f7a7db5e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":7,
              "y":52},
            "size":{
              "width":127,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"825c053dd63d42d9b4d337b8cb1f15a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":7,
                  "y":52},
                "size":{
                  "width":127,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6900076e906f4f0c971b820f1788355f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":7,
              "y":76},
            "size":{
              "width":183,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82d82ebdd962433d8b756b326120e259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":7,
                  "y":76},
                "size":{
                  "width":183,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0a5d5ddd7ad4c3bb18fc6b4548775f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":200,
              "y":52},
            "size":{
              "width":140,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb1c29413cc440d7b4ca5aa82a5bea61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":200,
                  "y":52},
                "size":{
                  "width":140,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"385d2ab92982494e942711976f403296",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":100},
            "size":{
              "width":144,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24663f2e473a4a948031c94515ccdaf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":100},
                "size":{
                  "width":144,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3afed8934acd4dffba02cea6b1178596",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":341},
            "size":{
              "width":299,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75d862f7611f4c5cb8e65b15edd09e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":341},
                "size":{
                  "width":299,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_3_2_现场买单订单详情/u18.png"}},
{
          "id":"e06307fb686c42798c59080c2ea09ddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":168},
            "size":{
              "width":360,
              "height":151},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bf05840b9084432a2433e1b1dd635b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":168},
                "size":{
                  "width":360,
                  "height":151},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1_1确认订单（现场）/u8.png"}},
{
          "id":"0ce502cec0e74bbfb87164f7c67cf5b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":174},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c424b316381a48a0977570e3f36ff607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":174},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e5568c490b04275960d735779d0aa87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":200},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19da6f1bf1d54c5895b7e3ea628f5063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":200},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"562bdefeee8c40bf8e6c1c368ffa9e10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":226},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd4fe4ebaf5344c8bcabfd6b5db4b902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":226},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8eddd587532e4681b15150f934ae09c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":252},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02ccd8de538f43398cd938bb3524e9ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":252},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c6d4d5189f04f4b947ad4f7f5884e5c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":278},
            "size":{
              "width":333,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/6_1_1确认订单（现场）/u18_line.png"}},
{
          "id":"7568caa00a3849ff840d96ecd10ef9cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":287},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c92f39c5c2d6468786b406d564a6611e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":287},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14b084fb5c8d4ea8baa0b6df999d80d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":141},
            "size":{
              "width":360,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f540bc9c9a2d4102a7fb35bc0dd733b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":141},
                "size":{
                  "width":360,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u129.png"}},
{
          "id":"c251bfd0df7d4c398f99fcfd27983f5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":147},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af5bc562a8214102a63b2ce87081709d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":147},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44bf08402c854104b82f7fd8e54b57ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":283,
              "y":147},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5d0056724534fd2b8495c39749ddf70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":147},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bfc1565d6ab4337a323210492092bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":39},
            "size":{
              "width":330,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1296ac8f85a549638504c5127731fd1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":39},
                "size":{
                  "width":330,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cb3e1a22dac8444cb3dc3e09a4ff50db":{
      "scriptId":"u0"},
    "1d8ef099f9ef440b95ff62922bd072c8":{
      "scriptId":"u1"},
    "3c6d3eb4cb6040e180fa4f94f9d288df":{
      "scriptId":"u2"},
    "e4d6410bb96a41c08f18e30d4b31b962":{
      "scriptId":"u3"},
    "704bf8c26d774fe0ae4143254a372a9e":{
      "scriptId":"u4"},
    "2e7af9ae70e8410a86edf344d52c6cf5":{
      "scriptId":"u5"},
    "2aeff1089a414c4ca2494087e1336054":{
      "scriptId":"u6"},
    "79c31514c06041c29b27838cd0b008ae":{
      "scriptId":"u7"},
    "69853b033e92495bbb13c7f804acb541":{
      "scriptId":"u8"},
    "dc671242522445fc85a8d342b06b3a42":{
      "scriptId":"u9"},
    "0fe64356341b4628aa28b41f7a7db5e4":{
      "scriptId":"u10"},
    "825c053dd63d42d9b4d337b8cb1f15a0":{
      "scriptId":"u11"},
    "6900076e906f4f0c971b820f1788355f":{
      "scriptId":"u12"},
    "82d82ebdd962433d8b756b326120e259":{
      "scriptId":"u13"},
    "d0a5d5ddd7ad4c3bb18fc6b4548775f1":{
      "scriptId":"u14"},
    "cb1c29413cc440d7b4ca5aa82a5bea61":{
      "scriptId":"u15"},
    "385d2ab92982494e942711976f403296":{
      "scriptId":"u16"},
    "24663f2e473a4a948031c94515ccdaf8":{
      "scriptId":"u17"},
    "3afed8934acd4dffba02cea6b1178596":{
      "scriptId":"u18"},
    "75d862f7611f4c5cb8e65b15edd09e83":{
      "scriptId":"u19"},
    "e06307fb686c42798c59080c2ea09ddb":{
      "scriptId":"u20"},
    "8bf05840b9084432a2433e1b1dd635b4":{
      "scriptId":"u21"},
    "0ce502cec0e74bbfb87164f7c67cf5b3":{
      "scriptId":"u22"},
    "c424b316381a48a0977570e3f36ff607":{
      "scriptId":"u23"},
    "5e5568c490b04275960d735779d0aa87":{
      "scriptId":"u24"},
    "19da6f1bf1d54c5895b7e3ea628f5063":{
      "scriptId":"u25"},
    "562bdefeee8c40bf8e6c1c368ffa9e10":{
      "scriptId":"u26"},
    "dd4fe4ebaf5344c8bcabfd6b5db4b902":{
      "scriptId":"u27"},
    "8eddd587532e4681b15150f934ae09c7":{
      "scriptId":"u28"},
    "02ccd8de538f43398cd938bb3524e9ab":{
      "scriptId":"u29"},
    "1c6d4d5189f04f4b947ad4f7f5884e5c":{
      "scriptId":"u30"},
    "7568caa00a3849ff840d96ecd10ef9cf":{
      "scriptId":"u31"},
    "c92f39c5c2d6468786b406d564a6611e":{
      "scriptId":"u32"},
    "14b084fb5c8d4ea8baa0b6df999d80d2":{
      "scriptId":"u33"},
    "f540bc9c9a2d4102a7fb35bc0dd733b7":{
      "scriptId":"u34"},
    "c251bfd0df7d4c398f99fcfd27983f5c":{
      "scriptId":"u35"},
    "af5bc562a8214102a63b2ce87081709d":{
      "scriptId":"u36"},
    "44bf08402c854104b82f7fd8e54b57ba":{
      "scriptId":"u37"},
    "c5d0056724534fd2b8495c39749ddf70":{
      "scriptId":"u38"},
    "0bfc1565d6ab4337a323210492092bc8":{
      "scriptId":"u39"},
    "1296ac8f85a549638504c5127731fd1b":{
      "scriptId":"u40"}}});