$axure.loadCurrentPage({
  "url":"农旅产品详情_1.html",
  "generationDate":new Date(1500456176004.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"174e52fb37ac4a76a9bc9ac4c7c04091",
    "type":"Axure:Page",
    "name":"农旅产品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5b22112a07c9431e853d410e476e6a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4f12348a5a4755ad2d3ab165236d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章列表_1/u0.png"}},
{
          "id":"a0d73aa0c2334190ba9e16dd229ec632",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":430},
            "size":{
              "width":358,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601e37cdb5344c94b60fc5ba21b0fcf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":430},
                "size":{
                  "width":358,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情_1/u2.png"}},
{
          "id":"c9352d30998f480399d9a1df1af63aa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e16382e59d4ec2af48f96a78601490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介_1/u2.png"}},
{
          "id":"872640187cde461995c12c3310c50370",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":41,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f264fdd782a640e8a051e29c9e1b4538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":41,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/平台简介/u4.png"}},
{
          "id":"5d461c2f6d804383a230526066d1af49",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":133,
              "y":9},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f07622d5d71432b9a6ed0a168a2cbaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":133,
                  "y":9},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7b118934fe14d9ab5239efbce7d0154",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":7},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9fe1291e9a1400b8c33ba0fe50605e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":7},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"1095b6aaa09a4e79b08c8cb1c8292c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":17},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc96eba7b7e6441bae995261472d00ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":17},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"c46432eebce64b69a48af648b4a0350e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":334,
              "y":27},
            "size":{
              "width":6,
              "height":6},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba490fe420e48898793bda2c8daa956",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":334,
                  "y":27},
                "size":{
                  "width":6,
                  "height":6},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/平台简介/u8.png"}},
{
          "id":"ac8d0a9515fd49b29df22399721702c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":40},
            "size":{
              "width":358,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc31e2ba88e2436481da83af76cc2d9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":40},
                "size":{
                  "width":358,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情_1/u16.jpg"}},
{
          "id":"9e6ee747a8194bb7a4a565917bea3a07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":170},
            "size":{
              "width":358,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01601dc5b17d4fd18f182bc20110a315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":170},
                "size":{
                  "width":358,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情_1/u18.png"}},
{
          "id":"bc6f77b921be46088ef75ff63bc6d886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":18,
              "y":177},
            "size":{
              "width":335,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa2ce23a8fcf4bd1bd2fecb9894167c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":18,
                  "y":177},
                "size":{
                  "width":335,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c88f54b4a914402878fdbbad17af059",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":18,
              "y":200},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac99e8ed275c4046bbfc8edf588a727c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":200},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c90349b94f849ee890a90e36d0dcbb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":290,
              "y":200},
            "size":{
              "width":52,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6474984dea448e99aa05554453128b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":200},
                "size":{
                  "width":52,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b308430f6a245d28931289927755a50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":473},
            "size":{
              "width":345,
              "height":397}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e112fdfb531f4d6eaa399b9fbd3bb80d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":473},
                "size":{
                  "width":345,
                  "height":397}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"508646b57bdc4d0f870a0cbda8a2f019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":280},
            "size":{
              "width":358,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd5e34b904c49f586ec2ea21c9e5239",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":280},
                "size":{
                  "width":358,
                  "height":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情_1/u28.png"}},
{
          "id":"3bdadf7945b64ea39e03c5d7fa355704",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":307},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品列表_1/u168_line.png"}},
{
          "id":"16882a03adbc42498bbe79586f3d05b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":290},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fab233f02d3f447c9fac4275528b3760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":290},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"415e049068cb4ef5be1e5772a44c7f68",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":460},
            "size":{
              "width":360,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商品列表_1/u168_line.png"}},
{
          "id":"d99648621d8c4b8e91eb346c6aec293b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":444},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ea1648a33e410b97622f34fc4067fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":444},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be536668f8214536bc45b42c3e0450a6",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":617},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a4f7aa4e19f641e8b4993cfeb29fc1d6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fd3d1d584f89425a875fe53a6e5ccf98",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c77c0443d9e3434e8e1dfa687e81d699",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/蜜桃/u40.png"}},
{
                  "id":"2c7f38d48cd04868a034ad8d4dd5377b",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":11,
                      "y":15},
                    "size":{
                      "width":79,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23d1294ea53b4a949181e0be3250f22e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":11,
                          "y":15},
                        "size":{
                          "width":79,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"87f67b9f575c49c1b2b77cbcd47d666a",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b7470335b3349268edd928af8583437",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 确认预约时间",
                              "target":{
                                "targetType":"page",
                                "url":"确认预约时间_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/定时配送_1/u63.png"}},
{
                  "id":"e2bf6cb02f154ab4b766d4be385d22c7",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"10px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":23},
                    "size":{
                      "width":43,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7863a2233bc6461691a1ee8f36a5d27f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"10px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":23},
                        "size":{
                          "width":43,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b3514b79a9cc4714a92821f258c2aad9",
                  "label":"",
                  "parentDynamicPanel":"be536668f8214536bc45b42c3e0450a6",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":24},
                    "size":{
                      "width":49,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/农旅产品详情/u56_line.png"}}]}]},
{
          "id":"73475256d2134522b56b8c970eb53201",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":358,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f287cac7b0374c8893d2e32b8dd08047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":358,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 商品列表",
                      "target":{
                        "targetType":"page",
                        "url":"商品列表_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/农场详情_1/u62.png"}},
{
          "id":"4b54912016444821820f4469afcef3f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":242},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"389cacaeb096434e8b47096777d5d0b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":242},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ca84628ec1a410686596a46860a39d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":234},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc9d37cce358435c89bc92bcc5cef08d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":234},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品列表/u27.png"}},
{
          "id":"78baf9a4f28d4a919807a49ff7d9c157",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":235.5},
            "size":{
              "width":29,
              "height":29},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4e4c8bec39d49a1a9974fd48b6f787d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":235.5},
                "size":{
                  "width":29,
                  "height":29},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/农旅产品详情/u40.png"}},
{
          "id":"ad959bb75a7c4270b054aac4c99b7248",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 农场详情",
                      "target":{
                        "targetType":"page",
                        "url":"农场详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7392da7f49764b6b80819c3756c0d27a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":327},
            "size":{
              "width":324,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c121799d2abb431fa257569077cf23cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":327},
                "size":{
                  "width":324,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5b22112a07c9431e853d410e476e6a60":{
      "scriptId":"u0"},
    "6c4f12348a5a4755ad2d3ab165236d46":{
      "scriptId":"u1"},
    "a0d73aa0c2334190ba9e16dd229ec632":{
      "scriptId":"u2"},
    "601e37cdb5344c94b60fc5ba21b0fcf8":{
      "scriptId":"u3"},
    "c9352d30998f480399d9a1df1af63aa1":{
      "scriptId":"u4"},
    "43e16382e59d4ec2af48f96a78601490":{
      "scriptId":"u5"},
    "872640187cde461995c12c3310c50370":{
      "scriptId":"u6"},
    "f264fdd782a640e8a051e29c9e1b4538":{
      "scriptId":"u7"},
    "5d461c2f6d804383a230526066d1af49":{
      "scriptId":"u8"},
    "7f07622d5d71432b9a6ed0a168a2cbaa":{
      "scriptId":"u9"},
    "b7b118934fe14d9ab5239efbce7d0154":{
      "scriptId":"u10"},
    "e9fe1291e9a1400b8c33ba0fe50605e6":{
      "scriptId":"u11"},
    "1095b6aaa09a4e79b08c8cb1c8292c95":{
      "scriptId":"u12"},
    "bc96eba7b7e6441bae995261472d00ce":{
      "scriptId":"u13"},
    "c46432eebce64b69a48af648b4a0350e":{
      "scriptId":"u14"},
    "3ba490fe420e48898793bda2c8daa956":{
      "scriptId":"u15"},
    "ac8d0a9515fd49b29df22399721702c1":{
      "scriptId":"u16"},
    "dc31e2ba88e2436481da83af76cc2d9a":{
      "scriptId":"u17"},
    "9e6ee747a8194bb7a4a565917bea3a07":{
      "scriptId":"u18"},
    "01601dc5b17d4fd18f182bc20110a315":{
      "scriptId":"u19"},
    "bc6f77b921be46088ef75ff63bc6d886":{
      "scriptId":"u20"},
    "fa2ce23a8fcf4bd1bd2fecb9894167c7":{
      "scriptId":"u21"},
    "7c88f54b4a914402878fdbbad17af059":{
      "scriptId":"u22"},
    "ac99e8ed275c4046bbfc8edf588a727c":{
      "scriptId":"u23"},
    "1c90349b94f849ee890a90e36d0dcbb0":{
      "scriptId":"u24"},
    "b6474984dea448e99aa05554453128b6":{
      "scriptId":"u25"},
    "8b308430f6a245d28931289927755a50":{
      "scriptId":"u26"},
    "e112fdfb531f4d6eaa399b9fbd3bb80d":{
      "scriptId":"u27"},
    "508646b57bdc4d0f870a0cbda8a2f019":{
      "scriptId":"u28"},
    "6bd5e34b904c49f586ec2ea21c9e5239":{
      "scriptId":"u29"},
    "3bdadf7945b64ea39e03c5d7fa355704":{
      "scriptId":"u30"},
    "16882a03adbc42498bbe79586f3d05b9":{
      "scriptId":"u31"},
    "fab233f02d3f447c9fac4275528b3760":{
      "scriptId":"u32"},
    "415e049068cb4ef5be1e5772a44c7f68":{
      "scriptId":"u33"},
    "d99648621d8c4b8e91eb346c6aec293b":{
      "scriptId":"u34"},
    "20ea1648a33e410b97622f34fc4067fe":{
      "scriptId":"u35"},
    "be536668f8214536bc45b42c3e0450a6":{
      "scriptId":"u36"},
    "fd3d1d584f89425a875fe53a6e5ccf98":{
      "scriptId":"u37"},
    "c77c0443d9e3434e8e1dfa687e81d699":{
      "scriptId":"u38"},
    "2c7f38d48cd04868a034ad8d4dd5377b":{
      "scriptId":"u39"},
    "23d1294ea53b4a949181e0be3250f22e":{
      "scriptId":"u40"},
    "87f67b9f575c49c1b2b77cbcd47d666a":{
      "scriptId":"u41"},
    "7b7470335b3349268edd928af8583437":{
      "scriptId":"u42"},
    "e2bf6cb02f154ab4b766d4be385d22c7":{
      "scriptId":"u43"},
    "7863a2233bc6461691a1ee8f36a5d27f":{
      "scriptId":"u44"},
    "b3514b79a9cc4714a92821f258c2aad9":{
      "scriptId":"u45"},
    "73475256d2134522b56b8c970eb53201":{
      "scriptId":"u46"},
    "f287cac7b0374c8893d2e32b8dd08047":{
      "scriptId":"u47"},
    "4b54912016444821820f4469afcef3f2":{
      "scriptId":"u48"},
    "389cacaeb096434e8b47096777d5d0b7":{
      "scriptId":"u49"},
    "8ca84628ec1a410686596a46860a39d7":{
      "scriptId":"u50"},
    "cc9d37cce358435c89bc92bcc5cef08d":{
      "scriptId":"u51"},
    "78baf9a4f28d4a919807a49ff7d9c157":{
      "scriptId":"u52"},
    "c4e4c8bec39d49a1a9974fd48b6f787d":{
      "scriptId":"u53"},
    "ad959bb75a7c4270b054aac4c99b7248":{
      "scriptId":"u54"},
    "7392da7f49764b6b80819c3756c0d27a":{
      "scriptId":"u55"},
    "c121799d2abb431fa257569077cf23cb":{
      "scriptId":"u56"}}});