$axure.loadCurrentPage({
  "url":"时令市场.html",
  "generationDate":new Date(1504186568014.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom"],
  "page":{
    "packageId":"1d11542002914501848254865cb4e91a",
    "type":"Axure:Page",
    "name":"时令市场",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51c8fa84a4664c7dab516ee1a5ba4ce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":777}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f78ca961e44c21a74bb491998af120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":777}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u0.png"}},
{
          "id":"ab5e2bd1ec514d13aa547ad6050ae965",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":697}},
          "adaptiveStyles":{
},
          "masterId":"a652b6c4ffdd4c70aeca0ab75b8386af"},
{
          "id":"583f77eb55b24186a171c94b572acb05",
          "label":"幻灯片",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":358,
              "height":143}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待4000毫秒",
                      "waitTime":4000},
{
                      "action":"setPanelState",
                      "description":"设置 幻灯片 to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["583f77eb55b24186a171c94b572acb05"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]},
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待4000毫秒",
                      "waitTime":4000},
{
                      "action":"setPanelState",
                      "description":"设置 幻灯片 to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap",
                      "panelsToStates":[{
                          "panelPath":["583f77eb55b24186a171c94b572acb05"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2651a0f5c63b4ead995d41070ce5a09a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"507cbb7b1ca24d0897532b570247cec0",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":360,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07e95827a45148e782d68085cc6e58c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":360,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 农旅卡列表",
                              "target":{
                                "targetType":"page",
                                "url":"农旅卡列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u5.png"}},
{
                  "id":"415ffff6b63c434db4699c91cec55aac",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":108,
                      "y":61},
                    "size":{
                      "width":158,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c0aae4d4c5341c8893e64e220a6900c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":108,
                          "y":61},
                        "size":{
                          "width":158,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"a721a1981a974890b9486b6d1e920716",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1522b62b0a094e66a857665639919a44",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":360,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7fc7213bc11440c5aef04cba01f1ee29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":360,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 农旅卡列表",
                              "target":{
                                "targetType":"page",
                                "url":"农旅卡列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u5.png"}},
{
                  "id":"d473ca2052dc488889c9cd791ec2ad8e",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":108,
                      "y":61},
                    "size":{
                      "width":158,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82d31ff70c32402f808ccf5a4566167e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":108,
                          "y":61},
                        "size":{
                          "width":158,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"15ddbe78f280489abd8e447d60af974d",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"236be1fd491c4d35bb6490f68024f68e",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":360,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ca7b72d3ffe41afa66653293c2b8f98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":360,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 农旅卡列表",
                              "target":{
                                "targetType":"page",
                                "url":"农旅卡列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u5.png"}},
{
                  "id":"233bc84418f3439797ecff1a76183d47",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":108,
                      "y":61},
                    "size":{
                      "width":158,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1109bcf0c00542a88afb0c7d3b40a026",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":108,
                          "y":61},
                        "size":{
                          "width":158,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"d3951ad6e2c1491089f0f9fb12df85e4",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"300b66892cdf40049929148212a6d2cd",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":360,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"032387bc4ba84e18a1987f64ce23683a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":360,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 农旅卡列表",
                              "target":{
                                "targetType":"page",
                                "url":"农旅卡列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u5.png"}},
{
                  "id":"ab7ba98d0da74b2bb2b84b884b7efe08",
                  "label":"",
                  "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":108,
                      "y":61},
                    "size":{
                      "width":158,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a877bc6d78fc45b3bbacf7da4559483f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"583f77eb55b24186a171c94b572acb05",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":108,
                          "y":61},
                        "size":{
                          "width":158,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"186685dfb258459b8a4f89be17fd1967",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":143},
            "size":{
              "width":360,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d874751bb32e42d6ba833159bd277049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":143},
                "size":{
                  "width":360,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u49.png"}},
{
          "id":"e0e290488db7445fb2afe862e3033465",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":153},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18fbd6223ef42f7bd2d12d6e7852db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":153},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u51.png"}},
{
          "id":"3d65a1fccb134fd2b5d0ceec2282d269",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":213},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"311bc455a8a34044b1ced4a034d0d5f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":213},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35033d17da0c4f9d8374f6930d0a03bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":153},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c05c2ce0389494ca519eda352889897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":153},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u51.png"}},
{
          "id":"65932e816d954e00921905909d2da7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":213},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5724166c36754395922ed16a08a75ccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":213},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee1d13244b7d45a999ab6151f5e71ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":153},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"163f1c517d1042b6bc28ae96c49da6d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":153},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u51.png"}},
{
          "id":"229289ad1015493a8ceb59331bdb7a12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":153},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d564a46970045fd9d28d4dda1aaef32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":153},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u51.png"}},
{
          "id":"6ed18cc09c7d40058ed8c4ccd90e20ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":213},
            "size":{
              "width":53,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e78a76a36ddb4769823f03e293fb0430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":213},
                "size":{
                  "width":53,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e66506bcef524a2ca3cfc6186412333f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":213},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbfe976822ee42578df5a586259a65cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":213},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eac3e36996c4d5a99d1724fcc4dcf21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":253},
            "size":{
              "width":360,
              "height":257}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f665f51157b4a90a16e4b47ecd21c16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":253},
                "size":{
                  "width":360,
                  "height":257}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u67.png"}},
{
          "id":"a65757650a13476fadfee29c1a72314a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9.5,
              "y":270},
            "size":{
              "width":105,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c03161f63f419eb4462df92a1e65da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9.5,
                  "y":270},
                "size":{
                  "width":105,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u69.png"}},
{
          "id":"b411fa9d71674efdbf78aca8eb940791",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9.5,
              "y":270},
            "size":{
              "width":105,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68a14fede70b4e0a9eb4e33fbfbfbee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9.5,
                  "y":270},
                "size":{
                  "width":105,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u200.jpg"}},
{
          "id":"b522e5223a35447d9354ad6ba4d44dca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":16,
              "y":375},
            "size":{
              "width":65,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f219d6387a74ddcaf0d1589593a1893",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":16,
                  "y":375},
                "size":{
                  "width":65,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"547f3526af1e4bab9eb1f6560fbfb1d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":16,
              "y":394},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d94e98d3344b52bcde52c42d506791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":394},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c59573599766446da94f087ea74f165d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":126.5,
              "y":270},
            "size":{
              "width":105,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47426fcf74d944a78f3882acc66ef842",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126.5,
                  "y":270},
                "size":{
                  "width":105,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u69.png"}},
{
          "id":"d71b52e6161c464eae276401c22ba86e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126.5,
              "y":270},
            "size":{
              "width":107,
              "height":94},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c93f711c19784589802117e94bf9962f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126.5,
                  "y":270},
                "size":{
                  "width":107,
                  "height":94},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u208.png"}},
{
          "id":"d1d69244f226426cb3d2d7a1f927360a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":132,
              "y":375},
            "size":{
              "width":66,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b44337d9416243ae9fa92bd13cd5b84b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":132,
                  "y":375},
                "size":{
                  "width":66,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27ea2b0190c848f1b8492d68c0422d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":134,
              "y":394},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c2e5a23d61647b1982029b1f9126a4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":134,
                  "y":394},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0de116dcc4f74d0f84f12ace9886ed84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":243.5,
              "y":270},
            "size":{
              "width":105,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbfbe3d8dc5640069d3219b20a1393d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243.5,
                  "y":270},
                "size":{
                  "width":105,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/时令市场/u69.png"}},
{
          "id":"a094241dc45c4a00bc82bea9aa89b3e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":250,
              "y":375},
            "size":{
              "width":73,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b414fd6564f48bfac4b2ed52e496991",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":250,
                  "y":375},
                "size":{
                  "width":73,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a49eaa7eba11460994071b1d681f0fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":250,
              "y":394},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0054900778424ea98cb8b49ae60a0cd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":250,
                  "y":394},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bd8d5952de34f298d615549bb63cdd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245.5,
              "y":270},
            "size":{
              "width":105,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d908a14d3134d9aa657d0c7d1619d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245.5,
                  "y":270},
                "size":{
                  "width":105,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u220.jpg"}}]}},
  "masters":{
    "a652b6c4ffdd4c70aeca0ab75b8386af":{
      "packageId":"a652b6c4ffdd4c70aeca0ab75b8386af",
      "type":"Axure:Master",
      "name":"底部菜单0831",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d3980e768e434d6e8006717cfc1027d7",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":-10,
                "y":0},
              "size":{
                "width":360,
                "height":63}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":-10,
            "fixedVertical":"bottom",
            "fixedMarginVertical":0,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"33e17ce2012b4cbda3b4e022b57a30db",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"23869cb13512415b8b7971a663608747",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":23},
                      "size":{
                        "width":360,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3217ebd80ccd40c586ae39ff3ebb1543",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":0,
                            "y":23},
                          "size":{
                            "width":360,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u387.png"}},
{
                    "id":"d004dced895a4eacb5efe917cca36edf",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":29,
                        "y":47},
                      "size":{
                        "width":21,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c8814745f745428db1ec799978487b14",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":29,
                            "y":47},
                          "size":{
                            "width":21,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"410ed3b8921c4b049c59109bbeab49e3",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":92,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a651b47d1e6e452cad7dfe30c2a0ae7c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":92,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"910efa73a76d4b0d9db84006f75ec976",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":299,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a42ded06f7a7420f807e1369cb460d27",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":299,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"6d5a344f556a43e6a407001e342fbfea",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":29,
                        "y":25},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0b939d02785c48368653a620956655b4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":29,
                            "y":25},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u395.png"}},
{
                    "id":"fcf6bc000ad54b73a898b7612b0fd1be",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":310,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e8182f657e0a44b2a22072f4fe191a65",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":310,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u397.png"}},
{
                    "id":"999196b197e840f79974725b89c13987",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":100,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e40a4d1685f84b2eb78df8b3d82849aa",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":100,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u399.png"}},
{
                    "id":"469056e6db7b48ea8beb0cde764fda32",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":229,
                        "y":47},
                      "size":{
                        "width":41,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5cd991483bf843d1ae7045e6e98ebf9b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":229,
                            "y":47},
                          "size":{
                            "width":41,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"78876019e8d742938da830e4d8d4574a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":240,
                        "y":27},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"29d462b7bb7a493b87ec072faf2f5d57",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":240,
                            "y":27},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u403.png"}},
{
                    "id":"e54b788ac95740f0a17b53707d224d1e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":60},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"60"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0322dabe132f4082bf7d358e28e63678",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":150,
                            "y":0},
                          "size":{
                            "width":60,
                            "height":60},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"60"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u405.png"}},
{
                    "id":"4e103bbf5272432fbfcaef86e4b44e2a",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontSize":"10px",
                      "location":{
                        "x":165,
                        "y":39},
                      "size":{
                        "width":31,
                        "height":13}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"12db86e5ca4c477e9addd5bac0cc3d6d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"10px",
                          "location":{
                            "x":165,
                            "y":39},
                          "size":{
                            "width":31,
                            "height":13}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"e0c8b35ab6c640e4bfa3685c98588a2d",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":171,
                        "y":15},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"645a1aecdf08437f99fc444dc99f3e10",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":171,
                            "y":15},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/主页/u409.png"}},
{
                    "id":"c6e97157c788455f9783097231226f7e",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":290,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 个人中心主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"个人中心主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"696eadac344b40088748cf59bc9aaa9b",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":10,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"8de9a287ce1540abbcb6ec1b3c3a6254",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":150,
                        "y":0},
                      "size":{
                        "width":60,
                        "height":60}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 蔬菜箱1",
                                "target":{
                                  "targetType":"page",
                                  "url":"蔬菜箱1.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"480968bad064489eb276b95791c47f09",
                    "label":"",
                    "parentDynamicPanel":"d3980e768e434d6e8006717cfc1027d7",
                    "type":"imageMapRegion",
                    "styleType":"imageMapRegion",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":221,
                        "y":23},
                      "size":{
                        "width":59,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 农旅百科",
                                "target":{
                                  "targetType":"page",
                                  "url":"农旅百科.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}]}]}}},
  "objectPaths":{
    "51c8fa84a4664c7dab516ee1a5ba4ce6":{
      "scriptId":"u0"},
    "02f78ca961e44c21a74bb491998af120":{
      "scriptId":"u1"},
    "ab5e2bd1ec514d13aa547ad6050ae965":{
      "scriptId":"u2",
      "d3980e768e434d6e8006717cfc1027d7":{
        "scriptId":"u3"},
      "23869cb13512415b8b7971a663608747":{
        "scriptId":"u4"},
      "3217ebd80ccd40c586ae39ff3ebb1543":{
        "scriptId":"u5"},
      "d004dced895a4eacb5efe917cca36edf":{
        "scriptId":"u6"},
      "c8814745f745428db1ec799978487b14":{
        "scriptId":"u7"},
      "410ed3b8921c4b049c59109bbeab49e3":{
        "scriptId":"u8"},
      "a651b47d1e6e452cad7dfe30c2a0ae7c":{
        "scriptId":"u9"},
      "910efa73a76d4b0d9db84006f75ec976":{
        "scriptId":"u10"},
      "a42ded06f7a7420f807e1369cb460d27":{
        "scriptId":"u11"},
      "6d5a344f556a43e6a407001e342fbfea":{
        "scriptId":"u12"},
      "0b939d02785c48368653a620956655b4":{
        "scriptId":"u13"},
      "fcf6bc000ad54b73a898b7612b0fd1be":{
        "scriptId":"u14"},
      "e8182f657e0a44b2a22072f4fe191a65":{
        "scriptId":"u15"},
      "999196b197e840f79974725b89c13987":{
        "scriptId":"u16"},
      "e40a4d1685f84b2eb78df8b3d82849aa":{
        "scriptId":"u17"},
      "469056e6db7b48ea8beb0cde764fda32":{
        "scriptId":"u18"},
      "5cd991483bf843d1ae7045e6e98ebf9b":{
        "scriptId":"u19"},
      "78876019e8d742938da830e4d8d4574a":{
        "scriptId":"u20"},
      "29d462b7bb7a493b87ec072faf2f5d57":{
        "scriptId":"u21"},
      "e54b788ac95740f0a17b53707d224d1e":{
        "scriptId":"u22"},
      "0322dabe132f4082bf7d358e28e63678":{
        "scriptId":"u23"},
      "4e103bbf5272432fbfcaef86e4b44e2a":{
        "scriptId":"u24"},
      "12db86e5ca4c477e9addd5bac0cc3d6d":{
        "scriptId":"u25"},
      "e0c8b35ab6c640e4bfa3685c98588a2d":{
        "scriptId":"u26"},
      "645a1aecdf08437f99fc444dc99f3e10":{
        "scriptId":"u27"},
      "c6e97157c788455f9783097231226f7e":{
        "scriptId":"u28"},
      "696eadac344b40088748cf59bc9aaa9b":{
        "scriptId":"u29"},
      "8de9a287ce1540abbcb6ec1b3c3a6254":{
        "scriptId":"u30"},
      "480968bad064489eb276b95791c47f09":{
        "scriptId":"u31"}},
    "583f77eb55b24186a171c94b572acb05":{
      "scriptId":"u32"},
    "507cbb7b1ca24d0897532b570247cec0":{
      "scriptId":"u33"},
    "07e95827a45148e782d68085cc6e58c1":{
      "scriptId":"u34"},
    "415ffff6b63c434db4699c91cec55aac":{
      "scriptId":"u35"},
    "2c0aae4d4c5341c8893e64e220a6900c":{
      "scriptId":"u36"},
    "1522b62b0a094e66a857665639919a44":{
      "scriptId":"u37"},
    "7fc7213bc11440c5aef04cba01f1ee29":{
      "scriptId":"u38"},
    "d473ca2052dc488889c9cd791ec2ad8e":{
      "scriptId":"u39"},
    "82d31ff70c32402f808ccf5a4566167e":{
      "scriptId":"u40"},
    "236be1fd491c4d35bb6490f68024f68e":{
      "scriptId":"u41"},
    "1ca7b72d3ffe41afa66653293c2b8f98":{
      "scriptId":"u42"},
    "233bc84418f3439797ecff1a76183d47":{
      "scriptId":"u43"},
    "1109bcf0c00542a88afb0c7d3b40a026":{
      "scriptId":"u44"},
    "300b66892cdf40049929148212a6d2cd":{
      "scriptId":"u45"},
    "032387bc4ba84e18a1987f64ce23683a":{
      "scriptId":"u46"},
    "ab7ba98d0da74b2bb2b84b884b7efe08":{
      "scriptId":"u47"},
    "a877bc6d78fc45b3bbacf7da4559483f":{
      "scriptId":"u48"},
    "186685dfb258459b8a4f89be17fd1967":{
      "scriptId":"u49"},
    "d874751bb32e42d6ba833159bd277049":{
      "scriptId":"u50"},
    "e0e290488db7445fb2afe862e3033465":{
      "scriptId":"u51"},
    "f18fbd6223ef42f7bd2d12d6e7852db6":{
      "scriptId":"u52"},
    "3d65a1fccb134fd2b5d0ceec2282d269":{
      "scriptId":"u53"},
    "311bc455a8a34044b1ced4a034d0d5f2":{
      "scriptId":"u54"},
    "35033d17da0c4f9d8374f6930d0a03bd":{
      "scriptId":"u55"},
    "2c05c2ce0389494ca519eda352889897":{
      "scriptId":"u56"},
    "65932e816d954e00921905909d2da7cd":{
      "scriptId":"u57"},
    "5724166c36754395922ed16a08a75ccb":{
      "scriptId":"u58"},
    "ee1d13244b7d45a999ab6151f5e71ea1":{
      "scriptId":"u59"},
    "163f1c517d1042b6bc28ae96c49da6d5":{
      "scriptId":"u60"},
    "229289ad1015493a8ceb59331bdb7a12":{
      "scriptId":"u61"},
    "1d564a46970045fd9d28d4dda1aaef32":{
      "scriptId":"u62"},
    "6ed18cc09c7d40058ed8c4ccd90e20ca":{
      "scriptId":"u63"},
    "e78a76a36ddb4769823f03e293fb0430":{
      "scriptId":"u64"},
    "e66506bcef524a2ca3cfc6186412333f":{
      "scriptId":"u65"},
    "cbfe976822ee42578df5a586259a65cb":{
      "scriptId":"u66"},
    "5eac3e36996c4d5a99d1724fcc4dcf21":{
      "scriptId":"u67"},
    "0f665f51157b4a90a16e4b47ecd21c16":{
      "scriptId":"u68"},
    "a65757650a13476fadfee29c1a72314a":{
      "scriptId":"u69"},
    "87c03161f63f419eb4462df92a1e65da":{
      "scriptId":"u70"},
    "b411fa9d71674efdbf78aca8eb940791":{
      "scriptId":"u71"},
    "68a14fede70b4e0a9eb4e33fbfbfbee9":{
      "scriptId":"u72"},
    "b522e5223a35447d9354ad6ba4d44dca":{
      "scriptId":"u73"},
    "3f219d6387a74ddcaf0d1589593a1893":{
      "scriptId":"u74"},
    "547f3526af1e4bab9eb1f6560fbfb1d0":{
      "scriptId":"u75"},
    "46d94e98d3344b52bcde52c42d506791":{
      "scriptId":"u76"},
    "c59573599766446da94f087ea74f165d":{
      "scriptId":"u77"},
    "47426fcf74d944a78f3882acc66ef842":{
      "scriptId":"u78"},
    "d71b52e6161c464eae276401c22ba86e":{
      "scriptId":"u79"},
    "c93f711c19784589802117e94bf9962f":{
      "scriptId":"u80"},
    "d1d69244f226426cb3d2d7a1f927360a":{
      "scriptId":"u81"},
    "b44337d9416243ae9fa92bd13cd5b84b":{
      "scriptId":"u82"},
    "27ea2b0190c848f1b8492d68c0422d3b":{
      "scriptId":"u83"},
    "1c2e5a23d61647b1982029b1f9126a4d":{
      "scriptId":"u84"},
    "0de116dcc4f74d0f84f12ace9886ed84":{
      "scriptId":"u85"},
    "dbfbe3d8dc5640069d3219b20a1393d0":{
      "scriptId":"u86"},
    "a094241dc45c4a00bc82bea9aa89b3e9":{
      "scriptId":"u87"},
    "5b414fd6564f48bfac4b2ed52e496991":{
      "scriptId":"u88"},
    "a49eaa7eba11460994071b1d681f0fb5":{
      "scriptId":"u89"},
    "0054900778424ea98cb8b49ae60a0cd3":{
      "scriptId":"u90"},
    "2bd8d5952de34f298d615549bb63cdd4":{
      "scriptId":"u91"},
    "9d908a14d3134d9aa657d0c7d1619d0c":{
      "scriptId":"u92"}}});