$axure.loadCurrentPage({
  "url":"6_1_1确认订单（现场）.html",
  "generationDate":new Date(1515740160123.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"ad601912e6334128a8e5d9b1f5e454c5",
    "type":"Axure:Page",
    "name":"6.1.1确认订单（现场）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3300dd42f7044054a188fadae28ea8a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"161b4955496746329c9ebd7bfb32deaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_2登录/u0.png"}},
{
          "id":"fff60701c84b40baa1598e2ea1921069",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327e839beba84b309851895fc939e161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"9f3dc8eea07448d584e1452acb0bf146",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f9fe2b29a6d48ca81cd7cc2bedefc9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"0d48a3d946f544d0a77f367932692cfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":9},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ca2a925d80b4f76b7d9386ad71fda1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":9},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53b7e307a6744a8cac49e362932a8d5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":66},
            "size":{
              "width":360,
              "height":151},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b67804c1a644ed78c5c2e6586fafd2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":360,
                  "height":151},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1_1确认订单（现场）/u8.png"}},
{
          "id":"aaeba75b1b054f9b9ccdc2a5689269e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":72},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6523e749c1436191b169dae840f8bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":72},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59602142ad534552aa869caafd73f8a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":98},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4f85a8eb35946cdaf07c33137fe4e89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":98},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a9220ff3b8d41c9926796d51ce0d640",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":124},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daaf6317bd5f41b599f4a99a509f0d3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":124},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed9ab1960f024ac9a284fa05c35edc5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":150},
            "size":{
              "width":310,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ecc46b9d2b1409f9ae35460b1ce443b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":150},
                "size":{
                  "width":310,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae173a12d85e4305bce4156cf1a8e104",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":176},
            "size":{
              "width":333,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/6_1_1确认订单（现场）/u18_line.png"}},
{
          "id":"0bebbd8cebc64b42ad907202c0dad03a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":185},
            "size":{
              "width":84,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c9245c46af5425b80f57c1ce4dd9251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":185},
                "size":{
                  "width":84,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"782014112c764852af0956d5224f1155",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":512},
            "size":{
              "width":360,
              "height":50}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4a261f9293db45e9b0a70eda55b0d188",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"658f314eab944ba8b216d8289f0fa8a7",
                  "label":"",
                  "parentDynamicPanel":"782014112c764852af0956d5224f1155",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "size":{
                      "width":360,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6fdf4bea9fb4dd2b739b3687e229cf0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"782014112c764852af0956d5224f1155",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "size":{
                          "width":360,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/2_2_3_1确认订单（农旅）/u67.png"}},
{
                  "id":"125d91f0afbb49d6bbcc055d2de70a74",
                  "label":"",
                  "parentDynamicPanel":"782014112c764852af0956d5224f1155",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":9,
                      "y":13},
                    "size":{
                      "width":144,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7e3b907086a4ba4a024e5de4e280631",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"782014112c764852af0956d5224f1155",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":9,
                          "y":13},
                        "size":{
                          "width":144,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f02f573e654b408e97a8e2c6e4d03173",
                  "label":"",
                  "parentDynamicPanel":"782014112c764852af0956d5224f1155",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a80e773451024283b4cb9a89112bbb66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"782014112c764852af0956d5224f1155",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":210,
                          "y":0},
                        "size":{
                          "width":150,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/4_2_2确认订单/u67.png"}}]}]},
{
          "id":"77de596453c04709ab397fe36bb89055",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":360,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0da80275024a4466807b498c59392c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":360,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u129.png"}},
{
          "id":"39e924fa11f74429ae55bde24b9061d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":45},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef5daf258fde40c287db5f6e6848e2fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":45},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e501f305019454e834086cbe549c553",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":283,
              "y":45},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5ac616e633423fa7c853c625f21074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":283,
                  "y":45},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96f9e403a80b4f98b715f51891575e90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":227},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df4e09d7ed104fe380b19c8fcab1ce75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":227},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u121.png"}},
{
          "id":"041158d3be6c4338971679f863db685e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":239},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"017d9d756fb947709494802f66e9ac35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":239},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9878ce29fec14d739ec4fc9383f2934c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":239},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73d8919fec304a618e746da8f4960e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":239},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09095a83f4f7404f8adb4ca0fb4fe8b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9a1bc857f5441690ced9a87333d178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":265},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u121.png"}},
{
          "id":"2e6917926cce4c2c979cbe9b5345a03c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":279},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413b9a4d78204549890f3f60bdfabdc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":279},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6dbd27654304b948d66c77c2502b0b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":279},
            "size":{
              "width":37,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"becbd949f1b14f21a3d64166f90b4b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":279},
                "size":{
                  "width":37,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d27c7d853e3d495aa63d7112164d4621",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":304},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47f11c608c164b7e92ea5891c799db2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":304},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u121.png"}},
{
          "id":"d817bb25e414410aaf197ecfbb7400f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":316},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c5b89708a44b5dbd648c93cbbcdff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":316},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5502f5e1679442a822be3498f44f07c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":300,
              "y":316},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13b9839c13014dbf87d6397f70ddf670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":316},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a28dc952505d423e85e51b18561abff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":79,
              "y":316},
            "size":{
              "width":62,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da0b0c94068e414da56525dfceb772bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":79,
                  "y":316},
                "size":{
                  "width":62,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4881759d9ded4455a9a2d97b8aa64fef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":342},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83dc148869e244a5b63f625e7497d5ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":342},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u121.png"}},
{
          "id":"a30d29f9bb2241c4bbce29dc8ce242cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":354},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a35d966dc043f7aeddc44d724ffa38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":354},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c40c6255802d4f0f9f9af3b5ee4d0b11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":306,
              "y":354},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1029df46fce148aca0ceea26537ad149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":354},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c23da2a41fe4abeb7e73dc71e7204c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":392},
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAAAAAA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad316aa878cb44b789bc0f70708a691f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":392},
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAAAAAA}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2_2_1确认订单_宅配_/u121.png"}},
{
          "id":"645fc441739c4b198f19170a9c5801c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79cda94e92d846b592c31da51335e3fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e59d8a9590174785882fca41e16187d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":396},
            "size":{
              "width":29,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf840011fec842c891cd0b132b76d0b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":396},
                "size":{
                  "width":29,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1_2农场体验游详情/u40.png"}},
{
          "id":"918ac384a4c9472596cd05fe0eaaf9cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":404},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9227957bdf7416a9b2e5732c45d9feb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":404},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"895f05d8d4f54d81995815bcce755588",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":304},
            "size":{
              "width":360,
              "height":38}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "3300dd42f7044054a188fadae28ea8a9":{
      "scriptId":"u0"},
    "161b4955496746329c9ebd7bfb32deaf":{
      "scriptId":"u1"},
    "fff60701c84b40baa1598e2ea1921069":{
      "scriptId":"u2"},
    "327e839beba84b309851895fc939e161":{
      "scriptId":"u3"},
    "9f3dc8eea07448d584e1452acb0bf146":{
      "scriptId":"u4"},
    "4f9fe2b29a6d48ca81cd7cc2bedefc9d":{
      "scriptId":"u5"},
    "0d48a3d946f544d0a77f367932692cfc":{
      "scriptId":"u6"},
    "0ca2a925d80b4f76b7d9386ad71fda1e":{
      "scriptId":"u7"},
    "53b7e307a6744a8cac49e362932a8d5a":{
      "scriptId":"u8"},
    "2b67804c1a644ed78c5c2e6586fafd2f":{
      "scriptId":"u9"},
    "aaeba75b1b054f9b9ccdc2a5689269e9":{
      "scriptId":"u10"},
    "8b6523e749c1436191b169dae840f8bc":{
      "scriptId":"u11"},
    "59602142ad534552aa869caafd73f8a3":{
      "scriptId":"u12"},
    "d4f85a8eb35946cdaf07c33137fe4e89":{
      "scriptId":"u13"},
    "6a9220ff3b8d41c9926796d51ce0d640":{
      "scriptId":"u14"},
    "daaf6317bd5f41b599f4a99a509f0d3a":{
      "scriptId":"u15"},
    "ed9ab1960f024ac9a284fa05c35edc5a":{
      "scriptId":"u16"},
    "1ecc46b9d2b1409f9ae35460b1ce443b":{
      "scriptId":"u17"},
    "ae173a12d85e4305bce4156cf1a8e104":{
      "scriptId":"u18"},
    "0bebbd8cebc64b42ad907202c0dad03a":{
      "scriptId":"u19"},
    "2c9245c46af5425b80f57c1ce4dd9251":{
      "scriptId":"u20"},
    "782014112c764852af0956d5224f1155":{
      "scriptId":"u21"},
    "658f314eab944ba8b216d8289f0fa8a7":{
      "scriptId":"u22"},
    "b6fdf4bea9fb4dd2b739b3687e229cf0":{
      "scriptId":"u23"},
    "125d91f0afbb49d6bbcc055d2de70a74":{
      "scriptId":"u24"},
    "c7e3b907086a4ba4a024e5de4e280631":{
      "scriptId":"u25"},
    "f02f573e654b408e97a8e2c6e4d03173":{
      "scriptId":"u26"},
    "a80e773451024283b4cb9a89112bbb66":{
      "scriptId":"u27"},
    "77de596453c04709ab397fe36bb89055":{
      "scriptId":"u28"},
    "0da80275024a4466807b498c59392c09":{
      "scriptId":"u29"},
    "39e924fa11f74429ae55bde24b9061d6":{
      "scriptId":"u30"},
    "ef5daf258fde40c287db5f6e6848e2fa":{
      "scriptId":"u31"},
    "2e501f305019454e834086cbe549c553":{
      "scriptId":"u32"},
    "eb5ac616e633423fa7c853c625f21074":{
      "scriptId":"u33"},
    "96f9e403a80b4f98b715f51891575e90":{
      "scriptId":"u34"},
    "df4e09d7ed104fe380b19c8fcab1ce75":{
      "scriptId":"u35"},
    "041158d3be6c4338971679f863db685e":{
      "scriptId":"u36"},
    "017d9d756fb947709494802f66e9ac35":{
      "scriptId":"u37"},
    "9878ce29fec14d739ec4fc9383f2934c":{
      "scriptId":"u38"},
    "73d8919fec304a618e746da8f4960e33":{
      "scriptId":"u39"},
    "09095a83f4f7404f8adb4ca0fb4fe8b4":{
      "scriptId":"u40"},
    "cb9a1bc857f5441690ced9a87333d178":{
      "scriptId":"u41"},
    "2e6917926cce4c2c979cbe9b5345a03c":{
      "scriptId":"u42"},
    "413b9a4d78204549890f3f60bdfabdc3":{
      "scriptId":"u43"},
    "c6dbd27654304b948d66c77c2502b0b3":{
      "scriptId":"u44"},
    "becbd949f1b14f21a3d64166f90b4b8e":{
      "scriptId":"u45"},
    "d27c7d853e3d495aa63d7112164d4621":{
      "scriptId":"u46"},
    "47f11c608c164b7e92ea5891c799db2e":{
      "scriptId":"u47"},
    "d817bb25e414410aaf197ecfbb7400f5":{
      "scriptId":"u48"},
    "f5c5b89708a44b5dbd648c93cbbcdff5":{
      "scriptId":"u49"},
    "f5502f5e1679442a822be3498f44f07c":{
      "scriptId":"u50"},
    "13b9839c13014dbf87d6397f70ddf670":{
      "scriptId":"u51"},
    "a28dc952505d423e85e51b18561abff2":{
      "scriptId":"u52"},
    "da0b0c94068e414da56525dfceb772bf":{
      "scriptId":"u53"},
    "4881759d9ded4455a9a2d97b8aa64fef":{
      "scriptId":"u54"},
    "83dc148869e244a5b63f625e7497d5ec":{
      "scriptId":"u55"},
    "a30d29f9bb2241c4bbce29dc8ce242cc":{
      "scriptId":"u56"},
    "b7a35d966dc043f7aeddc44d724ffa38":{
      "scriptId":"u57"},
    "c40c6255802d4f0f9f9af3b5ee4d0b11":{
      "scriptId":"u58"},
    "1029df46fce148aca0ceea26537ad149":{
      "scriptId":"u59"},
    "5c23da2a41fe4abeb7e73dc71e7204c6":{
      "scriptId":"u60"},
    "ad316aa878cb44b789bc0f70708a691f":{
      "scriptId":"u61"},
    "645fc441739c4b198f19170a9c5801c3":{
      "scriptId":"u62"},
    "79cda94e92d846b592c31da51335e3fd":{
      "scriptId":"u63"},
    "e59d8a9590174785882fca41e16187d1":{
      "scriptId":"u64"},
    "cf840011fec842c891cd0b132b76d0b2":{
      "scriptId":"u65"},
    "918ac384a4c9472596cd05fe0eaaf9cd":{
      "scriptId":"u66"},
    "a9227957bdf7416a9b2e5732c45d9feb":{
      "scriptId":"u67"},
    "895f05d8d4f54d81995815bcce755588":{
      "scriptId":"u68"}}});