$axure.loadCurrentPage({
  "url":"2_8_3验证身份.html",
  "generationDate":new Date(1521193993464.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"bf362b59028a437cb96a1132f6ca69e5",
    "type":"Axure:Page",
    "name":"2.8.3验证身份",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"74cc9d8d8ba246e4abf6dd2e4d80c78b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":684}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ee762f499c41fb8ffb48a0b4d97a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":684}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_1我的农旅卡（待激活）/u0.png"}},
{
          "id":"c25446b915ea4f0dbf70cdf6dc8deb25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f33d03800cf744558453509cc43a4af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页/u2.png"}},
{
          "id":"6f0a8edc4c574c9ca545728d63cd1bae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c261967c02e14e09b2c14acb3f6142b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"908e96eef6134ff0931c9eb7faad23d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":134,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2db7fa232734191b4af08f19d6707b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":134,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"484b10182ed343ebaa4f6f3f980d83f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":260},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aaedc2e1756411db8793b5e24379334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":260},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.8.2 设置支付密码",
                      "target":{
                        "targetType":"page",
                        "url":"2_8_2_设置支付密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_8_2_设置支付密码/u36.png"}},
{
          "id":"4a724e8fa19e45ba942b2189902ca7d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":50},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84153446a4b24915bbda2d740b2e81f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":50},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a17cbcae1b64fd4b110e48e77291d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":30,
              "y":125},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80c437e5c314798a92b9e7f49e64d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":125},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15a60fcc04e244e0bbf491a5ea0b4bcf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":141},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aa81e306397440c28765bd693222729f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":30,
              "y":173},
            "size":{
              "width":56,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15b4c9c8f4d3499a85d3764c840c6769",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":30,
                  "y":173},
                "size":{
                  "width":56,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"837c2501a97040bf883af0b35798d1ec",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":195},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1511e6ba4f8d41eb8eb2a7983722b326",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":220,
              "y":195},
            "size":{
              "width":89,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38dab6b169044cdba4f504de6644ceb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":220,
                  "y":195},
                "size":{
                  "width":89,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_2登录/u20.png"}},
{
          "id":"cadc6098a01849d6bd85868f46928083",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":141},
            "size":{
              "width":89,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4408f36071724c7db547ed7231216af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":141},
                "size":{
                  "width":89,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_2登录/u26.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "74cc9d8d8ba246e4abf6dd2e4d80c78b":{
      "scriptId":"u0"},
    "09ee762f499c41fb8ffb48a0b4d97a97":{
      "scriptId":"u1"},
    "c25446b915ea4f0dbf70cdf6dc8deb25":{
      "scriptId":"u2"},
    "f33d03800cf744558453509cc43a4af1":{
      "scriptId":"u3"},
    "6f0a8edc4c574c9ca545728d63cd1bae":{
      "scriptId":"u4"},
    "c261967c02e14e09b2c14acb3f6142b8":{
      "scriptId":"u5"},
    "908e96eef6134ff0931c9eb7faad23d2":{
      "scriptId":"u6"},
    "f2db7fa232734191b4af08f19d6707b3":{
      "scriptId":"u7"},
    "484b10182ed343ebaa4f6f3f980d83f6":{
      "scriptId":"u8"},
    "6aaedc2e1756411db8793b5e24379334":{
      "scriptId":"u9"},
    "4a724e8fa19e45ba942b2189902ca7d5":{
      "scriptId":"u10"},
    "84153446a4b24915bbda2d740b2e81f6":{
      "scriptId":"u11"},
    "1a17cbcae1b64fd4b110e48e77291d83":{
      "scriptId":"u12"},
    "f80c437e5c314798a92b9e7f49e64d08":{
      "scriptId":"u13"},
    "15a60fcc04e244e0bbf491a5ea0b4bcf":{
      "scriptId":"u14"},
    "aa81e306397440c28765bd693222729f":{
      "scriptId":"u15"},
    "15b4c9c8f4d3499a85d3764c840c6769":{
      "scriptId":"u16"},
    "837c2501a97040bf883af0b35798d1ec":{
      "scriptId":"u17"},
    "1511e6ba4f8d41eb8eb2a7983722b326":{
      "scriptId":"u18"},
    "38dab6b169044cdba4f504de6644ceb2":{
      "scriptId":"u19"},
    "cadc6098a01849d6bd85868f46928083":{
      "scriptId":"u20"},
    "4408f36071724c7db547ed7231216af8":{
      "scriptId":"u21"}}});