$axure.loadCurrentPage({
  "url":"6_4_扫码支付.html",
  "generationDate":new Date(1519785533311.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"fcf0d5f2794c45f6a0de19dd91fb8220",
    "type":"Axure:Page",
    "name":"6.4 扫码支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e81618cff8c47d4aa653634ca78daab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "size":{
              "width":360,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb2f936a2e8447ee8e7de457e70c5ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "size":{
                  "width":360,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_2登录/u0.png"}},
{
          "id":"68df06cd10574b48b940754b4f1c4b4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-38,
              "y":41},
            "size":{
              "width":398,
              "height":109}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ca01256b304fc2b6731560732bb8b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-38,
                  "y":41},
                "size":{
                  "width":398,
                  "height":109}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_4_扫码支付/u2.png"}},
{
          "id":"a985d32bfe674faba9c8a4066928f30e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":51},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2431bff0d16a4bdbbe677ee200a7e7e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":51},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_1现场特惠买单/u6.png"}},
{
          "id":"e51b4d0f85524813b8decd65f8c1fbd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":58},
            "size":{
              "width":79,
              "height":16},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf61e049627479385e95830aa3d4a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":58},
                "size":{
                  "width":79,
                  "height":16},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f62e6c9c2004307b92d2a0700cd4ce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2162a51e2e1b434abbe6430d72053031",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/0_0主页/top_u178.png"}},
{
          "id":"4f4b805ba0404e6cab170757e4cfc518",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219c0ba9eb0842ff9e063d7389ddf420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"748ebed735d3468893a42215c7e30220",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":143.5,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea5e51fd2f3466caa08273cf5893e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":143.5,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf961e5101e64053a3a1202b693d6fd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":12},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d34ee825597a4b2995742797952b3ee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":12},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.8.1资金账单",
                      "target":{
                        "targetType":"page",
                        "url":"2_8_1资金账单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ec190744026476a9695f2cc5d9491d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":100},
            "size":{
              "width":130,
              "height":35},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d78b696eb4c24cfe8c7a7d9b32c5a093",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":100},
                "size":{
                  "width":130,
                  "height":35},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"设置 值于 recharge = &quot;spot&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"recharge"},
{
                                "exprType":"stringLiteral",
                                "value":"spot",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/6_1现场特惠买单/u127.png"}},
{
          "id":"c26d69f33bae4710bf65978e94667f88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":196,
              "y":100},
            "size":{
              "width":130,
              "height":35},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb8ed8750ae4436b6d6f4f5e987c40e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":196,
                  "y":100},
                "size":{
                  "width":130,
                  "height":35},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 7.3农场店铺页",
                      "target":{
                        "targetType":"page",
                        "url":"7_3农场店铺页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/6_1现场特惠买单/u127.png"}},
{
          "id":"48dc0f74fcba40658404a226308a18c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11.5,
              "y":190},
            "size":{
              "width":337,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cdee71c414b45378d524bd478c1a318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11.5,
                  "y":190},
                "size":{
                  "width":337,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_4_扫码支付/u20.png"}},
{
          "id":"301fd119b73141efb5c088ee8784b217",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":22,
              "y":202},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c974880cade84b2dbab0d4728c45c7a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":22,
                  "y":202},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"615424147c764617a612d7ac02a910a9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":91.5,
              "y":191},
            "size":{
              "width":250,
              "height":38}},
          "adaptiveStyles":{
}},
{
          "id":"fc16f1d7ebc34a45bed41f8e574a4e2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":11,
              "y":295},
            "size":{
              "width":337,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1ace2f00f349d28f5b93c2dae55c47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":11,
                  "y":295},
                "size":{
                  "width":337,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6_4_扫码支付/u25.png"}},
{
          "id":"6dde525f7f8248f0b840ed36ceef4764",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":19,
              "y":240},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8804263d96364038bd24dd8547aa18a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":240},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91f1dde1d96341268b69708f327c22b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF9900,
              "opacity":1},
            "location":{
              "x":298,
              "y":244},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1964c0d476334364ac14542947aee648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900,
                  "opacity":1},
                "location":{
                  "x":298,
                  "y":244},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7001bb51fe9441db226c605e4ca2bc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":82,
              "y":242},
            "size":{
              "width":95,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"191865e23ea04564ae7b2dbbc8148901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":242},
                "size":{
                  "width":95,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1e81618cff8c47d4aa653634ca78daab":{
      "scriptId":"u0"},
    "bb2f936a2e8447ee8e7de457e70c5ada":{
      "scriptId":"u1"},
    "68df06cd10574b48b940754b4f1c4b4e":{
      "scriptId":"u2"},
    "69ca01256b304fc2b6731560732bb8b3":{
      "scriptId":"u3"},
    "a985d32bfe674faba9c8a4066928f30e":{
      "scriptId":"u4"},
    "2431bff0d16a4bdbbe677ee200a7e7e5":{
      "scriptId":"u5"},
    "e51b4d0f85524813b8decd65f8c1fbd8":{
      "scriptId":"u6"},
    "3bf61e049627479385e95830aa3d4a78":{
      "scriptId":"u7"},
    "3f62e6c9c2004307b92d2a0700cd4ce7":{
      "scriptId":"u8"},
    "2162a51e2e1b434abbe6430d72053031":{
      "scriptId":"u9"},
    "4f4b805ba0404e6cab170757e4cfc518":{
      "scriptId":"u10"},
    "219c0ba9eb0842ff9e063d7389ddf420":{
      "scriptId":"u11"},
    "748ebed735d3468893a42215c7e30220":{
      "scriptId":"u12"},
    "fea5e51fd2f3466caa08273cf5893e4e":{
      "scriptId":"u13"},
    "cf961e5101e64053a3a1202b693d6fd5":{
      "scriptId":"u14"},
    "d34ee825597a4b2995742797952b3ee7":{
      "scriptId":"u15"},
    "9ec190744026476a9695f2cc5d9491d7":{
      "scriptId":"u16"},
    "d78b696eb4c24cfe8c7a7d9b32c5a093":{
      "scriptId":"u17"},
    "c26d69f33bae4710bf65978e94667f88":{
      "scriptId":"u18"},
    "feb8ed8750ae4436b6d6f4f5e987c40e":{
      "scriptId":"u19"},
    "48dc0f74fcba40658404a226308a18c8":{
      "scriptId":"u20"},
    "7cdee71c414b45378d524bd478c1a318":{
      "scriptId":"u21"},
    "301fd119b73141efb5c088ee8784b217":{
      "scriptId":"u22"},
    "c974880cade84b2dbab0d4728c45c7a5":{
      "scriptId":"u23"},
    "615424147c764617a612d7ac02a910a9":{
      "scriptId":"u24"},
    "fc16f1d7ebc34a45bed41f8e574a4e2f":{
      "scriptId":"u25"},
    "7f1ace2f00f349d28f5b93c2dae55c47":{
      "scriptId":"u26"},
    "6dde525f7f8248f0b840ed36ceef4764":{
      "scriptId":"u27"},
    "8804263d96364038bd24dd8547aa18a9":{
      "scriptId":"u28"},
    "91f1dde1d96341268b69708f327c22b6":{
      "scriptId":"u29"},
    "1964c0d476334364ac14542947aee648":{
      "scriptId":"u30"},
    "f7001bb51fe9441db226c605e4ca2bc6":{
      "scriptId":"u31"},
    "191865e23ea04564ae7b2dbbc8148901":{
      "scriptId":"u32"}}});