$axure.loadCurrentPage({
  "url":"11_4_农旅生活卡权益.html",
  "generationDate":new Date(1523326606610.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"status",
"package",
"payFrom",
"nc",
"carNum",
"recharge"],
  "page":{
    "packageId":"85e4f7e12e6c44ed8f544a51b10299a6",
    "type":"Axure:Page",
    "name":"11.4 农旅生活卡权益",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"68e8344abd36403098d426c351e3dd21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFDDDDDD},
            "location":{
              "x":0,
              "y":-17},
            "size":{
              "width":360,
              "height":657}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3a4106cd654232a19baa1b9d037b62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD},
                "location":{
                  "x":0,
                  "y":-17},
                "size":{
                  "width":360,
                  "height":657}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_4_农旅生活卡权益/u0.png"}},
{
          "id":"5d5463258c5e4662b685da909c5eec94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fc008a1725941819166c1621f57d911",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页/u2.png"}},
{
          "id":"9a08ec17f25e44abb4e853c5e670582b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":39,
              "height":41},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a9cb2cd1964bba9e6a5581376f1f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":39,
                  "height":41},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/0_0主页/u180.png"}},
{
          "id":"5e81736b1ac146898c4e988bf8ea355a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":134,
              "y":9},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab54a2edc29648849c07b8c29d4f2bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":134,
                  "y":9},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc6c69f3df95499cb9217f3180dd94da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":40},
            "size":{
              "width":215,
              "height":143}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d61f1405d0a5401aa5cd4f741bc82286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":40},
                "size":{
                  "width":215,
                  "height":143}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_0农旅卡主题页/u8.png"}},
{
          "id":"351c5d7a29564e0289cff92a95667fea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":187},
            "size":{
              "width":20,
              "height":20},
            "rotation":"45",
            "textRotation":"45",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af93cb07e8d44912a4e116b82b5440fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":187},
                "size":{
                  "width":20,
                  "height":20},
                "rotation":"45",
                "textRotation":"45",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_1我的农旅卡（待激活）/u10.png"}},
{
          "id":"16806abc45ba40a0b5c0316f6fbeb82d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":193},
            "size":{
              "width":360,
              "height":447},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b215be9645f44c7ab6f5c53d137c750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":193},
                "size":{
                  "width":360,
                  "height":447},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_4_农旅生活卡权益/u12.png"}},
{
          "id":"c3ff7457fd4449bea3b14aa7965d2917",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":160,
              "y":60},
            "size":{
              "width":67,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daa562b9976940b3865163b2561617e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":60},
                "size":{
                  "width":67,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"530c22409bf746a7a66418d29fde8c78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":211},
            "size":{
              "width":340,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef98a90fc18a448386ad78ac4ac9d96e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":211},
                "size":{
                  "width":340,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2我的农旅卡/u16.png"}},
{
          "id":"bd997f52aab54ac39dce37d51bca7043",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":218},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4797e346a63141529057374f440b93e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":218},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e82bf8e3d7674233ae85387a3d983d1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":239},
            "size":{
              "width":340,
              "height":111},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ec432fc88443e39d46f65193c6bbab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":239},
                "size":{
                  "width":340,
                  "height":111},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2我的农旅卡/u20.png"}},
{
          "id":"55c5545674a842cb86ccbd3b4d6065b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":349},
            "size":{
              "width":340,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f805ac374a941c29c1c76e26b4bdfa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":349},
                "size":{
                  "width":340,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2我的农旅卡/u22.png"}},
{
          "id":"bd917f50210844f98fef32e811d7c220",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":252},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d432bf78b17842609421428eb94bd87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":252},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1选择指定农场/u16.jpg"}},
{
          "id":"a93b1b34d41f49439be3f4ec8254b9c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":252},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d593625f2ab0471884a94394571d0fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":252},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1选择指定农场/u18.jpg"}},
{
          "id":"7ede697f643449d6a4a127afef49ea2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":250},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d95507fafdcb407a9235d98b7349ca36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":250},
                "size":{
                  "width":60,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1_1选择指定农场/u20.jpg"}},
{
          "id":"877cf41927d948178c42d6aaae467777",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":18,
              "y":312},
            "size":{
              "width":56,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e98ba82dd594d90bf4d93caed325490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":18,
                  "y":312},
                "size":{
                  "width":56,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f8ca062a9f040a7bdbb585062215549",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "location":{
              "x":99,
              "y":312},
            "size":{
              "width":67,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3455449453134281887cc7e280e86f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "location":{
                  "x":99,
                  "y":312},
                "size":{
                  "width":67,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e86db30e69894a33b15c0ecd3f62a2f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":187,
              "y":312},
            "size":{
              "width":46,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13bc7f51fa3e41ecb990e506233f629c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":187,
                  "y":312},
                "size":{
                  "width":46,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98821be19b3b40438e5f49f64010914f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":240,
              "y":354},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b47a23d6ba14ef797d7e40c3dbf17a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":240,
                  "y":354},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2.2.2.1确认订单(宅配)",
                      "target":{
                        "targetType":"page",
                        "url":"2_2_2_1确认订单_宅配_.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2我的农旅卡/u36.png"}},
{
          "id":"effd157a200e41a1bafa396cb92f7be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":399},
            "size":{
              "width":340,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc59841f980e43baba441f9b24ed709a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":399},
                "size":{
                  "width":340,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2我的农旅卡/u16.png"}},
{
          "id":"4da4703a69f641afbab8054094d56d7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":406},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53e84bddc80240d4aeeb05f19acaaeec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":406},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"745152eda31d407ab00a5c8b605be091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":427},
            "size":{
              "width":340,
              "height":73},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c4d6a8e5da5419aba1a38b6567b75ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":427},
                "size":{
                  "width":340,
                  "height":73},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2我的农旅卡/u42.png"}},
{
          "id":"d04c63f95ec3429d88ac6fcda90b449c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":499},
            "size":{
              "width":340,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db67876ca4f2420085f3d9b4ad0fd45e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":499},
                "size":{
                  "width":340,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2_2我的农旅卡/u22.png"}},
{
          "id":"be93d84b980c4f6799a246b5cf7ac0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6600},
            "location":{
              "x":240,
              "y":504},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"580990c0c7d84e7e8365cc24ae4a3e50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6600},
                "location":{
                  "x":240,
                  "y":504},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 11.5 权益景区列表",
                      "target":{
                        "targetType":"page",
                        "url":"11_5_权益景区列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/2_2我的农旅卡/u36.png"}},
{
          "id":"0a4aed08bf7246c4acce7481ff457379",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":112,
              "y":448},
            "size":{
              "width":138,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556f54b028f041629a08cbb4f98a0e65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":112,
                  "y":448},
                "size":{
                  "width":138,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc2dffc6b25d4e1287b1d428b5cf50b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":158,
              "y":132},
            "size":{
              "width":137,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa21cbe8dfd04f0d9b4756e3a1ba680c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":132},
                "size":{
                  "width":137,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e056b77ee244d22a8ebbf457756ddd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":158,
              "y":94},
            "size":{
              "width":144,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2f4dd427874a958bd23f1bdd167400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":158,
                  "y":94},
                "size":{
                  "width":144,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8f9db67838841b4bf836185083056f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":360},
            "size":{
              "width":133,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274523360e8c4e129181c643e82e0f5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":360},
                "size":{
                  "width":133,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eecebbf6a8a407a91f848960e2cd5f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":510},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8dab72c5a64ed1adf771ea2c171511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":510},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d44e41671234d15ab958fc3fb6050f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":51},
            "size":{
              "width":97,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13f39ce80c44f53bba52898dff70a32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":51},
                "size":{
                  "width":97,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/11_4_农旅生活卡权益/u58.png"}},
{
          "id":"bc1b916d64a14f6086f1e5663ebfb4b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":150},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"276832f823094af79e739a27d93812a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":150},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "68e8344abd36403098d426c351e3dd21":{
      "scriptId":"u0"},
    "6d3a4106cd654232a19baa1b9d037b62":{
      "scriptId":"u1"},
    "5d5463258c5e4662b685da909c5eec94":{
      "scriptId":"u2"},
    "5fc008a1725941819166c1621f57d911":{
      "scriptId":"u3"},
    "9a08ec17f25e44abb4e853c5e670582b":{
      "scriptId":"u4"},
    "a3a9cb2cd1964bba9e6a5581376f1f3d":{
      "scriptId":"u5"},
    "5e81736b1ac146898c4e988bf8ea355a":{
      "scriptId":"u6"},
    "ab54a2edc29648849c07b8c29d4f2bfa":{
      "scriptId":"u7"},
    "cc6c69f3df95499cb9217f3180dd94da":{
      "scriptId":"u8"},
    "d61f1405d0a5401aa5cd4f741bc82286":{
      "scriptId":"u9"},
    "351c5d7a29564e0289cff92a95667fea":{
      "scriptId":"u10"},
    "af93cb07e8d44912a4e116b82b5440fb":{
      "scriptId":"u11"},
    "16806abc45ba40a0b5c0316f6fbeb82d":{
      "scriptId":"u12"},
    "0b215be9645f44c7ab6f5c53d137c750":{
      "scriptId":"u13"},
    "c3ff7457fd4449bea3b14aa7965d2917":{
      "scriptId":"u14"},
    "daa562b9976940b3865163b2561617e5":{
      "scriptId":"u15"},
    "530c22409bf746a7a66418d29fde8c78":{
      "scriptId":"u16"},
    "ef98a90fc18a448386ad78ac4ac9d96e":{
      "scriptId":"u17"},
    "bd997f52aab54ac39dce37d51bca7043":{
      "scriptId":"u18"},
    "4797e346a63141529057374f440b93e6":{
      "scriptId":"u19"},
    "e82bf8e3d7674233ae85387a3d983d1d":{
      "scriptId":"u20"},
    "89ec432fc88443e39d46f65193c6bbab":{
      "scriptId":"u21"},
    "55c5545674a842cb86ccbd3b4d6065b2":{
      "scriptId":"u22"},
    "0f805ac374a941c29c1c76e26b4bdfa9":{
      "scriptId":"u23"},
    "bd917f50210844f98fef32e811d7c220":{
      "scriptId":"u24"},
    "d432bf78b17842609421428eb94bd87d":{
      "scriptId":"u25"},
    "a93b1b34d41f49439be3f4ec8254b9c1":{
      "scriptId":"u26"},
    "d593625f2ab0471884a94394571d0fb7":{
      "scriptId":"u27"},
    "7ede697f643449d6a4a127afef49ea2a":{
      "scriptId":"u28"},
    "d95507fafdcb407a9235d98b7349ca36":{
      "scriptId":"u29"},
    "877cf41927d948178c42d6aaae467777":{
      "scriptId":"u30"},
    "9e98ba82dd594d90bf4d93caed325490":{
      "scriptId":"u31"},
    "4f8ca062a9f040a7bdbb585062215549":{
      "scriptId":"u32"},
    "3455449453134281887cc7e280e86f94":{
      "scriptId":"u33"},
    "e86db30e69894a33b15c0ecd3f62a2f3":{
      "scriptId":"u34"},
    "13bc7f51fa3e41ecb990e506233f629c":{
      "scriptId":"u35"},
    "98821be19b3b40438e5f49f64010914f":{
      "scriptId":"u36"},
    "9b47a23d6ba14ef797d7e40c3dbf17a8":{
      "scriptId":"u37"},
    "effd157a200e41a1bafa396cb92f7be3":{
      "scriptId":"u38"},
    "dc59841f980e43baba441f9b24ed709a":{
      "scriptId":"u39"},
    "4da4703a69f641afbab8054094d56d7d":{
      "scriptId":"u40"},
    "53e84bddc80240d4aeeb05f19acaaeec":{
      "scriptId":"u41"},
    "745152eda31d407ab00a5c8b605be091":{
      "scriptId":"u42"},
    "0c4d6a8e5da5419aba1a38b6567b75ef":{
      "scriptId":"u43"},
    "d04c63f95ec3429d88ac6fcda90b449c":{
      "scriptId":"u44"},
    "db67876ca4f2420085f3d9b4ad0fd45e":{
      "scriptId":"u45"},
    "be93d84b980c4f6799a246b5cf7ac0db":{
      "scriptId":"u46"},
    "580990c0c7d84e7e8365cc24ae4a3e50":{
      "scriptId":"u47"},
    "0a4aed08bf7246c4acce7481ff457379":{
      "scriptId":"u48"},
    "556f54b028f041629a08cbb4f98a0e65":{
      "scriptId":"u49"},
    "dc2dffc6b25d4e1287b1d428b5cf50b5":{
      "scriptId":"u50"},
    "aa21cbe8dfd04f0d9b4756e3a1ba680c":{
      "scriptId":"u51"},
    "6e056b77ee244d22a8ebbf457756ddd1":{
      "scriptId":"u52"},
    "1d2f4dd427874a958bd23f1bdd167400":{
      "scriptId":"u53"},
    "d8f9db67838841b4bf836185083056f6":{
      "scriptId":"u54"},
    "274523360e8c4e129181c643e82e0f5f":{
      "scriptId":"u55"},
    "2eecebbf6a8a407a91f848960e2cd5f3":{
      "scriptId":"u56"},
    "6b8dab72c5a64ed1adf771ea2c171511":{
      "scriptId":"u57"},
    "7d44e41671234d15ab958fc3fb6050f9":{
      "scriptId":"u58"},
    "b13f39ce80c44f53bba52898dff70a32":{
      "scriptId":"u59"},
    "bc1b916d64a14f6086f1e5663ebfb4b0":{
      "scriptId":"u60"},
    "276832f823094af79e739a27d93812a4":{
      "scriptId":"u61"}}});